CREATE OR REPLACE FUNCTION F_NEXT_TRAIL_ID RETURN VARCHAR2 IS
NEXT_TRAIL_ID VARCHAR2(30);

BEGIN
   
  /* Formatted on 5/7/2021 3:10:02 PM (QP5 v5.354) */
SELECT 'BPT' || NUMBERS
  INTO NEXT_TRAIL_ID
  FROM (  SELECT REGEXP_REPLACE(NE_UNIQUE, '[^0-9]', '') + 1 NUMBERS
            FROM NM_ELEMENTS@METRANS
           WHERE NE_GTY_GROUP_TYPE = 'RTRL'
        ORDER BY NE_DATE_CREATED DESC NULLS LAST)
  WHERE ROWNUM = 1;
  RETURN NEXT_TRAIL_ID;
  
  EXCEPTION
	WHEN OTHERS THEN
		RETURN null;

END F_NEXT_TRAIL_ID ;
/
