CREATE OR REPLACE VIEW WH_ASSETS.CINDY_TEMP_ACCIDENT_VIEW
BEQUEATH DEFINER
AS 
SELECT                                          --ACCIDENTS.ACCIDENT_DATE,
           --           ACCIDENTS.ACCIDENT_DAY_OF_WEEK,
           --           ACCIDENTS.ACCIDENT_DAY_OF_WEEK_NUM,
           --           ACCIDENTS.ACCIDENT_HOUR,
           --           ACCIDENTS.ACCIDENT_MONTH_NAME,
           --           ACCIDENTS.ACCIDENT_MONTH_NUM,
           --           ACCIDENTS.ACCIDENT_TIME,
           --           ACCIDENTS.ACCIDENT_YEAR,
           --           ACCIDENTS.CONTRIB_CIRC_ENV1,
           --           ACCIDENTS.CONTRIB_CIRC_ENV1_DESCR,
           --           ACCIDENTS.CONTRIB_CIRC_ENV2,
           --           ACCIDENTS.CONTRIB_CIRC_ENV2_DESCR,
           --           ACCIDENTS.CONTRIB_CIRC_ROAD1,
           --           ACCIDENTS.CONTRIB_CIRC_ROAD1_DESCR,
           --           ACCIDENTS.CONTRIB_CIRC_ROAD2,
           --           ACCIDENTS.CONTRIB_CIRC_ROAD2_DESCR,
           --           ACCIDENTS.COUNTY_CODE,
           --           ACCIDENTS.COUNTY_NAME,
           --           ACCIDENTS.CRASH_COST,
           ACCIDENTS.ELEMENT_ID,
           --           ACCIDENTS.FEDERAL_URBAN_GROUP,
           --           ACCIDENTS.FEDERAL_URBAN_GROUP_DESCR,
           ACCIDENTS.element_wid,
           --           ACCIDENTS.INJURY_COUNT,
           --           ACCIDENTS.INJURY_LEVEL,
           --           ACCIDENTS.INJURY_LEVEL_CODE,
           --           ACCIDENTS.LATITUDE,
           --           ACCIDENTS.LIGHT_CONDITION,
           --           ACCIDENTS.LIGHT_CONDITION_DESCR,
           ACCIDENTS.LOCATION_TYPE,
           --           ACCIDENTS.LOC_FIRST_HARMFUL_EVENT,
           --           ACCIDENTS.LOC_FIRST_HARMFUL_EVENT_DESCR,
           --           ACCIDENTS.LONGITUDE,
           ACCIDENTS.MDOTID,
           ACCIDENTS.NODE_ID,
           --           ACCIDENTS.NO_OF_A_INJ,
           --           ACCIDENTS.NO_OF_B_INJ,
           --           ACCIDENTS.NO_OF_C_INJ,
           --           ACCIDENTS.NO_OF_K_INJ,
           --           ACCIDENTS.NO_OF_NON_INJ,
           --           ACCIDENTS.OFFSET,
           --           ACCIDENTS.PRIMARY_ROUTE_MP,
           --           ACCIDENTS.PRIMARY_ROUTE_NAME,
           --           ACCIDENTS.PRIMARY_ROUTE_NUMBER,
           --           ACCIDENTS.REGION_CODE,
           --           ACCIDENTS.REGION_NAME,
           --           ACCIDENTS.REPORTING_AGENCY,
           --           ACCIDENTS.REPORTING_AGENCY_DESCR,
           --           ACCIDENTS.REPORT_NUMBER,
           --           ACCIDENTS.ROAD_GRADE,
           --           ACCIDENTS.ROAD_GRADE_DESCR,
           --           ACCIDENTS.ROAD_SURF_COND,
           --           ACCIDENTS.ROAD_SURF_COND_DESCR,
           --           ACCIDENTS.SCHOOL_BUS_RELATED,
           --           ACCIDENTS.SCHOOL_BUS_RELATED_DESCR,
           ACCIDENTS.SECTION_ID,
           --           ACCIDENTS.SPEED_LIMIT,
           --           ACCIDENTS.TOWN_CODE,
           --           ACCIDENTS.TOWN_NAME,
           --           ACCIDENTS.TRAFFIC_CONTROL_DEVICE,
           --           ACCIDENTS.TRAFFIC_CONTROL_DEVICE_DESCR,
           --           ACCIDENTS.TRF_CNTRL_DEV_OPRATIONL,
           --           ACCIDENTS.TRF_CNTRL_DEV_OPRATIONL_DESCR,
           --           ACCIDENTS.TYPE_OF_CRASH,
           --           ACCIDENTS.TYPE_OF_CRASH_DESCR,
           --           ACCIDENTS.TYPE_OF_LOCATION,
           --           ACCIDENTS.TYPE_OF_LOCATION_DESCR,
           --           ACCIDENTS.WEATHER_CONDITION,
           --           ACCIDENTS.WEATHER_CONDITION_DESCR,
           --           ACCIDENTS.WORKZONE_IN_OR_NEAR,
           --           ACCIDENTS.WORKZONE_IN_OR_NEAR_DESCR,
           --           ACCIDENTS.WORKZONE_LOCATION,
           --           ACCIDENTS.WORKZONE_LOCATION_DESCR,
           --           ACCIDENTS.WORKZONE_POLICE_PRESENT,
           --           ACCIDENTS.WORKZONE_POLICE_PRESENT_DESCR,
           --           ACCIDENTS.WORKZONE_TYPE,
           --           ACCIDENTS.WORKZONE_TYPE_DESCR,
           --           ACCIDENTS.WORKZONE_WORKERS_PRESENT,
           --           ACCIDENTS.WORKZONE_WORKERS_PRESENT_DESCR,
           --           ROADWAY_SECTIONS.AADT,
           --           ROADWAY_SECTIONS.AADT_TYPE,
           --           ROADWAY_SECTIONS.AADT_TYPE_DESCR,
           --           ROADWAY_SECTIONS.AADT_YEAR,
           --           ROADWAY_SECTIONS.ABN,
           --           ROADWAY_SECTIONS.ABN_DESCR,
           --           ROADWAY_SECTIONS.ACCESS_CONTROL,
           --           ROADWAY_SECTIONS.ACCESS_CONTROL_DESCR,
           --           ROADWAY_SECTIONS.AGENCY,
           --           ROADWAY_SECTIONS.AGENCY_DESCR,
           --           ROADWAY_SECTIONS.BEGIN_OFFSET,             -- BEGIN_SECTION_OFFSET,
           --           ROUTE_SECTIONS.BEGIN_SECTION_MP,
           --           ROADWAY_SECTIONS.BRIDGE_POSTING_CSL,
           --           ROADWAY_SECTIONS.BRIDGE_RELIABILITY_CSL,
           --           ROADWAY_SECTIONS.CAPACITY,
           --           ROADWAY_SECTIONS.CONDITION_CSL,
           --           ROADWAY_SECTIONS.CONGESTION_CSL,
           --           ROADWAY_SECTIONS.CONGESTION_RATE_CSL,
           --           ROADWAY_SECTIONS.CRASH_HISTORY_CSL,
           --           ROADWAY_SECTIONS.CRASH_HISTORY_RATE_CSL,
           --           ROADWAY_SECTIONS.CSL_YEAR,
           --           ROUTE_SECTIONS.CUMULATIVE_MILEPOINT_ORDER,
           --           ROADWAY_SECTIONS.DEFENSE_HIGHWAY,
           --           ROADWAY_SECTIONS.DEFENSE_HIGHWAY_DESCR,
           --           HIGHWAYS.DIRECTIONAL_SUFFIX,
           --           HIGHWAYS.ELEMENT_LENGTH,
           --           ROADWAY_SECTIONS.END_OFFSET,                 -- END_SECTION_OFFSET,
           --           ROUTE_SECTIONS.END_SECTION_MP,
           --           HIGHWAYS.EXISTING,
           --           ROADWAY_SECTIONS.FACTORED_AADT,
           --           HIGHWAYS.FACTOR_GROUP,
           --           ROADWAY_SECTIONS.FACTOR_YEAR,
           --           ROADWAY_SECTIONS.FEDERAL_FUNCTIONAL_CLASS,
           --           ROADWAY_SECTIONS.FEDERAL_FUNCTIONAL_CLASS_DESCR,
           --           ROADWAY_SECTIONS.FEDERAL_URBAN_RURAL,
           --           ROADWAY_SECTIONS.FEDERAL_URBAN_RURAL_DESCR,
           --           ROADWAY_SECTIONS.FUTURE_ADT,
           --           ROADWAY_SECTIONS.FUTURE_ADT_YEAR,
           --           ROADWAY_SECTIONS.HASS_DESCRIPTION,
           --           ROADWAY_SECTIONS.HUNDRED_MILLION_VEHICLE_MILES,
           --           ROADWAY_SECTIONS.IRI,
           --           ROADWAY_SECTIONS.LANE_COUNT,
           --           ROADWAY_SECTIONS.LEFT_RUT,
           --           ROADWAY_SECTIONS.LEFT_SHOULDER_TYPE,
           --           ROADWAY_SECTIONS.LEFT_SHOULDER_TYPE_DESCR,
           --           ROADWAY_SECTIONS.LEFT_SHOULDER_WIDTH,
           --           ROADWAY_SECTIONS.MAINT_RESP_WINTER,
           --           ROADWAY_SECTIONS.MAINT_RESP_WINTER_DESCR,
           --           ROADWAY_SECTIONS.MAINT_RESP_YEARROUND,
           --           ROADWAY_SECTIONS.MAINT_RESP_YEAR_DESCR,
           --           ROADWAY_SECTIONS.MEAN_SUM_DEFLECTION_CSL,
           --           ROADWAY_SECTIONS.MEDIAN_AVERAGE_WIDTH,
           --           ROADWAY_SECTIONS.MEDIAN_TYPE,
           --           ROADWAY_SECTIONS.MEDIAN_TYPE_DESCR,
           --           ROADWAY_SECTIONS.MIN_PAVEMENT_WIDTH_CSL,
           --           ROADWAY_SECTIONS.MIN_STRUCT_BRIDGE_COND_CSL,
           --           ROADWAY_SECTIONS.NATIONAL_TRUCK_NETWORK,
           --           ROADWAY_SECTIONS.NATIONAL_TRUCK_NETWORK_DESCR,
           --           ROADWAY_SECTIONS.NHS_STATUS,
           --           HIGHWAYS.NUMBER_OF_LANES,
           --           HIGHWAYS.OFFICIAL_MILES,
           --           HIGHWAYS.ONE_WAY,
           --           HIGHWAYS.ONE_WAY_DESCR,
           --           ROADWAY_SECTIONS.OWNER,
           --           ROADWAY_SECTIONS.OWNER_DESCR,
           --           ROADWAY_SECTIONS.PAVEMENT_CONDITION_CSL,
           --           ROADWAY_SECTIONS.PAVEMENT_RUTTING_CSL,
           --           ROADWAY_SECTIONS.PAVEMENT_WIDTH_CSL,
           --           ROADWAY_SECTIONS.PCR,
           --           ROADWAY_SECTIONS.PLOW_CREW,
           --           ROADWAY_SECTIONS.PMS_FILE_NAME,
           --           ROADWAY_SECTIONS.PMS_INVENTORY_YEAR,
           --           ROADWAY_SECTIONS.PRIORITY,
           --           HIGHWAYS.RAMP,
           --           HIGHWAYS.RAMP_DESCR,
           --           ROADWAY_SECTIONS.RECOMMENDATION_DATE,
           --           ROADWAY_SECTIONS.RECOMMENDED_NEXT_TREATMENT,
           --           ROADWAY_SECTIONS.RECOMMENDED_TREATMENT_YEAR,
           --           HIGHWAYS.REGION,
           --           HIGHWAYS.REGION_DESCR,
           --           ROADWAY_SECTIONS.RIDE_QUALITY_CSL,
           --           ROADWAY_SECTIONS.RIGHT_RUT,
           --           ROADWAY_SECTIONS.RIGHT_SHOULDER_TYPE,
           --           ROADWAY_SECTIONS.RIGHT_SHOULDER_TYPE_DESCR,
           --           ROADWAY_SECTIONS.RIGHT_SHOULDER_WIDTH,
           --           ROADWAY_SECTIONS.ROADWAY_STRENGTH_CSL,
           --           ROADWAY_SECTIONS.ROADWAY_TYPE,
           --           ROADWAY_SECTIONS.ROADWAY_TYPE_DESCR,
           --           ROADWAY_SECTIONS.ROAD_POSTING_CSL,
           --           HIGHWAYS.ROUTE_SYSTEM,
           --           HIGHWAYS.ROUTE_SYSTEM_DESCR,
           --           ROADWAY_SECTIONS.RUT_CSL,
           --           ROADWAY_SECTIONS.SAFETY_CSL,
           --           ROADWAY_SECTIONS.SCENIC_BYWAY_DESCRIPTION,
           --           ROADWAY_SECTIONS.SCENIC_BYWAY_DESIG_YR,
           --           ROADWAY_SECTIONS.SCENIC_BYWAY_NAME,
           --           ROADWAY_SECTIONS.SCENIC_BYWAY_TYPE,
           --           ROADWAY_SECTIONS.SCENIC_BYWAY_TYPE_DESCR,
           --           ROADWAY_SECTIONS.SECTION_LENGTH,
           --           ROADWAY_SECTIONS.SERVICE_CSL,
           --           ROADWAY_SECTIONS.SPEED_ZONE,
           --           ROADWAY_SECTIONS.STATE_DESIG_TYPE,
           --           ROADWAY_SECTIONS.STATE_DESIG_TYPE_DESCR,
           --           ROADWAY_SECTIONS.STATE_URBAN_RURAL,
           --           ROADWAY_SECTIONS.STATE_URBAN_RURAL_DESCR,
           --           ROADWAY_SECTIONS.STREET_NAME,
           --           ROADWAY_SECTIONS.STREET_NAME_PREFIX,
           --           ROADWAY_SECTIONS.STREET_NAME_SUFFIX,
           --           ROADWAY_SECTIONS.STRUCT_BRIDGE_COND_CSL,
           --           ROADWAY_SECTIONS.SUMMER_CREW,
           --           ROADWAY_SECTIONS.THRU_LANE_COUNT,
           --           ROADWAY_SECTIONS.TOTAL_PAVEMENT_WIDTH,
           --           ROADWAY_SECTIONS.TRUCK_PERCENT,
           --           ROADWAY_SECTIONS.WEIGHTED_IRI_CSL,
           --           ROADWAY_SECTIONS.WEIGHTED_PCR_CSL,
           --           ROADWAY_SECTIONS.WIDTH,
           --           ROADWAY_SECTIONS.WINTER_CREW,
           --           ROADWAY_SECTIONS.YEAR_OF_LAST_WORK,
           --           NULL,                                         -- COLUMNS FROM NODES
           --           NULL,
           --           NULL,
           --           NULL,
           --           NULL,
           ROUTE_SECTIONS.ROUTE_NUMBER,
          ROUTE_SECTIONS.ROUTE_NAME,
           --           CASE
           --               WHEN ROUTE_SECTIONS.direction = 1
           --               THEN
           --                   ROUND (
           --                         ROUTE_SECTIONS.begin_element_milepoint
           --                       + ACCIDENTS.OFFSET,
           --                       2)
           --               WHEN ROUTE_SECTIONS.direction = -1
           --               THEN
           --                   ROUND (
           --                         ROUTE_SECTIONS.end_element_milepoint
           --                       - ACCIDENTS.OFFSET,
           --                       2)
           --           END
           --               "Milepoint",
           --           NULL, --       JURISDICTION  (IN NODES TABLE, BUT NOT IN ROADWAY_SECTIONS YET),
           --           ROADWAY_SECTIONS.CREATED_BY,
           --           ROADWAY_SECTIONS.DATE_CREATED,
           --           ROADWAY_SECTIONS.DATE_MODIFIED,
           --           ROADWAY_SECTIONS.END_DATE,
           --           ROADWAY_SECTIONS.MODIFIED_BY,
           --           ROADWAY_SECTIONS.SNAPSHOT_YEAR,
           --           ROADWAY_SECTIONS.START_DATE,
           --           ROADWAY_SECTIONS.STATE
           route_sections.route_number   AS route_sections_route_number,
           wh_common.dim_routes.route_number AS dim_routes_route_number
      FROM ACCIDENTS
           LEFT OUTER JOIN elements
               ON ACCIDENTS.element_wid = elements.element_wid
           LEFT OUTER JOIN SECTIONS
               ON ACCIDENTS.SECTION_ID = SECTIONS.SECTION_ID
           LEFT OUTER JOIN ROUTE_SECTIONS
               ON SECTIONS.SECTION_ID = ROUTE_SECTIONS.SECTION_ID
           LEFT OUTER JOIN wh_common.dim_routes
               ON route_sections.route_number =
                  wh_common.dim_routes.route_number
     WHERE                                     --accidents.element_id = 227438
               -- ACCIDENTS.LOCATION_TYPE = 'ELEMENT'
               --       AND wh_common.dim_routes.route_system <> 'PMS ROUTE'
               accidents.element_id IS NOT NULL
           AND ACCIDENTS.mdotid IN ('2013-10229',
                                    '2013-1451',
                                    '2013-14775',
                                    '2013-15333',
                                    '2013-15466',
                                    '2013-1585',
                                    '2013-1616',
                                    '2013-16558',
                                    '2013-17220',
                                    '2013-18679',
                                    '2013-18709',
                                    '2013-19979',
                                    '2013-20912',
                                    '2013-21507',
                                    '2013-21646',
                                    '2013-23725',
                                    '2013-24805',
                                    '2013-2679',
                                    '2013-27199',
                                    '2013-28079',
                                    '2013-29337',
                                    '2013-30835',
                                    '2013-31166',
                                    '2013-31984',
                                    '2013-32178',
                                    '2013-3305',
                                    '2013-33148',
                                    '2013-33952',
                                    '2013-342',
                                    '2013-35123',
                                    '2013-36017',
                                    '2013-3614',
                                    '2013-36196',
                                    '2013-36476',
                                    '2013-36478',
                                    '2013-36486',
                                    '2013-3783',
                                    '2013-435',
                                    '2013-4486',
                                    '2013-594',
                                    '2013-6085',
                                    '2013-706',
                                    '2013-7940',
                                    '2013-7981',
                                    '2013-7982',
                                    '2013-8673',
                                    '2013-9541',
                                    '2013-9642',
                                    '2013-9740',
                                    '2013-9890',
                                    '2014-10096',
                                    '2014-10860',
                                    '2014-11345',
                                    '2014-11714',
                                    '2014-12071',
                                    '2014-12081',
                                    '2014-12545',
                                    '2014-12581',
                                    '2014-14977',
                                    '2014-15715',
                                    '2014-15826',
                                    '2014-15828',
                                    '2014-16267',
                                    '2014-16889',
                                    '2014-16912',
                                    '2014-17138',
                                    '2014-18758',
                                    '2014-19012',
                                    '2014-19201',
                                    '2014-20097',
                                    '2014-21542',
                                    '2014-236',
                                    '2014-23689',
                                    '2014-26070',
                                    '2014-26340',
                                    '2014-28661',
                                    '2014-29080',
                                    '2014-29555',
                                    '2014-29744',
                                    '2014-29791',
                                    '2014-30083',
                                    '2014-30705',
                                    '2014-30853',
                                    '2014-31044',
                                    '2014-31355',
                                    '2014-32544',
                                    '2014-33830',
                                    '2014-34716',
                                    '2014-34971',
                                    '2014-36005',
                                    '2014-37231',
                                    '2014-37860',
                                    '2014-4163',
                                    '2014-6316',
                                    '2014-6374',
                                    '2014-6463',
                                    '2014-7665',
                                    '2014-9133',
                                    '2014-9384',
                                    '2015-1060',
                                    '2015-10973',
                                    '2015-11231',
                                    '2015-12203',
                                    '2015-12299',
                                    '2015-13497',
                                    '2015-14328',
                                    '2015-15037',
                                    '2015-15944',
                                    '2015-16038',
                                    '2015-16460',
                                    '2015-16829',
                                    '2015-17960',
                                    '2015-21506',
                                    '2015-2218',
                                    '2015-2403',
                                    '2015-37385',
                                    '2015-37391',
                                    '2015-37741',
                                    '2015-38522',
                                    '2015-38677',
                                    '2015-39083',
                                    '2015-39776',
                                    '2015-42683',
                                    '2015-42842',
                                    '2015-43300',
                                    '2015-44198',
                                    '2015-44515',
                                    '2015-4455',
                                    '2015-45690',
                                    '2015-46293',
                                    '2015-46530',
                                    '2015-46952',
                                    '2015-47192',
                                    '2015-4802',
                                    '2015-48098',
                                    '2015-51472',
                                    '2015-52086',
                                    '2015-52954',
                                    '2015-53326',
                                    '2015-5359',
                                    '2015-54020',
                                    '2015-54148',
                                    '2015-7656',
                                    '2015-882',
                                    '2015-8949',
                                    '2015-9128',
                                    '2015-9590',
                                    '2016-1145',
                                    '2016-1174',
                                    '2016-1371',
                                    '2016-15300',
                                    '2016-15308',
                                    '2016-15397',
                                    '2016-15623',
                                    '2016-1632',
                                    '2016-16455',
                                    '2016-17490',
                                    '2016-19270',
                                    '2016-19946',
                                    '2016-2015',
                                    '2016-2129',
                                    '2016-21920',
                                    '2016-22418',
                                    '2016-22680',
                                    '2016-23011',
                                    '2016-24854',
                                    '2016-25107',
                                    '2016-25227',
                                    '2016-25333',
                                    '2016-26715',
                                    '2016-27241',
                                    '2016-27583',
                                    '2016-27892',
                                    '2016-30978',
                                    '2016-31608',
                                    '2016-33578',
                                    '2016-34374',
                                    '2016-3488',
                                    '2016-35905',
                                    '2016-36036',
                                    '2016-36650',
                                    '2016-37308',
                                    '2016-37410',
                                    '2016-37566',
                                    '2016-37915',
                                    '2016-37962',
                                    '2016-38626',
                                    '2016-39103',
                                    '2016-39913',
                                    '2016-4222',
                                    '2016-5196',
                                    '2016-6302',
                                    '2016-6356',
                                    '2016-6435',
                                    '2016-6705',
                                    '2016-6912',
                                    '2016-8203',
                                    '2016-9023',
                                    '2017-10868',
                                    '2017-11018',
                                    '2017-11146',
                                    '2017-11394',
                                    '2017-11619',
                                    '2017-12499',
                                    '2017-1273',
                                    '2017-14777',
                                    '2017-14964',
                                    '2017-15482',
                                    '2017-19800',
                                    '2017-20310',
                                    '2017-20814',
                                    '2017-21620',
                                    '2017-21961',
                                    '2017-22870',
                                    '2017-22987',
                                    '2017-2320',
                                    '2017-24256',
                                    '2017-25448',
                                    '2017-26619',
                                    '2017-27009',
                                    '2017-27075',
                                    '2017-27272',
                                    '2017-27557',
                                    '2017-27594',
                                    '2017-28117',
                                    '2017-29556',
                                    '2017-30583',
                                    '2017-30676',
                                    '2017-3089',
                                    '2017-34881',
                                    '2017-3504',
                                    '2017-35531',
                                    '2017-40601',
                                    '2017-40982',
                                    '2017-41942',
                                    '2017-41943',
                                    '2017-6757',
                                    '2017-797',
                                    '2017-8494',
                                    '2017-8576');
