CREATE OR REPLACE VIEW WH_ASSETS.CINDY_2018_CRASH_TEST
BEQUEATH DEFINER
AS 
SELECT  B.MDOTID,
        B.UNIT_KEY,
        AP.PERSON_KEY,
        1 AS AGG
FROM ACCIDENT_PEOPLE AP
     RIGHT OUTER JOIN (SELECT A.MDOTID AS MDOTID, UNIT_KEY, A.ACCIDENT_YEAR FROM ACCIDENTS A JOIN ACCIDENT_UNITS U ON A.MDOTID = U.MDOTID) B ON B.MDOTID = AP.MDOTID 
     WHERE B.ACCIDENT_YEAR >= 2017;
