CREATE OR REPLACE VIEW WH_ASSETS.CROSS_SECTIONS
BEQUEATH DEFINER
AS 
SELECT BEGIN_OFFSET,
           ELEMENT_ID,
           ELEMENT_WID,
           END_OFFSET,
           LEFT_LANE_CROSSSECTION,
           LEFT_SHOULDER_TYPE,
           LEFT_SHOULDER_TYPE_DESCR,
           LEFT_SHOULDER_WIDTH,
           LEFT_SIDEWALK_TYPE,
           LEFT_SIDEWALK_TYPE_DESCR,
           LEFT_SIDEWALK_WIDTH,
           RIGHT_LANE_CROSSSECTION,
           RIGHT_SHOULDER_TYPE,
           RIGHT_SHOULDER_TYPE_DESCR,
           RIGHT_SHOULDER_WIDTH,
           RIGHT_SIDEWALK_TYPE,
           RIGHT_SIDEWALK_TYPE_DESCR,
           RIGHT_SIDEWALK_WIDTH,
           ROUTE_NUMBER,
           SECTION_ID
      FROM CROSS_SECTION_HISTORY
     WHERE END_DATE IS NULL;
