CREATE OR REPLACE FUNCTION F_NEXT_INV_NUMBER RETURN VARCHAR2 IS
NEXT_INV_NUMBER VARCHAR2(30);

BEGIN
   
  /* Formatted on 5/7/2021 3:10:02 PM (QP5 v5.354) */
SELECT NE_UNIQUE + 1
  INTO NEXT_INV_NUMBER
  FROM (  SELECT NE_UNIQUE
            FROM NM_ELEMENTS_ALL@METRANS
           WHERE NE_GTY_GROUP_TYPE = 'RINV'
        ORDER BY NE_DATE_CREATED DESC NULLS LAST)
  WHERE ROWNUM = 1;
  RETURN NEXT_INV_NUMBER;
  
  EXCEPTION
	WHEN OTHERS THEN
		RETURN null;

END F_NEXT_INV_NUMBER;
/
