CREATE OR REPLACE PROCEDURE load_crashes_on_route
IS
    /**********************************************************************
    This procedure loads the CRASHES_ON_ROUTE table which is a full outer join of the highway network with the crashes.
    It replaces the materialized view mv_crashes_on_route

    It truncates the table and re-loads it.

    04-12-2019 SH  Initial Version
    11-06-2019 SH  Add new columns from accidents and SNAPSHOT_YEAR,
                   MDOT_REVIEW_DATE, MDOT_LAST_MODIFIED, MDOT_REVIEWER_ID, MDOT_REVIEW_COMMENT requested by Shawn Hembree
                   CRASHREPORTID - requested by Tom Marcotte
                   BICYCLE_YN ,PEDESTRIAN_YN,NO_OF_UNITS , NO_OF_PERSONS   - added for mapviewer - Requested by Shawn Macdonald
    12-22-2019  SH Moved new version to production
    04-05-2020 SH Lookup snapshot year from complete_transportation_network instead of hardcode it
    07-20-2020 SH Add sidewalks  LEFT_SIDEWALK_TYPE, LEFT_SIDEWALK_TYPE_DESCR, LEFT_SIDEWALK_WIDTH, RIGHT_SIDEWALK_TYPE,
                  RIGHT_SIDEWALK_TYPE_DESCR, RIGHT_SIDEWALK_WIDTH
    04-05-2021 SH Add secondary_crash column 
    06-16-2021 SH Add columns FED_AID, LAST_TREATMENT_PSN
    09-01-2022 SH Add column FARS_YN to indicate if the crash is considered a fars fatility JIRA task dotdw-640    
    09-14-2022 SH Add MOTORCYCLE_YN Unit types 11 (Motorcycle), 12  (Moped) Jira Task: DOTDW-640  
    02-27-2204 DG  Add columns BASE_AS_BUILT_HMA, BASE_GRAN_THICK, BASE_GRAN_TYPE, BASE_GRAN_TYPE_DESCR, BASE_MISC_THICK, BASE_MISC_TYPE, BASE_MISC_TYPE_DESCR, 
                               BASE_MOD_TYPE, BASE_MOD_TYPE_DESCR, BASE_MOD_YR, BASE_PRI_ID_TYPE, BASE_PRI_ID_TYPE_DESCR, BASE_PRIMARY_ID, BASE_PRIMARY_WIN,                
                               BASE_SEC_ID_TYPE, BASE_SEC_ID_TYPE_DESCR, BASE_SECOND_ID, BASE_SUB_THICK, 
                               EXCEPTIONS_DESC_XXX, FACTORED_AADT_CALC_COMMENT, 
                               HPMT_COMB_AADT_PCNT, HPMT_COMB_DHV_PCNT, HPMT_DHV_PCNT, HPMT_DIR_DIST, HPMT_PASS_AADT_PCNTc, HPMT_PASS_DHV_PCNT, HPMT_SU_AADT_PCNT, HPMT_SU_DHV_PCNT
                               NHFN_CONNECTOR_ID, NHFN_SUBSYSTEM, NHFN_SUBSYSTEM_DESCR, SLD_FILE_DATE, SLD_FILE_NAME  
    **********************************************************************/



    commit_count   NUMBER (7) := 0;
    cntr           NUMBER (7) := 0;
    snap_year      NUMBER;

    g_start_time   DATE := SYSDATE;
    g_owner        VARCHAR2 (20) := 'WH_ASSETS';
    g_jobname      VARCHAR2 (30) := 'LOAD_CRASHES_ON_ROUTE';
    g_object       VARCHAR2 (20) := 'CRASHES_ON_ROUTE';
    g_sqlmsg       VARCHAR2 (500) := NULL;



    CURSOR acc
    IS
        SELECT A.ACCIDENT_DATE,
               A.ACCIDENT_DAY_OF_WEEK,
               A.ACCIDENT_DAY_OF_WEEK_NUM,
               A.ACCIDENT_HOUR,
               A.ACCIDENT_MONTH_NAME,
               A.ACCIDENT_MONTH_NUM,
               A.ACCIDENT_TIME,
               A.ACCIDENT_YEAR,
               A.BICYCLE_YN,
               A.CONTRIB_CIRC_ENV1,
               A.CONTRIB_CIRC_ENV1_DESCR,
               A.CONTRIB_CIRC_ENV2,
               A.CONTRIB_CIRC_ENV2_DESCR,
               A.CONTRIB_CIRC_ROAD1,
               A.CONTRIB_CIRC_ROAD1_DESCR,
               A.CONTRIB_CIRC_ROAD2,
               A.CONTRIB_CIRC_ROAD2_DESCR,
               A.COUNTY_CODE,
               A.COUNTY_NAME,
               A.CRASH_COST,
               A.CRASH_NODE_ID,
               CASE
                   WHEN A.MDOTID IS NOT NULL THEN A.ELEMENT_ID
                   ELSE H.ELEMENT_ID
               END
                   ELEMENT_ID,
               A.CRASHREPORTID,
               A.FARS_YN,
               A.FEDERAL_URBAN_GROUP,
               A.FEDERAL_URBAN_GROUP_DESCR,
               CASE
                   WHEN A.MDOTID IS NOT NULL THEN A.ELEMENT_WID
                   ELSE H.ELEMENT_WID
               END
                   ELEMENT_WID,
               A.INJURY_COUNT,
               A.INJURY_LEVEL,
               A.INJURY_LEVEL_CODE,
               A.LATITUDE,
               A.LIGHT_CONDITION,
               A.LIGHT_CONDITION_DESCR,
               A.LOCATION_TYPE,
               A.LOC_FIRST_HARMFUL_EVENT,
               A.LOC_FIRST_HARMFUL_EVENT_DESCR,
               A.LONGITUDE,
               A.MDOTID,
               A.MDOT_LAST_MODIFIED,
               A.MDOT_REVIEW_COMMENT,
               A.MDOT_REVIEW_DATE,
               A.MDOT_REVIEWER_ID,
               A.MOTORCYCLE_YN,
               CASE
                   WHEN A.MDOTID IS NOT NULL THEN A.NODE_ID
                   ELSE H.NODE_ID1
               END
                   NODE_ID,
               A.NO_OF_A_INJ,
               A.NO_OF_B_INJ,
               A.NO_OF_C_INJ,
               A.NO_OF_K_INJ,
               A.NO_OF_NON_INJ,
               A.NO_OF_PERSONS,
               A.NO_OF_UNITS,
               A.OFFSET,
               A.PEDESTRIAN_YN,
               CASE
                   WHEN A.MDOTID IS NOT NULL THEN A.PRIMARY_ROUTE_MP
                   ELSE H.PRIMARY_ROUTE_MP
               END
                   PRIMARY_ROUTE_MP,
               A.PRIMARY_ROUTE_NAME,
               CASE
                   WHEN A.MDOTID IS NOT NULL THEN A.PRIMARY_ROUTE_NUMBER
                   ELSE H.PRIMARY_ROUTE_NUMBER
               END
                   PRIMARY_ROUTE_NUMBER,
               A.REGION_CODE,
               A.REGION_NAME,
               A.REPORTING_AGENCY,
               A.REPORTING_AGENCY_DESCR,
               A.REPORT_NUMBER,
               A.ROAD_GRADE,
               A.ROAD_GRADE_DESCR,
               A.ROAD_SURF_COND,
               A.ROAD_SURF_COND_DESCR,
               A.SCHOOL_BUS_RELATED,
               A.SCHOOL_BUS_RELATED_DESCR,
               A.SECONDARY_CRASH_YN,
               H.SECTION_ID,
               A.SPEED_LIMIT,
               CASE
                   WHEN A.MDOTID IS NOT NULL THEN A.TOWN_CODE
                   ELSE H.TOWN_CODE1
               END
                   TOWN_CODE,
               CASE
                   WHEN A.MDOTID IS NOT NULL THEN A.TOWN_NAME
                   ELSE H.TOWN_NAME1
               END
                   TOWN_NAME,
               A.TRAFFIC_CONTROL_DEVICE,
               A.TRAFFIC_CONTROL_DEVICE_DESCR,
               A.TRF_CNTRL_DEV_OPRATIONL,
               A.TRF_CNTRL_DEV_OPRATIONL_DESCR,
               A.TYPE_OF_CRASH,
               A.TYPE_OF_CRASH_DESCR,
               A.TYPE_OF_LOCATION,
               A.TYPE_OF_LOCATION_DESCR,
               A.WEATHER_CONDITION,
               A.WEATHER_CONDITION_DESCR,
               A.WORKZONE_IN_OR_NEAR,
               A.WORKZONE_IN_OR_NEAR_DESCR,
               A.WORKZONE_LOCATION,
               A.WORKZONE_LOCATION_DESCR,
               A.WORKZONE_POLICE_PRESENT,
               A.WORKZONE_POLICE_PRESENT_DESCR,
               A.WORKZONE_TYPE,
               A.WORKZONE_TYPE_DESCR,
               A.WORKZONE_WORKERS_PRESENT,
               A.WORKZONE_WORKERS_PRESENT_DESCR,
               ROW_TYPE,
               H.AADT,
               H.AADT_TYPE,
               H.AADT_TYPE_DESCR,
               H.AADT_YEAR,
               H.ABN,
               H.ABN_DESCR,
               H.ACCESS_CONTROL,
               H.ACCESS_CONTROL_DESCR,
               H.AGENCY,
               H.AGENCY_DESCR,
               H.BASE_AS_BUILT_HMA,        
               H.BASE_GRAN_THICK,
               H.BASE_GRAN_TYPE,
               H.BASE_GRAN_TYPE_DESCR,
               H.BASE_MISC_THICK,                 
               H.BASE_MISC_TYPE,                  
               H.BASE_MISC_TYPE_DESCR,            
               H.BASE_MOD_TYPE,                   
               H.BASE_MOD_TYPE_DESCR,             
               H.BASE_MOD_YR,                     
               H.BASE_PRI_ID_TYPE,                
               H.BASE_PRI_ID_TYPE_DESCR,          
               H.BASE_PRIMARY_ID,                 
               H.BASE_PRIMARY_WIN,                
               H.BASE_SEC_ID_TYPE,                
               H.BASE_SEC_ID_TYPE_DESCR,          
               H.BASE_SECOND_ID,                  
               H.BASE_SUB_THICK,  
               H.BEGIN_ELEMENT_MILEPOINT,
               H.BEGIN_SECTION_MP,
               H.BEGIN_NODE_DESCRIPTION,
               H.BEGIN_NODE_ID,
               H.BEGIN_SECTION_OFFSET,
               H.BRIDGE_POSTING_CSL,
               H.BRIDGE_RELIABILITY_CSL,
               H.CAPACITY,
               H.CENTER_TURN_LANE_COUNT,
               H.CENTER_TURN_LANE_WIDTH,
               H.CONDITION_CSL,
               H.CONGESTION_CSL,
               H.CONGESTION_RATE_CSL,
               H.CRASH_HISTORY_CSL,
               H.CRASH_HISTORY_RATE_CSL,
               H.CSL_YEAR,
               H.CUMULATIVE_MILEPOINT_ORDER,
               H.DIRECTION,
               H.DIRECTIONAL_SUFFIX,
               H.ELEMENT_LENGTH,
               H.END_ELEMENT_MILEPOINT,
               H.END_SECTION_MP,
               H.END_NODE_DESCRIPTION,
               H.END_NODE_ID,
               H.END_SECTION_OFFSET,
               H.EXCEPTIONS_DESC_XXX,
               H.EXISTING,
               H.FACTORED_AADT,
               H.FACTORED_AADT_CALC_COMMENT,
               H.FACTOR_GROUP,
               H.FACTOR_YEAR,
               H.FED_AID,
               H.FEDERAL_FUNCTIONAL_CLASS,
               H.FEDERAL_FUNCTIONAL_CLASS_DESCR,
               H.FEDERAL_URBAN_RURAL,
               H.FEDERAL_URBAN_RURAL_DESCR,
               H.FUTURE_ADT,
               H.FUTURE_ADT_YEAR,
               H.HASS_DESCRIPTION,
               H.HASS_ID,
               H.HPMS_SECTION_ID,
               H.HPMT_COMB_AADT_PCNT,
               H.HPMT_COMB_DHV_PCNT,
               H.HPMT_DHV_PCNT,
               H.HPMT_DIR_DIST,
               H.HPMT_PASS_AADT_PCNT,
               H.HPMT_PASS_DHV_PCNT,
               H.HPMT_SU_AADT_PCNT,
               H.HPMT_SU_DHV_PCNT,
               H.HUNDRED_MILLION_VEHICLE_MILES,
               H.IRI,
               H.JURISDICTION,
               H.JURISDICTION_ABBREVIATION,
               H.JURISDICTION_CODE,
               H.LANE_COUNT,
               H.LANE_SURFACE_TYPE,
               H.LANE_SURFACE_TYPE_DESCR,
               H.LAST_TREATMENT_PSN,
               H.LEFT_LANE_CROSSSECTION,
               H.LEFT_RUT,
               H.LEFT_SHOULDER_TYPE,
               H.LEFT_SHOULDER_TYPE_DESCR,
               H.LEFT_SHOULDER_WIDTH,
               H.LEFT_SIDEWALK_TYPE,
               H.LEFT_SIDEWALK_TYPE_DESCR,
               H.LEFT_SIDEWALK_WIDTH,
               H.LEFT_TURN_LANE_COUNT,
               H.LEFT_TURN_LANE_WIDTH,
               H.MAINT_RESP_WINTER,
               H.MAINT_RESP_WINTER_DESCR,
               H.MAINT_RESP_YEARROUND,
               H.MAINT_RESP_YEAR_DESCR,
               H.MEAN_SUM_DEFLECTION_CSL,
               H.MEDIAN_AVERAGE_WIDTH,
               H.MEDIAN_TYPE,
               H.MEDIAN_TYPE_DESCR,
               H.MEV,
               H.MIN_PAVEMENT_WIDTH_CSL,
               H.MIN_STRUCT_BRIDGE_COND_CSL,
               H.MPO,
               H.NATIONAL_TRUCK_NETWORK,
               H.NATIONAL_TRUCK_NETWORK_DESCR,
               H.NHFN_CONNECTOR_ID,
               H.NHFN_SUBSYSTEM,
               H.NHFN_SUBSYSTEM_DESCR,
               H.NHS_STATUS,
               H.NHS_TYPE,
               H.NHS_TYPE_DESCR,
               H.NODE_DESCRIPTION,
               H.NO_OF_LEGS,
               H.NUMBER_OF_LANES,
               H.OFFICIAL_MILES,
               H.ONE_WAY,
               H.ONE_WAY_DESCR,
               H.OWNER,
               H.OWNER_DESCR,
               H.PAVEMENT_CONDITION_CSL,
               H.PAVEMENT_RUTTING_CSL,
               H.PAVEMENT_WIDTH_CSL,
               H.PCR,
               H.PLOW_CREW,
               H.PMS_FILE_NAME,
               H.PMS_INVENTORY_YEAR,
               H.PRIMARY,
               H.PRIORITY,
               H.RAMP,
               H.RAMP_DESCR,
               H.MAINTENANCE_REGION,
               H.MAINTENANCE_REGION_DESCR,
               H.RIDE_QUALITY_CSL,
               H.RIGHT_LANE_CROSSSECTION,
               H.RIGHT_RUT,
               H.RIGHT_SHOULDER_TYPE,
               H.RIGHT_SHOULDER_TYPE_DESCR,
               H.RIGHT_SHOULDER_WIDTH,
               H.RIGHT_SIDEWALK_TYPE,
               H.RIGHT_SIDEWALK_TYPE_DESCR,
               H.RIGHT_SIDEWALK_WIDTH,
               H.RIGHT_TURN_LANE_COUNT,
               H.RIGHT_TURN_LANE_WIDTH,
               H.ROADWAY_STRENGTH_CSL,
               H.ROADWAY_TYPE,
               H.ROADWAY_TYPE_DESCR,
               H.ROAD_POSTING_CSL,
               H.ROUTE_NAME,
               H.ROUTE_NUMBER,
               H.ROUTE_GROUP,
               H.ROUTE_SYSTEM,
               H.ROUTE_TYPE,
               H.RUT_CSL,
               H.SAFETY_CSL,
               H.SCENIC_BYWAY_DESCRIPTION,
               H.SCENIC_BYWAY_DESIG_YR,
               H.SCENIC_BYWAY_NAME,
               H.SCENIC_BYWAY_TYPE,
               H.SCENIC_BYWAY_TYPE_DESCR,
               H.SECTION_LENGTH,
               H.SERVICE_CSL,
               H.SH_SA_IR_DESIGNATION,
               H.SLD_FILE_DATE, 
               H.SLD_FILE_NAME, 
               H.SORTORD,
               h.SPEED,
               h.SPEEDSRC,
               h.SPEEDZN_ID,
               H.SPUR_NUMBER,
               H.STATE_AID_NO,
               H.STATE_DESIGNATION_NUMBER,
               H.STATE_DESIG_TYPE,
               H.STATE_DESIG_TYPE_DESCR,
               H.STATE_HIGHWAY_DESIGNATION_NUMBER,
               H.STATE_URBAN_RURAL,
               H.STATE_URBAN_RURAL_DESCR,
               H.STRATEGIC_HIGHWAY_NETWORK,
               H.STRATEGIC_HIGHWAY_NETWORK_DESC,
               H.STREET_NAME,
               H.STREET_NAME_PREFIX,
               H.STREET_NAME_SUFFIX,
               H.STREETNAME,
               H.STRUCT_BRIDGE_COND_CSL,
               H.SUMMER_CREW,
               H.THRU_LANE_COUNT,
               H.THRU_LANE_WIDTH,
               H.TOTAL_PAVEMENT_WIDTH,
               H.TOWNLINE_NODE,
               H.TRAFFIC_SIGNAL,
               H.TRANSPORTATION_MODE,
               H.TRUCK_LANE_COUNT,
               H.TRUCK_LANE_WIDTH,
               H.TRUCK_PERCENT,
               H.WCSH_AGREEMENT,
               H.WCSH_CODE,
               H.WEIGHTED_IRI_CSL,
               H.WEIGHTED_PCR_CSL,
               H.WIDTH,
               H.WINTER_CREW,
               CASE
                   WHEN a.location_type = 'ELEMENT' AND H.direction = 1
                   THEN
                       ROUND (H.begin_element_milepoint + A.OFFSET, 2)
                   WHEN a.location_type = 'ELEMENT' AND H.direction = -1
                   THEN
                       ROUND (H.end_element_milepoint - A.OFFSET, 2)
                   WHEN a.location_type = 'NODE'
                   THEN
                       H.begin_element_milepoint
                   ELSE
                       NULL
               END
                   MILEPOINT                                -- CRASH MILEPOINT
          FROM V_HIGHWAY_NETWORK  h
               FULL OUTER JOIN accidents a
                   ON (a.node_id = h.node_id1 OR a.section_id = h.section_id);
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CRASHES_ON_ROUTE';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE CRASHES_ON_ROUTE_ERROR_LOG';

    MANAGE_INDEXES.Mark_Indexes_Unusable ('CRASHES_ON_ROUTE');

    SELECT MAX (snapshot_year)
      INTO snap_year
      FROM complete_transportation_network;

    FOR aa IN acc
    LOOP
        INSERT INTO crashes_on_route (AADT,
                                      AADT_TYPE,
                                      AADT_TYPE_DESCR,
                                      AADT_YEAR,
                                      ABN,
                                      ABN_DESCR,
                                      ACCESS_CONTROL,
                                      ACCESS_CONTROL_DESCR,
                                      ACCIDENT_DATE,
                                      ACCIDENT_DAY_OF_WEEK,
                                      ACCIDENT_DAY_OF_WEEK_NUM,
                                      ACCIDENT_HOUR,
                                      ACCIDENT_MONTH_NAME,
                                      ACCIDENT_MONTH_NUM,
                                      ACCIDENT_TIME,
                                      ACCIDENT_YEAR,
                                      AGENCY,
                                      AGENCY_DESCR,
                                      BASE_AS_BUILT_HMA,        
                                      BASE_GRAN_THICK,
                                      BASE_GRAN_TYPE,
                                      BASE_GRAN_TYPE_DESCR,
                                      BASE_MISC_THICK,                 
                                      BASE_MISC_TYPE,                  
                                      BASE_MISC_TYPE_DESCR,            
                                      BASE_MOD_TYPE,                   
                                      BASE_MOD_TYPE_DESCR,             
                                      BASE_MOD_YR,                     
                                      BASE_PRI_ID_TYPE,                
                                      BASE_PRI_ID_TYPE_DESCR,          
                                      BASE_PRIMARY_ID,                 
                                      BASE_PRIMARY_WIN,                
                                      BASE_SEC_ID_TYPE,                
                                      BASE_SEC_ID_TYPE_DESCR,          
                                      BASE_SECOND_ID,                  
                                      BASE_SUB_THICK,  
                                      BEGIN_ELEMENT_MILEPOINT,
                                      BEGIN_NODE_DESCRIPTION,
                                      BEGIN_NODE_ID,
                                      BEGIN_SECTION_MP,
                                      BEGIN_SECTION_OFFSET,
                                      BICYCLE_YN,
                                      BRIDGE_POSTING_CSL,
                                      BRIDGE_RELIABILITY_CSL,
                                      CAPACITY,
                                      CENTER_TURN_LANE_COUNT,
                                      CENTER_TURN_LANE_WIDTH,
                                      CONDITION_CSL,
                                      CONGESTION_CSL,
                                      CONGESTION_RATE_CSL,
                                      CONTRIB_CIRC_ENV1,
                                      CONTRIB_CIRC_ENV1_DESCR,
                                      CONTRIB_CIRC_ENV2,
                                      CONTRIB_CIRC_ENV2_DESCR,
                                      CONTRIB_CIRC_ROAD1,
                                      CONTRIB_CIRC_ROAD1_DESCR,
                                      CONTRIB_CIRC_ROAD2,
                                      CONTRIB_CIRC_ROAD2_DESCR,
                                      COUNTY_CODE,
                                      COUNTY_NAME,
                                      CRASH_COST,
                                      CRASH_HISTORY_CSL,
                                      CRASH_HISTORY_RATE_CSL,
                                      CRASH_NODE_ID,
                                      CRASHREPORTID,
                                      CSL_YEAR,
                                      CUMULATIVE_MILEPOINT_ORDER,
                                      DIRECTION,
                                      DIRECTIONAL_SUFFIX,
                                      ELEMENT_ID,
                                      ELEMENT_LENGTH,
                                      ELEMENT_WID,
                                      END_ELEMENT_MILEPOINT,
                                      END_NODE_DESCRIPTION,
                                      END_NODE_ID,
                                      END_SECTION_MP,
                                      END_SECTION_OFFSET,
                                      EXCEPTIONS_DESC_XXX,
                                      EXISTING,
                                      FACTORED_AADT,
                                      FACTORED_AADT_CALC_COMMENT,
                                      FACTOR_GROUP,
                                      FACTOR_YEAR,
                                      FARS_YN,
                                      FED_AID,
                                      FEDERAL_FUNCTIONAL_CLASS,
                                      FEDERAL_FUNCTIONAL_CLASS_DESCR,
                                      FEDERAL_URBAN_GROUP,
                                      FEDERAL_URBAN_GROUP_DESCR,
                                      FEDERAL_URBAN_RURAL,
                                      FEDERAL_URBAN_RURAL_DESCR,
                                      FUTURE_ADT,
                                      FUTURE_ADT_YEAR,
                                      HASS_DESCRIPTION,
                                      HASS_ID,
                                      HIGHWAY_ID,
                                      HPMS_SECTION_ID,
                                      HPMT_COMB_AADT_PCNT,
                                      HPMT_COMB_DHV_PCNT,
                                      HPMT_DHV_PCNT,
                                      HPMT_DIR_DIST,
                                      HPMT_PASS_AADT_PCNT,
                                      HPMT_PASS_DHV_PCNT,
                                      HPMT_SU_AADT_PCNT,
                                      HPMT_SU_DHV_PCNT,
                                      HUNDRED_MILLION_VEHICLE_MILES,
                                      INJURY_COUNT,
                                      INJURY_LEVEL,
                                      INJURY_LEVEL_CODE,
                                      IRI,
                                      JURISDICTION,
                                      JURISDICTION_ABBREVIATION,
                                      JURISDICTION_CODE,
                                      LANE_COUNT,
                                      LANE_SURFACE_TYPE,
                                      LANE_SURFACE_TYPE_DESCR,
                                      LAST_TREATMENT_PSN,
                                      LATITUDE,
                                      LEFT_LANE_CROSSSECTION,
                                      LEFT_RUT,
                                      LEFT_SHOULDER_TYPE,
                                      LEFT_SHOULDER_TYPE_DESCR,
                                      LEFT_SHOULDER_WIDTH,
                                      LEFT_SIDEWALK_TYPE,
                                      LEFT_SIDEWALK_TYPE_DESCR,
                                      LEFT_SIDEWALK_WIDTH,
                                      LEFT_TURN_LANE_COUNT,
                                      LEFT_TURN_LANE_WIDTH,
                                      LIGHT_CONDITION,
                                      LIGHT_CONDITION_DESCR,
                                      LOCATION_TYPE,
                                      LOC_FIRST_HARMFUL_EVENT,
                                      LOC_FIRST_HARMFUL_EVENT_DESCR,
                                      LONGITUDE,
                                      MAINTENANCE_REGION,
                                      MAINTENANCE_REGION_DESCR,
                                      MAINT_RESP_WINTER,
                                      MAINT_RESP_WINTER_DESCR,
                                      MAINT_RESP_YEARROUND,
                                      MAINT_RESP_YEAR_DESCR,
                                      MDOT_LAST_MODIFIED,
                                      MDOT_REVIEW_COMMENT,
                                      MDOT_REVIEW_DATE,
                                      MDOT_REVIEWER_ID,
                                      MDOTID,
                                      MEAN_SUM_DEFLECTION_CSL,
                                      MEDIAN_AVERAGE_WIDTH,
                                      MEDIAN_TYPE,
                                      MEDIAN_TYPE_DESCR,
                                      MEV,
                                      MILEPOINT,
                                      MIN_PAVEMENT_WIDTH_CSL,
                                      MIN_STRUCT_BRIDGE_COND_CSL,
                                      MOTORCYCLE_YN,
                                      MPO,
                                      NATIONAL_TRUCK_NETWORK,
                                      NATIONAL_TRUCK_NETWORK_DESCR,
                                      NHFN_CONNECTOR_ID,
                                      NHFN_SUBSYSTEM,
                                      NHFN_SUBSYSTEM_DESCR,
                                      NHS_STATUS,
                                      NHS_TYPE,
                                      NHS_TYPE_DESCR,
                                      NODE_DESCRIPTION,
                                      NODE_ID,
                                      NO_OF_A_INJ,
                                      NO_OF_B_INJ,
                                      NO_OF_C_INJ,
                                      NO_OF_K_INJ,
                                      NO_OF_LEGS,
                                      NO_OF_NON_INJ,
                                      NO_OF_PERSONS,
                                      NO_OF_UNITS,
                                      NUMBER_OF_LANES,
                                      OFFICIAL_MILES,
                                      OFFSET,
                                      ONE_WAY,
                                      ONE_WAY_DESCR,
                                      OWNER,
                                      OWNER_DESCR,
                                      PAVEMENT_CONDITION_CSL,
                                      PAVEMENT_RUTTING_CSL,
                                      PAVEMENT_WIDTH_CSL,
                                      PCR,
                                      PEDESTRIAN_YN,
                                      PLOW_CREW,
                                      PMS_FILE_NAME,
                                      PMS_INVENTORY_YEAR,
                                      PRIMARY,
                                      PRIMARY_ROUTE_MP,
                                      PRIMARY_ROUTE_NAME,
                                      PRIMARY_ROUTE_NUMBER,
                                      PRIORITY,
                                      RAMP,
                                      RAMP_DESCR,
                                      REGION_CODE,
                                      REGION_NAME,
                                      REPORTING_AGENCY,
                                      REPORTING_AGENCY_DESCR,
                                      REPORT_NUMBER,
                                      RIDE_QUALITY_CSL,
                                      RIGHT_LANE_CROSSSECTION,
                                      RIGHT_RUT,
                                      RIGHT_SHOULDER_TYPE,
                                      RIGHT_SHOULDER_TYPE_DESCR,
                                      RIGHT_SHOULDER_WIDTH,
                                      RIGHT_SIDEWALK_TYPE,
                                      RIGHT_SIDEWALK_TYPE_DESCR,
                                      RIGHT_SIDEWALK_WIDTH,
                                      RIGHT_TURN_LANE_COUNT,
                                      RIGHT_TURN_LANE_WIDTH,
                                      ROADWAY_STRENGTH_CSL,
                                      ROADWAY_TYPE,
                                      ROADWAY_TYPE_DESCR,
                                      ROAD_GRADE,
                                      ROAD_GRADE_DESCR,
                                      ROAD_POSTING_CSL,
                                      ROAD_SURF_COND,
                                      ROAD_SURF_COND_DESCR,
                                      ROUTE_GROUP,
                                      ROUTE_NAME,
                                      ROUTE_NUMBER,
                                      ROUTE_SYSTEM,
                                      ROUTE_TYPE,
                                      ROW_TYPE,
                                      RUT_CSL,
                                      SAFETY_CSL,
                                      SCENIC_BYWAY_DESCRIPTION,
                                      SCENIC_BYWAY_DESIG_YR,
                                      SCENIC_BYWAY_NAME,
                                      SCENIC_BYWAY_TYPE,
                                      SCENIC_BYWAY_TYPE_DESCR,
                                      SCHOOL_BUS_RELATED,
                                      SCHOOL_BUS_RELATED_DESCR,
                                      SECONDARY_CRASH_YN,
                                      SECTION_ID,
                                      SECTION_LENGTH,
                                      SERVICE_CSL,
                                      SH_SA_IR_DESIGNATION,
                                      SLD_FILE_DATE, 
                                      SLD_FILE_NAME, 
                                      SNAPSHOT_YEAR,
                                      SORTORD,
                                      SPEED,
                                      SPEEDSRC,
                                      SPEEDZN_ID,
                                      SPEED_LIMIT,
                                      SPUR_NUMBER,
                                      STATE_AID_NO,
                                      STATE_DESIGNATION_NUMBER,
                                      STATE_DESIG_TYPE,
                                      STATE_DESIG_TYPE_DESCR,
                                      STATE_HIGHWAY_DESIGNATION_NUMBER,
                                      STATE_URBAN_RURAL,
                                      STATE_URBAN_RURAL_DESCR,
                                      STRATEGIC_HIGHWAY_NETWORK,
                                      STRATEGIC_HIGHWAY_NETWORK_DESC,
                                      STREETNAME,
                                      STREET_NAME,
                                      STREET_NAME_PREFIX,
                                      STREET_NAME_SUFFIX,
                                      STRUCT_BRIDGE_COND_CSL,
                                      SUMMER_CREW,
                                      THRU_LANE_COUNT,
                                      THRU_LANE_WIDTH,
                                      TOTAL_PAVEMENT_WIDTH,
                                      TOWNLINE_NODE,
                                      TOWN_CODE,
                                      TOWN_NAME,
                                      TRAFFIC_CONTROL_DEVICE,
                                      TRAFFIC_CONTROL_DEVICE_DESCR,
                                      TRAFFIC_SIGNAL,
                                      TRANSPORTATION_MODE,
                                      TRF_CNTRL_DEV_OPRATIONL,
                                      TRF_CNTRL_DEV_OPRATIONL_DESCR,
                                      TRUCK_LANE_COUNT,
                                      TRUCK_LANE_WIDTH,
                                      TRUCK_PERCENT,
                                      TYPE_OF_CRASH,
                                      TYPE_OF_CRASH_DESCR,
                                      TYPE_OF_LOCATION,
                                      TYPE_OF_LOCATION_DESCR,
                                      WCSH_AGREEMENT,
                                      WCSH_CODE,
                                      WEATHER_CONDITION,
                                      WEATHER_CONDITION_DESCR,
                                      WEIGHTED_IRI_CSL,
                                      WEIGHTED_PCR_CSL,
                                      WIDTH,
                                      WINTER_CREW,
                                      WORKZONE_IN_OR_NEAR,
                                      WORKZONE_IN_OR_NEAR_DESCR,
                                      WORKZONE_LOCATION,
                                      WORKZONE_LOCATION_DESCR,
                                      WORKZONE_POLICE_PRESENT,
                                      WORKZONE_POLICE_PRESENT_DESCR,
                                      WORKZONE_TYPE,
                                      WORKZONE_TYPE_DESCR,
                                      WORKZONE_WORKERS_PRESENT,
                                      WORKZONE_WORKERS_PRESENT_DESCR)
             VALUES (aa.AADT,
                     aa.AADT_TYPE,
                     aa.AADT_TYPE_DESCR,
                     aa.AADT_YEAR,
                     aa.ABN,
                     aa.ABN_DESCR,
                     aa.ACCESS_CONTROL,
                     aa.ACCESS_CONTROL_DESCR,
                     aa.ACCIDENT_DATE,
                     aa.ACCIDENT_DAY_OF_WEEK,
                     aa.ACCIDENT_DAY_OF_WEEK_NUM,
                     aa.ACCIDENT_HOUR,
                     aa.ACCIDENT_MONTH_NAME,
                     aa.ACCIDENT_MONTH_NUM,
                     aa.ACCIDENT_TIME,
                     aa.ACCIDENT_YEAR,
                     aa.AGENCY,
                     aa.AGENCY_DESCR,
                     aa.BASE_AS_BUILT_HMA,        
                     aa.BASE_GRAN_THICK,
                     aa.BASE_GRAN_TYPE,
                     aa.BASE_GRAN_TYPE_DESCR,
                     aa.BASE_MISC_THICK,                 
                     aa.BASE_MISC_TYPE,                  
                     aa.BASE_MISC_TYPE_DESCR,            
                     aa.BASE_MOD_TYPE,                   
                     aa.BASE_MOD_TYPE_DESCR,             
                     aa.BASE_MOD_YR,                     
                     aa.BASE_PRI_ID_TYPE,                
                     aa.BASE_PRI_ID_TYPE_DESCR,          
                     aa.BASE_PRIMARY_ID,                 
                     aa.BASE_PRIMARY_WIN,                
                     aa.BASE_SEC_ID_TYPE,                
                     aa.BASE_SEC_ID_TYPE_DESCR,          
                     aa.BASE_SECOND_ID,                  
                     aa.BASE_SUB_THICK,  
                     aa.BEGIN_ELEMENT_MILEPOINT,
                     aa.BEGIN_NODE_DESCRIPTION,
                     aa.BEGIN_NODE_ID,
                     aa.BEGIN_SECTION_MP,
                     aa.BEGIN_SECTION_OFFSET,
                     aa.BICYCLE_YN,
                     aa.BRIDGE_POSTING_CSL,
                     aa.BRIDGE_RELIABILITY_CSL,
                     aa.CAPACITY,
                     aa.CENTER_TURN_LANE_COUNT,
                     aa.CENTER_TURN_LANE_WIDTH,
                     aa.CONDITION_CSL,
                     aa.CONGESTION_CSL,
                     aa.CONGESTION_RATE_CSL,
                     aa.CONTRIB_CIRC_ENV1,
                     aa.CONTRIB_CIRC_ENV1_DESCR,
                     aa.CONTRIB_CIRC_ENV2,
                     aa.CONTRIB_CIRC_ENV2_DESCR,
                     aa.CONTRIB_CIRC_ROAD1,
                     aa.CONTRIB_CIRC_ROAD1_DESCR,
                     aa.CONTRIB_CIRC_ROAD2,
                     aa.CONTRIB_CIRC_ROAD2_DESCR,
                     aa.COUNTY_CODE,
                     aa.COUNTY_NAME,
                     aa.CRASH_COST,
                     aa.CRASH_HISTORY_CSL,
                     aa.CRASH_HISTORY_RATE_CSL,
                     aa.CRASH_NODE_ID,
                     aa.CRASHREPORTID,
                     aa.CSL_YEAR,
                     aa.CUMULATIVE_MILEPOINT_ORDER,
                     aa.DIRECTION,
                     aa.DIRECTIONAL_SUFFIX,
                     aa.ELEMENT_ID,
                     aa.ELEMENT_LENGTH,
                     aa.ELEMENT_WID,
                     aa.END_ELEMENT_MILEPOINT,
                     aa.END_NODE_DESCRIPTION,
                     aa.END_NODE_ID,
                     aa.END_SECTION_MP,
                     aa.END_SECTION_OFFSET,
                     aa.EXCEPTIONS_DESC_XXX,
                     aa.EXISTING,
                     aa.FACTORED_AADT,
                     aa.FACTORED_AADT_CALC_COMMENT,
                     aa.FACTOR_GROUP,
                     aa.FACTOR_YEAR,
                     aa.FARS_YN,
                     aa.FED_AID,
                     aa.FEDERAL_FUNCTIONAL_CLASS,
                     aa.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                     aa.FEDERAL_URBAN_GROUP,
                     aa.FEDERAL_URBAN_GROUP_DESCR,
                     aa.FEDERAL_URBAN_RURAL,
                     aa.FEDERAL_URBAN_RURAL_DESCR,
                     aa.FUTURE_ADT,
                     aa.FUTURE_ADT_YEAR,
                     aa.HASS_DESCRIPTION,
                     aa.HASS_ID,
                     aa.ELEMENT_WID,
                     aa.HPMS_SECTION_ID,
                     aa.HPMT_COMB_AADT_PCNT,
                     aa.HPMT_COMB_DHV_PCNT,
                     aa.HPMT_DHV_PCNT,
                     aa.HPMT_DIR_DIST,
                     aa.HPMT_PASS_AADT_PCNT,
                     aa.HPMT_PASS_DHV_PCNT,
                     aa.HPMT_SU_AADT_PCNT,
                     aa.HPMT_SU_DHV_PCNT,
                     aa.HUNDRED_MILLION_VEHICLE_MILES,
                     aa.INJURY_COUNT,
                     aa.INJURY_LEVEL,
                     aa.INJURY_LEVEL_CODE,
                     aa.IRI,
                     aa.JURISDICTION,
                     aa.JURISDICTION_ABBREVIATION,
                     aa.JURISDICTION_CODE,
                     aa.LANE_COUNT,
                     aa.LANE_SURFACE_TYPE,
                     aa.LANE_SURFACE_TYPE_DESCR,
                     aa.LAST_TREATMENT_PSN,
                     aa.LATITUDE,
                     aa.LEFT_LANE_CROSSSECTION,
                     aa.LEFT_RUT,
                     aa.LEFT_SHOULDER_TYPE,
                     aa.LEFT_SHOULDER_TYPE_DESCR,
                     aa.LEFT_SHOULDER_WIDTH,
                     aa.LEFT_SIDEWALK_TYPE,
                     aa.LEFT_SIDEWALK_TYPE_DESCR,
                     aa.LEFT_SIDEWALK_WIDTH,
                     aa.LEFT_TURN_LANE_COUNT,
                     aa.LEFT_TURN_LANE_WIDTH,
                     aa.LIGHT_CONDITION,
                     aa.LIGHT_CONDITION_DESCR,
                     aa.LOCATION_TYPE,
                     aa.LOC_FIRST_HARMFUL_EVENT,
                     aa.LOC_FIRST_HARMFUL_EVENT_DESCR,
                     aa.LONGITUDE,
                     aa.MAINTENANCE_REGION,
                     aa.MAINTENANCE_REGION_DESCR,
                     aa.MAINT_RESP_WINTER,
                     aa.MAINT_RESP_WINTER_DESCR,
                     aa.MAINT_RESP_YEARROUND,
                     aa.MAINT_RESP_YEAR_DESCR,
                     aa.MDOT_LAST_MODIFIED,
                     aa.MDOT_REVIEW_COMMENT,
                     aa.MDOT_REVIEW_DATE,
                     aa.MDOT_REVIEWER_ID,
                     aa.MDOTID,
                     aa.MEAN_SUM_DEFLECTION_CSL,
                     aa.MEDIAN_AVERAGE_WIDTH,
                     aa.MEDIAN_TYPE,
                     aa.MEDIAN_TYPE_DESCR,
                     aa.MEV,
                     aa.MILEPOINT,
                     aa.MIN_PAVEMENT_WIDTH_CSL,
                     aa.MIN_STRUCT_BRIDGE_COND_CSL,
                     aa.MOTORCYCLE_YN,
                     aa.MPO,
                     aa.NATIONAL_TRUCK_NETWORK,
                     aa.NATIONAL_TRUCK_NETWORK_DESCR,
                     aa.NHFN_CONNECTOR_ID,
                     aa.NHFN_SUBSYSTEM,
                     aa.NHFN_SUBSYSTEM_DESCR,
                     aa.NHS_STATUS,
                     aa.NHS_TYPE,
                     aa.NHS_TYPE_DESCR,
                     aa.NODE_DESCRIPTION,
                     aa.NODE_ID,
                     aa.NO_OF_A_INJ,
                     aa.NO_OF_B_INJ,
                     aa.NO_OF_C_INJ,
                     aa.NO_OF_K_INJ,
                     aa.NO_OF_LEGS,
                     aa.NO_OF_NON_INJ,
                     aa.NO_OF_PERSONS,
                     aa.NO_OF_UNITS,
                     aa.NUMBER_OF_LANES,
                     aa.OFFICIAL_MILES,
                     aa.OFFSET,
                     aa.ONE_WAY,
                     aa.ONE_WAY_DESCR,
                     aa.OWNER,
                     aa.OWNER_DESCR,
                     aa.PAVEMENT_CONDITION_CSL,
                     aa.PAVEMENT_RUTTING_CSL,
                     aa.PAVEMENT_WIDTH_CSL,
                     aa.PCR,
                     aa.PEDESTRIAN_YN,
                     aa.PLOW_CREW,
                     aa.PMS_FILE_NAME,
                     aa.PMS_INVENTORY_YEAR,
                     aa.PRIMARY,
                     aa.PRIMARY_ROUTE_MP,
                     aa.PRIMARY_ROUTE_NAME,
                     aa.PRIMARY_ROUTE_NUMBER,
                     aa.PRIORITY,
                     aa.RAMP,
                     aa.RAMP_DESCR,
                     aa.REGION_CODE,
                     aa.REGION_NAME,
                     aa.REPORTING_AGENCY,
                     aa.REPORTING_AGENCY_DESCR,
                     aa.REPORT_NUMBER,
                     aa.RIDE_QUALITY_CSL,
                     aa.RIGHT_LANE_CROSSSECTION,
                     aa.RIGHT_RUT,
                     aa.RIGHT_SHOULDER_TYPE,
                     aa.RIGHT_SHOULDER_TYPE_DESCR,
                     aa.RIGHT_SHOULDER_WIDTH,
                     aa.RIGHT_SIDEWALK_TYPE,
                     aa.RIGHT_SIDEWALK_TYPE_DESCR,
                     aa.RIGHT_SIDEWALK_WIDTH,
                     aa.RIGHT_TURN_LANE_COUNT,
                     aa.RIGHT_TURN_LANE_WIDTH,
                     aa.ROADWAY_STRENGTH_CSL,
                     aa.ROADWAY_TYPE,
                     aa.ROADWAY_TYPE_DESCR,
                     aa.ROAD_GRADE,
                     aa.ROAD_GRADE_DESCR,
                     aa.ROAD_POSTING_CSL,
                     aa.ROAD_SURF_COND,
                     aa.ROAD_SURF_COND_DESCR,
                     aa.ROUTE_GROUP,
                     aa.ROUTE_NAME,
                     aa.ROUTE_NUMBER,
                     aa.ROUTE_SYSTEM,
                     aa.ROUTE_TYPE,
                     aa.ROW_TYPE,
                     aa.RUT_CSL,
                     aa.SAFETY_CSL,
                     aa.SCENIC_BYWAY_DESCRIPTION,
                     aa.SCENIC_BYWAY_DESIG_YR,
                     aa.SCENIC_BYWAY_NAME,
                     aa.SCENIC_BYWAY_TYPE,
                     aa.SCENIC_BYWAY_TYPE_DESCR,
                     aa.SCHOOL_BUS_RELATED,
                     aa.SCHOOL_BUS_RELATED_DESCR,
                     aa.SECONDARY_CRASH_YN,
                     aa.SECTION_ID,
                     aa.SECTION_LENGTH,
                     aa.SERVICE_CSL,
                     aa.SH_SA_IR_DESIGNATION,
                     aa.SLD_FILE_DATE, 
                     aa.SLD_FILE_NAME, 
                     snap_year,                               -- SNAPSHOT_YEAR
                     aa.SORTORD,
                     aa.SPEED,
                     aa.SPEEDSRC,
                     aa.SPEEDZN_ID,
                     aa.SPEED_LIMIT,
                     aa.SPUR_NUMBER,
                     aa.STATE_AID_NO,
                     aa.STATE_DESIGNATION_NUMBER,
                     aa.STATE_DESIG_TYPE,
                     aa.STATE_DESIG_TYPE_DESCR,
                     aa.STATE_HIGHWAY_DESIGNATION_NUMBER,
                     aa.STATE_URBAN_RURAL,
                     aa.STATE_URBAN_RURAL_DESCR,
                     aa.STRATEGIC_HIGHWAY_NETWORK,
                     aa.STRATEGIC_HIGHWAY_NETWORK_DESC,
                     aa.STREETNAME,
                     aa.STREET_NAME,
                     aa.STREET_NAME_PREFIX,
                     aa.STREET_NAME_SUFFIX,
                     aa.STRUCT_BRIDGE_COND_CSL,
                     aa.SUMMER_CREW,
                     aa.THRU_LANE_COUNT,
                     aa.THRU_LANE_WIDTH,
                     aa.TOTAL_PAVEMENT_WIDTH,
                     aa.TOWNLINE_NODE,
                     aa.TOWN_CODE,
                     aa.TOWN_NAME,
                     aa.TRAFFIC_CONTROL_DEVICE,
                     aa.TRAFFIC_CONTROL_DEVICE_DESCR,
                     aa.TRAFFIC_SIGNAL,
                     aa.TRANSPORTATION_MODE,
                     aa.TRF_CNTRL_DEV_OPRATIONL,
                     aa.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                     aa.TRUCK_LANE_COUNT,
                     aa.TRUCK_LANE_WIDTH,
                     aa.TRUCK_PERCENT,
                     aa.TYPE_OF_CRASH,
                     aa.TYPE_OF_CRASH_DESCR,
                     aa.TYPE_OF_LOCATION,
                     aa.TYPE_OF_LOCATION_DESCR,
                     aa.WCSH_AGREEMENT,
                     aa.WCSH_CODE,
                     aa.WEATHER_CONDITION,
                     aa.WEATHER_CONDITION_DESCR,
                     aa.WEIGHTED_IRI_CSL,
                     aa.WEIGHTED_PCR_CSL,
                     aa.WIDTH,
                     aa.WINTER_CREW,
                     aa.WORKZONE_IN_OR_NEAR,
                     aa.WORKZONE_IN_OR_NEAR_DESCR,
                     aa.WORKZONE_LOCATION,
                     aa.WORKZONE_LOCATION_DESCR,
                     aa.WORKZONE_POLICE_PRESENT,
                     aa.WORKZONE_POLICE_PRESENT_DESCR,
                     aa.WORKZONE_TYPE,
                     aa.WORKZONE_TYPE_DESCR,
                     aa.WORKZONE_WORKERS_PRESENT,
                     aa.WORKZONE_WORKERS_PRESENT_DESCR)
                LOG ERRORS INTO CRASHES_ON_ROUTE_ERROR_LOG
                        ('LOAD_CRASHES_ON_ROUTE ' || SYSDATE)
                        REJECT LIMIT 100;

        commit_count := commit_count + 1;

        IF commit_count > 10000
        THEN
            COMMIT;
            commit_count := 0;
        END IF;
    END LOOP;

    COMMIT;
    MANAGE_INDEXES.Rebuild_Unusable_Indexes ('CRASHES_ON_ROUTE');

    SELECT COUNT (*) INTO cntr FROM CRASHES_ON_ROUTE;

    WH_COMMON.PKG_COMMON_UTILITIES.UPDATE_WHSE_LOG (
        OWNER         => G_OWNER,
        OBJECT_NAME   => g_object,
        object_cnt    => cntr,
        proc          => $$PLSQL_UNIT,
        start_time    => g_start_time);
EXCEPTION
    WHEN OTHERS
    THEN
        G_SQLMSG := $$PLSQL_UNIT || ': ' || SUBSTR (SQLERRM, 1, 400);
        WH_COMMON.PKG_COMMON_UTILITIES.UPDATE_WHSE_LOG (
            OWNER         => G_OWNER,
            OBJECT_NAME   => g_object,
            MSG           => G_SQLMSG,
            STATUS        => 'Failed');

        WH_COMMON.PKG_COMMON_UTILITIES.EXIT_AND_REPORT (
            g_jobname,
            'FAILURE',
            $$PLSQL_UNIT || ' ' || SUBSTR (SQLERRM, 1, 400));
        RAISE_APPLICATION_ERROR (-20010, G_SQLMSG);
END;
/
