CREATE OR REPLACE VIEW WH_ASSETS.NODES
BEQUEATH DEFINER
AS 
SELECT COUNTY_CODE1,
           COUNTY_CODE2,
           COUNTY_NAME1,
           COUNTY_NAME2,
           ELEMENT_ID,
           FACTORED_AADT,
           FEDERAL_FUNCTIONAL_CLASS,
           FEDERAL_FUNCTIONAL_CLASS_DESCR,
           FEDERAL_URBAN_GROUP,
           FEDERAL_URBAN_GROUP_DESCR,
           FEDERAL_URBAN_RURAL,
           FEDERAL_URBAN_RURAL_DESCR,
           HASS_DESCR,
           JURISDICTION,
           LATITUDE,
           LONGITUDE,
           MEV,
           NHS_STATUS,
           NODE_DESCRIPTION,
           NODE_ID,
           NODE_TYPE,
           NO_OF_LEGS,
           OFFSET,
           PRIMARY_ROUTE_MP,
           PRIMARY_ROUTE_NAME,
           PRIMARY_ROUTE_NUM,
           PRIORITY,
           REGION1,
           REGION2,
           REGION_NAME1,
           REGION_NAME2,
           ROUTE_TYPE,
           SECTION_ID,
           SIGNAL_ID, 
           SIGNAL_TYPE,
           STATE_URBAN_RURAL,
           STATE_URBAN_RURAL_DESCR,
           TOWNLINE_NODE,
           TOWN_CODE1,
           TOWN_CODE2,
           TOWN_NAME1,
           TOWN_NAME2,
           TRAFFIC_SIGNAL
      FROM NODES_HISTORY
     WHERE END_DATE IS NULL;
