CREATE OR REPLACE VIEW WH_ASSETS.ROUTES
BEQUEATH DEFINER
AS 
SELECT BEGIN_ELEMENT_MILEPOINT,
BEGIN_NODE_ID,
CUMULATIVE_MILEPOINT_ORDER,
DIRECTION,
ELEMENT_ID,
ELEMENT_LENGTH,
ELEMENT_WID,
END_ELEMENT_MILEPOINT,
END_NODE_ID,
PRIMARY,
REGION,
REGION_DESCR,
ROUTE_GROUP,
ROUTE_ID,
ROUTE_NAME,
ROUTE_NUMBER,
ROUTE_SYSTEM,
ROUTE_TYPE,
SORTORD,
TOWN,
TOWN_CODE,
TRANSPORTATION_MODE
      FROM ROUTES_HISTORY
     WHERE END_DATE IS NULL;
