CREATE OR REPLACE VIEW WH_ASSETS.ROUTE_SECTIONS
BEQUEATH DEFINER
AS 
SELECT AADT,
           AADT_TYPE,
           AADT_TYPE_DESCR,
           AADT_YEAR,
           ABN,
           ABN_DESCR,
           ACCESS_CONTROL,
           ACCESS_CONTROL_DESCR,
           AGENCY,
           AGENCY_DESCR,
           BASE_AS_BUILT_HMA,        
           BASE_GRAN_THICK,
           BASE_GRAN_TYPE,
           BASE_GRAN_TYPE_DESCR,
           BASE_MISC_THICK,                 
           BASE_MISC_TYPE,                  
           BASE_MISC_TYPE_DESCR,            
           BASE_MOD_TYPE,                   
           BASE_MOD_TYPE_DESCR,             
           BASE_MOD_YR,                     
           BASE_PRI_ID_TYPE,                
           BASE_PRI_ID_TYPE_DESCR,          
           BASE_PRIMARY_ID,                 
           BASE_PRIMARY_WIN,                
           BASE_SEC_ID_TYPE,                
           BASE_SEC_ID_TYPE_DESCR,          
           BASE_SECOND_ID,                  
           BASE_SUB_THICK,  
           r.BEGIN_ELEMENT_MILEPOINT,
           CASE
               WHEN R.direction = 1 THEN E.BEGIN_NODE_DESCRIPTION
               WHEN R.direction = -1 THEN E.END_NODE_DESCRIPTION
           END,                                  --    BEGIN_NODE_DESCRIPTION,
           CASE
               WHEN R.direction = 1 THEN E.BEGIN_NODE_ID
               WHEN R.direction = -1 THEN E.END_NODE_ID
           END,                                             --  BEGIN_NODE_ID,
           s.BEGIN_OFFSET,
           CASE
               WHEN r.direction = 1
               THEN
                   r.BEGIN_ELEMENT_MILEPOINT + S.BEGIN_OFFSET
               WHEN r.direction = -1
               THEN
                   r.END_ELEMENT_MILEPOINT - S.END_OFFSET
           END,
           --          BEGIN_SECTION_MP,
           BRIDGE_POSTING_CSL,
           BRIDGE_RELIABILITY_CSL,
           CAPACITY,
           CENTER_TURN_LANE_COUNT,
           CENTER_TURN_LANE_WIDTH,
           CONDITION_CSL,
           CONGESTION_CSL,
           CONGESTION_RATE_CSL,
           COUNTY_CODE,
           COUNTY_NAME,
           CRASH_HISTORY_CSL,
           CRASH_HISTORY_RATE_CSL,
           CSL_YEAR,
           r.CUMULATIVE_MILEPOINT_ORDER,
           r.DIRECTION,
           DIRECTIONAL_SUFFIX,
           e.ELEMENT_ID,
           r.ELEMENT_LENGTH,
           e.ELEMENT_WID,
           r.END_ELEMENT_MILEPOINT,
           CASE
               WHEN R.direction = 1 THEN E.END_NODE_DESCRIPTION
               WHEN R.direction = -1 THEN E.BEGIN_NODE_DESCRIPTION
           END,                                    --    END_NODE_DESCRIPTION,
           CASE
               WHEN R.direction = 1 THEN E.END_NODE_ID
               WHEN R.direction = -1 THEN E.BEGIN_NODE_ID
           END,                                                -- END_NODE_ID,
           s.END_OFFSET,
           CASE
               WHEN r.direction = 1
               THEN
                   r.BEGIN_ELEMENT_MILEPOINT + S.END_OFFSET
               WHEN r.direction = -1
               THEN
                   r.END_ELEMENT_MILEPOINT - S.BEGIN_OFFSET
           END,
           --         END_SECTION_MP,
           EXCEPTIONS_DESC_XXX,
           EXISTING,
           FACTORED_AADT,
           FACTORED_AADT_CALC_COMMENT,
           FACTOR_GROUP,
           FACTOR_YEAR,
           FED_AID,
           FEDERAL_FUNCTIONAL_CLASS,
           FEDERAL_FUNCTIONAL_CLASS_DESCR,
           FEDERAL_URBAN_GROUP,
           FEDERAL_URBAN_GROUP_DESCR,
           FEDERAL_URBAN_RURAL,
           FEDERAL_URBAN_RURAL_DESCR,
           FUTURE_ADT,
           FUTURE_ADT_YEAR,
           GA_TYPE,
           GA_TYPE_DESCR,
           HASS_DESCRIPTION,
           HASS_ID,
           HPMS_SECTION_ID,
           HPMT_COMB_AADT_PCNT,
           HPMT_COMB_DHV_PCNT,
           HPMT_DHV_PCNT,
           HPMT_DIR_DIST,
           HPMT_PASS_AADT_PCNT,
           HPMT_PASS_DHV_PCNT,
           HPMT_SU_AADT_PCNT,
           HPMT_SU_DHV_PCNT,
           HUNDRED_MILLION_VEHICLE_MILES,
           IRI,
           JURISDICTION,
           JURISDICTION_ABBREVIATION,
           JURISDICTION_CODE,
           LANE_COUNT,
           LANE_SURFACE_TYPE,
           LANE_SURFACE_TYPE_DESCR,
           LAST_TREATMENT_PSN,
           LEFT_LANE_CROSSSECTION,
           LEFT_RUT,
           LEFT_SHOULDER_TYPE,
           LEFT_SHOULDER_TYPE_DESCR,
           LEFT_SHOULDER_WIDTH,
           LEFT_SIDEWALK_TYPE,
           LEFT_SIDEWALK_TYPE_DESCR,
           LEFT_SIDEWALK_WIDTH,
           LEFT_TURN_LANE_COUNT,
           LEFT_TURN_LANE_WIDTH,
           MAINT_RESP_WINTER,
           MAINT_RESP_WINTER_DESCR,
           MAINT_RESP_YEARROUND,
           MAINT_RESP_YEAR_DESCR,
           MEAN_SUM_DEFLECTION_CSL,
           MEDIAN_AVERAGE_WIDTH,
           MEDIAN_TYPE,
           MEDIAN_TYPE_DESCR,
           MIN_PAVEMENT_WIDTH_CSL,
           MIN_STRUCT_BRIDGE_COND_CSL,
           MPO,
           NATIONAL_TRUCK_NETWORK,
           NATIONAL_TRUCK_NETWORK_DESCR,
           NHFN_CONNECTOR_ID,
           NHFN_SUBSYSTEM,
           NHFN_SUBSYSTEM_DESCR,
           NHS_STATUS,
           NHS_TYPE,
           NHS_TYPE_DESCR,
           LANE_COUNT,
           OFFICIAL_MILES,
           ONE_WAY,
           ONE_WAY_DESCR,
           OWNER,
           OWNER_DESCR,
           PAVEMENT_CONDITION_CSL,
           PAVEMENT_RUTTING_CSL,
           PAVEMENT_WIDTH_CSL,
           PCR,
           PLOW_CREW,
           PMS_FILE_NAME,
           PMS_INVENTORY_YEAR,
           r.PRIMARY,
           e.PRIMARY_ROUTE_NAME,
           e.PRIMARY_ROUTE_NUMBER,
           PRIORITY,
           RAMP,
           RAMP_DESCR,
           e.REGION,
           e.REGION_DESCR,
           RIDE_QUALITY_CSL,
           RIGHT_LANE_CROSSSECTION,
           RIGHT_RUT,
           RIGHT_SHOULDER_TYPE,
           RIGHT_SHOULDER_TYPE_DESCR,
           RIGHT_SHOULDER_WIDTH,
           RIGHT_SIDEWALK_TYPE,
           RIGHT_SIDEWALK_TYPE_DESCR,
           RIGHT_SIDEWALK_WIDTH,
           RIGHT_TURN_LANE_COUNT,
           RIGHT_TURN_LANE_WIDTH,
           ROADWAY_STRENGTH_CSL,
           ROADWAY_TYPE,
           ROADWAY_TYPE_DESCR,
           ROAD_POSTING_CSL,
           r.ROUTE_GROUP,
           r.ROUTE_ID,
           r.ROUTE_NAME,
           r.ROUTE_NUMBER,
           r.ROUTE_SYSTEM,
           r.ROUTE_TYPE,
           RUT_CSL,
           SAFETY_CSL,
           SCENIC_BYWAY_DESCRIPTION,
           SCENIC_BYWAY_DESIG_YR,
           SCENIC_BYWAY_NAME,
           SCENIC_BYWAY_TYPE,
           SCENIC_BYWAY_TYPE_DESCR,
           s.SECTION_ID,
           SECTION_LENGTH,
           SERVICE_CSL,
           SH_SA_IR_DESIGNATION,
           SLD_FILE_DATE,                   
           SLD_FILE_NAME,
           R.SORTORD,
           SPEED,
           SPEEDSRC,
           SPEEDZN_ID,
           SPUR_NUMBER,
           STATE_AID_NO,
           STATE_DESIGNATION_NUMBER,
           STATE_DESIG_TYPE,
           STATE_DESIG_TYPE_DESCR,
           STATE_HIGHWAY_DESIGNATION_NUMBER,
           STATE_URBAN_RURAL,
           STATE_URBAN_RURAL_DESCR,
           STRATEGIC_HIGHWAY_NETWORK,
           STRATEGIC_HIGHWAY_NETWORK_DESC,
           STREET_NAME,
           STREET_NAME_PREFIX,
           STREET_NAME_SUFFIX,
           TRIM (
                  STREET_NAME_PREFIX
               || ' '
               || STREET_NAME
               || ' '
               || STREET_NAME_SUFFIX),
           STRUCT_BRIDGE_COND_CSL,
           SUMMER_CREW,
           THRU_LANE_COUNT,
           THRU_LANE_WIDTH,
           TOTAL_PAVEMENT_WIDTH,
           e.TOWN,
           e.TOWN_CODE,
           TRANSPORTATION_MODE,
           TRUCK_LANE_COUNT,
           TRUCK_LANE_WIDTH,
           TRUCK_PERCENT,
           WCSH_AGREEMENT,
           WCSH_CODE,
           WEIGHTED_IRI_CSL,
           WEIGHTED_PCR_CSL,
           WIDTH,
           WINTER_CREW
      FROM SECTIONS  S
           JOIN elements e ON s.element_id = e.element_id
           JOIN ROUTES R ON E.ELEMENT_ID = R.ELEMENT_ID
           LEFT OUTER JOIN CROSS_SECTIONS C
               ON     R.ROUTE_NUMBER = C.ROUTE_NUMBER
                  AND S.SECTION_ID = C.SECTION_ID;
