CREATE OR REPLACE VIEW WH_ASSETS.RTE_MAINTREG
BEQUEATH DEFINER
AS 
SELECT DISTINCT
        T2.ROUTE_NUMBER AS RTCODE,
        T2.ROUTE_TYPE AS RTTYPE,
        T2.ROUTE_NAME AS RTNAME,
        T3.ROUTE_SYSTEM AS RTSYSTEM,
        T1.MAINTENANCE_REGION AS MREG,
        T1.MREG_NAME
    FROM
        ROUTES T2
        LEFT JOIN WH_COMMON.DIM_TOWNS T1 ON T1.TOWNNAME = T2.TOWN
        LEFT JOIN WH_COMMON.DIM_ROUTES T3 ON T3.ROUTE_NUMBER = T2.ROUTE_NUMBER
    WHERE
        T1.MAINTENANCE_REGION IS NOT NULL
        AND T2.ROUTE_TYPE IN (
            'I',
            'M',
            'N',
            'R'
        )
    ORDER BY
        T2.ROUTE_NUMBER,
        T1.MAINTENANCE_REGION;
