CREATE OR REPLACE VIEW WH_ASSETS.V_BNS_PED_BIKE
BEQUEATH DEFINER
AS 
WITH
        oneelementsetup
        AS
            (SELECT element_id,
                    node_id,
                    offset,
                    ROWNUM     AS rn
               FROM (SELECT begin_node_id     AS node_id,
                            0                 AS offset,
                            'BEGIN'           AS offset_type,
                            element_id
                       FROM elements
                     UNION
                     SELECT end_node_id        AS node_id,
                            element_length     AS offset,
                            'END'              AS offset_type,
                            element_id
                       FROM elements)),
        minelement
        AS
            (  SELECT MIN (rn) AS min_rn, node_id
                 FROM oneelementsetup
             GROUP BY node_id),
        nodeaccidents
        AS
            (SELECT DISTINCT node_id
               FROM accidents
              WHERE element_id IS NULL AND node_id IS NOT NULL)
    SELECT a.ped_bike_num,
           a.ped_bike_type,
           a.maxinjury_degreecd,
           a.maxinjury_degreedesc,
           a.ped_bike_k,
           a.ped_bike_a,
           a.ped_bike_b,
           a.ped_bike_c,
           a.ped_bike_pd,
           a.ped_bike_injdegcd,
           a.PED_BIKE_INJDEGREEDESC,
           a.NUM_PED_BIKE_INJ,
           b."ACCIDENT_DATE",
           b."ACCIDENT_DAY_OF_WEEK_NUM",
           b."ACCIDENT_DAY_OF_WEEK",
           b."ACCIDENT_TIME",
           b."ACCIDENT_YEAR",
           b."CONTRIB_CIRC_ENV1",
           b."CONTRIB_CIRC_ENV1_DESCR",
           b."CONTRIB_CIRC_ENV2",
           b."CONTRIB_CIRC_ENV2_DESCR",
           b."CONTRIB_CIRC_ROAD1",
           b."CONTRIB_CIRC_ROAD1_DESCR",
           b."CONTRIB_CIRC_ROAD2",
           b."CONTRIB_CIRC_ROAD2_DESCR",
           b."COUNTY_CODE",
           b."COUNTY_NAME",
           b."CRASH_COST",
           d.element_id,
           b.FARS_YN,
           b."ELEMENT_WID",
           b."INJURY_COUNT",
           b."LIGHT_CONDITION",
           b."LIGHT_CONDITION_DESCR",
           b."LOCATION_TYPE",
           b."LOC_FIRST_HARMFUL_EVENT",
           b."LOC_FIRST_HARMFUL_EVENT_DESCR",
           b."MDOTID",
           b."NO_OF_A_INJ",
           b."NO_OF_B_INJ",
           b."NO_OF_C_INJ",
           b."NO_OF_K_INJ",
           b."NO_OF_NON_INJ",
           b."NODE_ID",
           d.offset,
           b."REPORTING_AGENCY",
           b."REPORTING_AGENCY_DESCR",
           b."ROAD_SURF_COND",
           b."ROAD_SURF_COND_DESCR",
           b."ROAD_GRADE",
           b."ROAD_GRADE_DESCR",
           b."SECTION_ID",
           b."SCHOOL_BUS_RELATED",
           b."SCHOOL_BUS_RELATED_DESCR",
           b."TRAFFIC_CONTROL_DEVICE",
           b."TRAFFIC_CONTROL_DEVICE_DESCR",
           b."TYPE_OF_CRASH",
           b."TYPE_OF_CRASH_DESCR",
           b."TYPE_OF_LOCATION",
           b."TYPE_OF_LOCATION_DESCR",
           b."WEATHER_CONDITION",
           b."WEATHER_CONDITION_DESCR",
           b."WORKZONE_IN_OR_NEAR",
           b."WORKZONE_IN_OR_NEAR_DESCR",
           b."WORKZONE_LOCATION",
           b."WORKZONE_LOCATION_DESCR",
           b."WORKZONE_TYPE",
           b."WORKZONE_TYPE_DESCR",
           b."WORKZONE_WORKERS_PRESENT",
           b."WORKZONE_WORKERS_PRESENT_DESCR",
           b."WORKZONE_POLICE_PRESENT",
           b."WORKZONE_POLICE_PRESENT_DESCR",
           b."PRIMARY_ROUTE_NUMBER",
           b."PRIMARY_ROUTE_NAME",
           b."REPORT_NUMBER",
           b."LATITUDE",
           b."LONGITUDE",
           b."ACCIDENT_MONTH_NUM",
           b."ACCIDENT_MONTH_NAME",
           b."TOWN_CODE",
           b."TOWN_NAME",
           b."REGION_CODE",
           b."REGION_NAME",
           b."SPEED_LIMIT",
           b."FEDERAL_URBAN_GROUP",
           b."FEDERAL_URBAN_GROUP_DESCR",
           b."PRIMARY_ROUTE_MP",
           b."ACCIDENT_HOUR",
           b."INJURY_LEVEL",
           b."INJURY_LEVEL_CODE"
      FROM mV_BNS_PED_BIKE  a
           JOIN accidents b ON a.mdotid = b.mdotid
           JOIN oneelementsetup d ON d.node_id = b.node_id
           JOIN minelement c ON d.rn = c.min_rn
     WHERE b.element_id IS NULL AND b.node_id IS NOT NULL
    UNION ALL
    SELECT a.ped_bike_num,
           a.ped_bike_type,
           a.maxinjury_degreecd,
           a.maxinjury_degreedesc,
           a.ped_bike_k,
           a.ped_bike_a,
           a.ped_bike_b,
           a.ped_bike_c,
           a.ped_bike_pd,
           a.ped_bike_injdegcd,
           a.PED_BIKE_INJDEGREEDESC,
           a.NUM_PED_BIKE_INJ,
           b."ACCIDENT_DATE",
           b."ACCIDENT_DAY_OF_WEEK_NUM",
           b."ACCIDENT_DAY_OF_WEEK",
           b."ACCIDENT_TIME",
           b."ACCIDENT_YEAR",
           b."CONTRIB_CIRC_ENV1",
           b."CONTRIB_CIRC_ENV1_DESCR",
           b."CONTRIB_CIRC_ENV2",
           b."CONTRIB_CIRC_ENV2_DESCR",
           b."CONTRIB_CIRC_ROAD1",
           b."CONTRIB_CIRC_ROAD1_DESCR",
           b."CONTRIB_CIRC_ROAD2",
           b."CONTRIB_CIRC_ROAD2_DESCR",
           b."COUNTY_CODE",
           b."COUNTY_NAME",
           b."CRASH_COST",
           b.element_id,
           b.FARS_YN,
           b."ELEMENT_WID",
           b."INJURY_COUNT",
           b."LIGHT_CONDITION",
           b."LIGHT_CONDITION_DESCR",
           b."LOCATION_TYPE",
           b."LOC_FIRST_HARMFUL_EVENT",
           b."LOC_FIRST_HARMFUL_EVENT_DESCR",
           b."MDOTID",
           b."NO_OF_A_INJ",
           b."NO_OF_B_INJ",
           b."NO_OF_C_INJ",
           b."NO_OF_K_INJ",
           b."NO_OF_NON_INJ",
           b."NODE_ID",
           b.offset,
           b."REPORTING_AGENCY",
           b."REPORTING_AGENCY_DESCR",
           b."ROAD_SURF_COND",
           b."ROAD_SURF_COND_DESCR",
           b."ROAD_GRADE",
           b."ROAD_GRADE_DESCR",
           b."SECTION_ID",
           b."SCHOOL_BUS_RELATED",
           b."SCHOOL_BUS_RELATED_DESCR",
           b."TRAFFIC_CONTROL_DEVICE",
           b."TRAFFIC_CONTROL_DEVICE_DESCR",
           b."TYPE_OF_CRASH",
           b."TYPE_OF_CRASH_DESCR",
           b."TYPE_OF_LOCATION",
           b."TYPE_OF_LOCATION_DESCR",
           b."WEATHER_CONDITION",
           b."WEATHER_CONDITION_DESCR",
           b."WORKZONE_IN_OR_NEAR",
           b."WORKZONE_IN_OR_NEAR_DESCR",
           b."WORKZONE_LOCATION",
           b."WORKZONE_LOCATION_DESCR",
           b."WORKZONE_TYPE",
           b."WORKZONE_TYPE_DESCR",
           b."WORKZONE_WORKERS_PRESENT",
           b."WORKZONE_WORKERS_PRESENT_DESCR",
           b."WORKZONE_POLICE_PRESENT",
           b."WORKZONE_POLICE_PRESENT_DESCR",
           b."PRIMARY_ROUTE_NUMBER",
           b."PRIMARY_ROUTE_NAME",
           b."REPORT_NUMBER",
           b."LATITUDE",
           b."LONGITUDE",
           b."ACCIDENT_MONTH_NUM",
           b."ACCIDENT_MONTH_NAME",
           b."TOWN_CODE",
           b."TOWN_NAME",
           b."REGION_CODE",
           b."REGION_NAME",
           b."SPEED_LIMIT",
           b."FEDERAL_URBAN_GROUP",
           b."FEDERAL_URBAN_GROUP_DESCR",
           b."PRIMARY_ROUTE_MP",
           b."ACCIDENT_HOUR",
           b."INJURY_LEVEL",
           b."INJURY_LEVEL_CODE"
      FROM mV_BNS_PED_BIKE a JOIN accidents b ON a.mdotid = b.mdotid
     WHERE b.element_id IS NOT NULL;
