CREATE OR REPLACE VIEW WH_ASSETS.V_METRANS_FACT_CSL
BEQUEATH DEFINER
AS 
SELECT "CSL_YEAR","MIN_STRCTBRDGCND","WEIGHTED_PCR","WEIGHTED_IRI","PVECND","RDEQTY","RDWYSTRN","STRCBRDG","CND_SCORE","MEAN_SUM_DEF","RUT","MINPVWDT","CRSHIS","PVNRUT","PVWDTH","BRDGREL","SFT_SCORE","RDPSTING","SRV_SCORE","CNGSTN_RTE","CNGSTN","BRDGPST","CRSHRTE","FERRY","ELEMENT_ID","ELEMENT_START_DATE","ELEMENT_END_DATE","ELEMENT_LENGTH","RLM_DATE","TOWNNAME","GEOCODE","COUNTY","REGION","PRIRTECODE","PRIRTENAME","PRIRTEBMP","PRIRTEEMP","PRIORITY","STREET_NAME","RAMP","OWNER","AGENCY" FROM MV_FACT_CSL@METRANS;
