CREATE OR REPLACE VIEW WH_ASSETS.V_QC_BAD_STATE_ROAD_LENGTHS
BEQUEATH DEFINER
AS 
SELECT "Element ID","Logical Length","Designation","Geometric Length","Logical-Geometric" FROM V_QC_BAD_STATE_ROAD_LENGTHS@METRANS;
