CREATE OR REPLACE VIEW WH_ASSETS.V_QC_SIGNAL_MISSING_FROM_CAS
BEQUEATH DEFINER
AS 
SELECT "ASSET_SYS_ID","SIGNAL_BEACON","NEAREST_NODE","PRIMARYNODE","ASSOCIATEDNODE" FROM V_QC_SIGNAL_MISSING_FROM_CAS@METRANS;
