CREATE OR REPLACE VIEW WH_ASSETS.V_QC_ELEMENTS_NO_AADT
BEQUEATH DEFINER
AS 
SELECT "NE_ID_OF","NM_BEGIN_MP","NM_END_MP","TOWNNAME","THRUTYPERD","THRUTYPERD_DESC","PRIORITY","FEDFUNCCLS" FROM V_QC_ELEMENTS_NO_AADT@METRANS;
