CREATE OR REPLACE VIEW WH_ASSETS.V_TIDE_URIP_SUMMARY
BEQUEATH DEFINER
AS 
SELECT "TIDEYEAR","PAYEE_CODE","PAYEE_FEDERAL_ID","TOTAL_PAID","MODIFIED_DATE","RURAL_PERCENT","URBAN_PERCENT","EXTRACT_DOLLARS","MINIMUM_DOLLARS","TOTAL_DUE","BUDGET_DOLLARS","ADJUSTMENT_DOLLARS","NET_AMOUNT","CALCULATION_TYPE","CERTIFICATION_STATUS","PAYEE_NAME","MAILING_LIST","MAINTENANCE_REGION","COUNTY" FROM URIP_SUMMARY@TIDE;
