CREATE OR REPLACE VIEW WH_ASSETS.V_TIDE_URIP_SEGMENTS
BEQUEATH DEFINER
AS 
SELECT "SEGMENT_ID","LINK_ID","TOWN","COUNTY","GROUP_NUMBER","GROUP_NAME","CENTERLANE","THRU2","THRU3","LEFTTURN","RIGHTTURN","CENTERTURN","TRUCKCLIMBING","TOWNNAME","ROUTE","BMP","STREET","DIR","BOFFSET","EOFFSET","TIDEYEAR","PAYEE_CODE","PAYEE_TYPE","PAYEE_NAME" FROM URIP_SEGMENTS@TIDE

--GRANT SELECT ON V_TIDE_URIP_SEGMENTS to DASH_USER
;
