CREATE OR REPLACE VIEW WH_ASSETS.CINDY_TEST_SPEED_ZONE
BEQUEATH DEFINER
AS 
SELECT 'NON-NUMBERED' AS SZ_GROUP,
SZ_UPDATED_BY, SZ_LAST_UPDATE, SZ_EFFECTIVE_DATE, 
   RT_UPDATED_BY, RT_LAST_UPDATE, ASSET_DESCR, 
   STREET_TYPE, STREET_NAME, STREET_PREFIX, 
   END_MP, END_DESCR, END_OFFSET, 
   END_NODE, START_DESCR, START_OFFSET, 
   START_NODE, SZ_DESCR, SPEED, 
   SPEED_ZONE_ID, DISTANCE, SEQ_NO, 
   LENGTH, ASSET, RTE_NAME, 
   TOWN, REGION, ROUTE
FROM DEVMETRN.SPEED_ZONES_VIEW_RD_INV@metrans
union
SELECT 'NUMBERED' AS SZ_GROUP,
SZ_UPDATED_BY, SZ_LAST_UPDATE, SZ_EFFECTIVE_DATE, 
   RT_UPDATED_BY, RT_LAST_UPDATE, ASSET_DESCR, 
   '' STREET_TYPE, '' STREET_NAME, '' STREET_PREFIX, 
   END_MP, END_DESCR, END_OFFSET, 
   END_NODE, START_DESCR, START_OFFSET, 
   START_NODE, SZ_DESCR, SPEED, 
   SPEED_ZONE_ID, DISTANCE, SEQ_NO, 
   LENGTH, ASSET, RTE_NAME, 
   TOWN, REGION, ROUTE
FROM DEVMETRN.SPEED_ZONES_VIEW_1@metrans;
