CREATE OR REPLACE VIEW WH_ASSETS.LINK
BEQUEATH DEFINER
AS 
SELECT "ELEMENT_ID", "BEGIN_NODE_ID", "END_NODE_ID", "ELEMENT_LENGTH", 
    TO_DATE(TO_CHAR(START_DATE,'MM/DD/YYYY'), 'MM/DD/YYYY') AS START_DATE, '', "TOWN_CODE", "TOWN", "COUNTY_CODE", "COUNTY_NAME", '', 
    '', "RAMP", "OFFICIAL_MILES", "EXISTING", "ONE_WAY", "PRIMARY_ROUTE_NUMBER", 
    "PRIMARY_ROUTE_NAME", "ELEMENT_ID", "REGION", '' AS ALTRTECODE_1, 
    '' AS ALTRTECODE_2, '' AS ALTRTECODE_3, '' AS ALTRTECODE_4, '' AS ALTRTECODE_5, 
    '' AS ALTRTECODE_6, '' AS ALTRTECODE_7, '' AS ALTRTECODE_8, '' AS ALTRTECODE_9, 
"FACTOR_GROUP", '' AS IN_SWMN
      FROM ELEMENT_HISTORY
     WHERE END_DATE IS NULL;
