CREATE OR REPLACE VIEW WH_ASSETS.V_BRIDGE_HISTORY
BEQUEATH DEFINER
AS 
SELECT I.BRIDGE_NUMBER,
           UPPER (BRIDGE_NAME),
           SNAPSHOT_YEAR,
           'ASSETWISE',
           ABUT_TO_ABUT_DETOUR,
           APPROACH_ROADWAY_WIDTH,
           APPROACH_SPAN_DESIGN,
           APPROACH_SPAN_DESIGN_DESCR,
           APPROACH_SPAN_MATERIAL,
           APPROACH_SPAN_MATERIAL_DESCR,
           APPROACH_SPAN_NUMBER,
           ARCHIVED_DATE,
           ARCHIVED_REASON,
           ASSET_STATUS,
           ASSET_STATUS_DESCR,
           ASSET_TYPE,
           BORDER_BRIDGE_NUMBER,
           BORDER_BRIDGE_PERCENT_RESP,
           BRIDGE_CONDITION_SCORE,
           BRIDGE_LENGTH,
           BRIDGE_MEDIAN,
           BRIDGE_MEDIAN_DESCR,
           BRIDGE_ON_OFF_SYSTEM,
           BRIDGE_ON_OFF_SYSTEM_DESCR,
           BRIDGE_POSTING_SCORE,
           BRIDGE_RELIABILITY_SCORE,
           CHANNEL_RATING,
           CHANNEL_RATING_DESCR,
           CLEAR_SPAN_LENGTH,
           CO_MAINTAINER,
           CO_MAINTAINER_DESCR,
           CO_OWNER,
           CO_OWNER_DESCR,
           COUNTY2_NAME,
           COUNTY_NAME,
           CULVERT_RATING,
           CULVERT_RATING_DESCR,
           CURB_SIDEWALK_WIDTH_LEFT,
           CURB_SIDEWALK_WIDTH_RIGHT,
           DECK_AREA,
           DECK_GEOMETRY_RATING,
           DECK_MEMBRANE_TYPE,
           DECK_MEMBRANE_TYPE_DESCR,
           DECK_PROTECTION_CODE,
           DECK_PROTECTION_DESCR,
           DECK_RATING,
           DECK_RATING_DESCR,
           DECK_STRUCTURE_TYPE,
           DECK_STRUCTURE_TYPE_DESCR,
           DECK_SURFACE_TYPE,
           DECK_SURFACE_TYPE_DESCR,
           DESIGN_LOAD,
           DESIGN_LOAD_DESCR,
           DETOUR_LENGTH,
           FC_INSPECTION_REQUIRED,
           FEATURE_ON_STRUCTURE,
           FEATURE_UNDER_STRUCTURE,
           FEDERAL_SUFFICIENCY_RATING,
           GEOGRAPHIC_REGION,
           HISTORICAL_SIGNIFICANCE,
           HISTORICAL_SIGNIFICANCE_DESCR,
           HORIZONTAL_CLEARANCE,
           INVENTORY_RATING,
           INVENTORY_RATING_TYPE,
           INVENTORY_RATING_TYPE_DESCR,
           INVRTE_ADT,
           INVRTE_ADT_TRUCK_PERCENT,
           INVRTE_ADT_YR,
           INVRTE_FUNCTIONCLASS,
           INVRTE_FUNCTIONCLASS_DESCR,
           INVRTE_ON_NHS,
           INVRTE_ON_NHS_DESCR,
           INVRTE_RECTYPE,
           INVRTE_ON_STRAHNET,
           INVRTE_ON_STRAHNET_DESCR,
           INVRTE_ON_TRUCKNET,
           INVRTE_ON_TRUCKNET_DESCR,
           LENGTH_MAX_SPAN,
           LR_EV2_RATING,
           LR_EV3_RATING,
           LR_POSTED_DATE,
           MAINTAINER,
           MAINTAINER_DESCR,
           MAIN_SPAN_DESIGN,
           MAIN_SPAN_DESIGN_DESCR,
           MAIN_SPAN_MATERIAL,
           MAIN_SPAN_MATERIAL_DESCR,
           MAIN_SPAN_NUMBER,
           MINOR_SPAN_CODE_DESCR,
           MIN_LAT_UNDER_CLEAR_LEFT,
           MIN_LAT_UNDER_CLEAR_RIGHT,
           MIN_NAVCLR_LIFT_BRDG,
           MIN_VERT_UNDER_CLEARANCE,
           MIN_VERTICAL_CLEARANCE_ON,
           NAVIGATION_CONTROL,
           NAVIGATION_HORIZONTAL,
           NAVIGATION_VERTICAL,
           NBIS_BRIDGE_LENGTH,
           NUMBER_LANES,
           NUMBER_LANES_UNDER,
           OL_NORTH_MAIN_POSTED_FT,
           OL_NORTH_MAIN_POSTED_IN,
           OL_PERMIT_NORTH_FT,
           OL_PERMIT_NORTH_IN,
           OL_PERMIT_SOUTH_FT,
           OL_PERMIT_SOUTH_IN,
           OL_PORTAL_NORTH_POSTED_FT,
           OL_PORTAL_NORTH_POSTED_IN,
           OL_PORTAL_SOUTH_POSTED_FT,
           OL_PORTAL_SOUTH_POSTED_IN,
           OL_SOUTH_MAIN_POSTED_FT,
           OL_SOUTH_MAIN_POSTED_IN,
           ON_BASE_HIGHWAY_NETWORK,
           ON_BASE_HIGHWAY_NETWORK_DESCR,
           OPERATING_RATING,
           OPERATING_RATING_TYPE,
           OPERATING_RATING_TYPE_DESC,
           OWNER,
           OWNER_DESCR,
           PARALLEL_STRUCTURE_DESIG,
           PIER_PROTECTION_RATING,
           POSTED_CLEARANCE,
           POSTED,
           POSTED_WEIGHT_TONS,
           POSTED_1_TRUCK,
           POSTED_4_AXLE,
           POSTED_SPACING,
           PRIORITY,
           RAIL_RATING,
           REMAINING_SERVICE_LIFE,
           SCOUR_RATING,
           SCOUR_RATING_DESCR,
           SKEW_ANGLE,
           STATUS,
           STATUS_DESCR,
           STRUCTURAL_EVALUATION,
           STRUCTURE_OPEN,
           STRUCTURE_OPEN_DESCR,
           SUBSTRUCTURE_RATING,
           SUBSTRUCTURE_RATING_DESCR,
           SUPERSTRUCTURE_RATING,
           SUPERSTRUCTURE_RATING_DESCR,
           TEMP_STUCTURE_DESIG,
           TEMP_STRUCTURE_DESIG_DESCR,
           TOWN_NAME1,
           TOWN_NAME2,
           TRANSITION_RATING,
           TRUCK_WEIGHT_POST_LIMIT,
           TYPE_OF_SERVICE_ON,
           TYPE_OF_SERVICE_ON_DESCR,
           TYPE_OF_SERVICE_UNDER,
           TYPE_OF_SERVICE_UNDER_DESCR,
           UNDERCLEARANCE_RATING,
           UNDERCLEARANCE_RATING_DESCR,
           UW_INSPECTION_REQUIRED,
           VEHICLE_HEIGHT_OVER,
           VEHICLE_HEIGHT_UNDER,
           WATERWAY_ADEQUACY_RATING,
           WATERWAY_ADEQUACY_RATING_DESCR,
           WIDTH,
           WIDTH_CURB_TO_CURB,
           YEAR_BUILT,
           YEAR_LAST_PAINTED,
           YEAR_RECONSTRUCTED,
           YEAR_WS_REPLACED
      FROM Ibridges_history i
    UNION
    SELECT p.BRIDGE_NUMBER,
           UPPER (p.BRIDGE_NAME),
           p.SNAPSHOT_YEAR,
           'PONTIS',
           NULL,                             --           ABUT_TO_ABUT_DETOUR,
           p.APPROACH_ROADWAY_WIDTH,
           CASE
               WHEN p.approach_span_design IN (-1, -2) THEN '00'
               ELSE p.APPROACH_SPAN_DESIGN
           END,
           CASE
               WHEN p.approach_span_design IN (-1, -2)
               THEN
                   '00 - Other'
               ELSE
                      p.APPROACH_SPAN_DESIGN
                   || ' - '
                   || p.APPROACH_SPAN_DESIGN_DESCR
           END,
           CASE
               WHEN p.APPROACH_SPAN_MATERIAL IN ('!', '_') THEN '0'
               ELSE p.APPROACH_SPAN_MATERIAL
           END,
           CASE
               WHEN p.APPROACH_SPAN_MATERIAL IN ('!', '_')
               THEN
                   '0 - Other'
               WHEN p.APPROACH_SPAN_MATERIAL IS NOT NULL
               THEN
                      p.APPROACH_SPAN_MATERIAL
                   || ' - '
                   || p.APPROACH_SPAN_MATERIAL_DESCR
           END,
           p.APPROACH_SPAN_NUMBER,
           NULL,                                            --  ARCHIVED_DATE,
           NULL,                                           -- ARCHIVED_REASON,
           NULL,                                              -- ASSET_STATUS,
           NULL,                                        -- ASSET_STATUS_DESCR,
           i.asset_type,                                        -- ASSET_TYPE,
           NULL,                                      -- BORDER_BRIDGE_NUMBER,
           NULL,                                -- BORDER_BRIDGE_PERCENT_RESP,
           p.BRIDGE_CONDITION_SCORE,
           p.BRIDGE_LENGTH,
           p.BRIDGE_MEDIAN,
           p.BRIDGE_MEDIAN || ' - ' || p.BRIDGE_MEDIAN_DESCR,
           p.BRIDGE_ON_OFF_SYSTEM,
           p.BRIDGE_ON_OFF_SYSTEM_DESCR,
           p.BRIDGE_POSTING_SCORE,
           p.BRIDGE_RELIABILITY_SCORE,
           p.CHANNEL_RATING,
           p.CHANNEL_RATING_DESCR,
           NULL,                                       --   CLEAR_SPAN_LENGTH,
           NULL,                                           --   CO_MAINTAINER,
           NULL,                                     --   CO_MAINTAINER_DESCR,
           NULL,                                                --   CO_OWNER,
           NULL,                                          --   CO_OWNER_DESCR,
           p.COUNTY2_NAME,
           p.COUNTY_NAME,
           p.CULVERT_RATING,
           p.CULVERT_RATING_DESCR,
           NULL,                               --    CURB_SIDEWALK_WIDTH_LEFT,
           NULL,                               --   CURB_SIDEWALK_WIDTH_RIGHT,
           p.DECK_AREA,
           NULL,                                    --   DECK_GEOMETRY_RATING,
           p.DECK_MEMBRANE_TYPE,
           p.DECK_MEMBRANE_TYPE_DESCR,
           NULL,                                     --  DECK_PROTECTION_CODE,
           NULL,                                     -- DECK_PROTECTION_DESCR,
           p.DECK_RATING,
           p.DECK_RATING_DESCR,
           p.DECK_STRUCTURE_TYPE,
           p.DECK_STRUCTURE_TYPE_DESCR,
           p.DECK_SURFACE_TYPE,
           p.DECK_SURFACE_TYPE_DESCR,
           p.DESIGN_LOAD,
           p.DESIGN_LOAD_DESCR,
           p.DETOUR_LENGTH,
           NULL,                                  --   FC_INSPECTION_REQUIRED,
           p.FEATURE_ON_STRUCTURE,
           p.FEATURE_UNDER_STRUCTURE,
           p.FEDERAL_SUFFICIENCY_RATING,
           NULL,                                       --   GEOGRAPHIC_REGION,
           NULL,                                 --   HISTORICAL_SIGNIFICANCE,
           NULL,                            --  HISTORICAL_SIGNIFICANCE_DESCR,
           p.HORIZONTAL_CLEARANCE,
           p.INVENTORY_RATING,
           p.INVENTORY_RATING_TYPE,
           p.INVENTORY_RATING_TYPE_DESCR,
           NULL,                                              --   INVRTE_ADT,
           NULL,                                 --  INVRTE_ADT_TRUCK_PERCENT,
           NULL,                                            --  INVRTE_ADT_YR,
           NULL,                                     --  INVRTE_FUNCTIONCLASS,
           NULL,                               --  INVRTE_FUNCTIONCLASS_DESCR,
           NULL,                                             -- INVRTE_ON_NHS,
           NULL,                                      --  INVRTE_ON_NHS_DESCR,
           NULL,                                            -- INVRTE_RECTYPE,
           NULL,                                      --   INVRTE_ON_STRAHNET,
           NULL,                                 --  INVRTE_ON_STRAHNET_DESCR,
           NULL,                                       --  INVRTE_ON_TRUCKNET,
           NULL,                                 --  INVRTE_ON_TRUCKNET_DESCR,
           p.LENGTH_MAX_SPAN,
           NULL,                                           --   LR_EV2_RATING,
           NULL,                                            --  LR_EV3_RATING,
           NULL,                                           --  LR_POSTED_DATE,
           p.MAINTAINER,
           p.MAINTAINER || ' - ' || p.MAINTAINER_DESCR,
           p.MAIN_SPAN_DESIGN,
           p.MAIN_SPAN_DESIGN_DESCR,
           p.MAIN_SPAN_MATERIAL,
           p.MAIN_SPAN_MATERIAL_DESCR,
           NULL,                                        --   MAIN_SPAN_NUMBER,
           NULL,                                   --   MINOR_SPAN_CODE_DESCR,
           NULL,                                 --  MIN_LAT_UNDER_CLEAR_LEFT,
           NULL,                               --   MIN_LAT_UNDER_CLEAR_RIGHT,
           NULL,                                      -- MIN_NAVCLR_LIFT_BRDG,
           NULL,                                  -- MIN_VERT_UNDER_CLEARANCE,
           NULL,                                --  MIN_VERTICAL_CLEARANCE_ON,
           NULL,                                      --   NAVIGATION_CONTROL,
           NULL,                                   --   NAVIGATION_HORIZONTAL,
           NULL,                                     --   NAVIGATION_VERTICAL,
           p.NBIS_BRIDGE_LENGTH,
           p.NUMBER_LANES,
           NULL,                                      --   NUMBER_LANES_UNDER,
           NULL,                                 --   OL_NORTH_MAIN_POSTED_FT,
           NULL,                                  --  OL_NORTH_MAIN_POSTED_IN,
           NULL,                                       --  OL_PERMIT_NORTH_FT,
           NULL,                                        -- OL_PERMIT_NORTH_IN,
           NULL,                                       --  OL_PERMIT_SOUTH_FT,
           NULL,                                       --  OL_PERMIT_SOUTH_IN,
           NULL,                                --  OL_PORTAL_NORTH_POSTED_FT,
           NULL,                                --  OL_PORTAL_NORTH_POSTED_IN,
           NULL,                                --  OL_PORTAL_SOUTH_POSTED_FT,
           NULL,                                 -- OL_PORTAL_SOUTH_POSTED_IN,
           NULL,                                  --  OL_SOUTH_MAIN_POSTED_FT,
           NULL,                                  --  OL_SOUTH_MAIN_POSTED_IN,
           NULL,                                  --  ON_BASE_HIGHWAY_NETWORK,
           NULL,                            --  ON_BASE_HIGHWAY_NETWORK_DESCR,
           p.OPERATING_RATING,
           p.OPERATING_RATING_TYPE,
           p.OPERATING_RATING_TYPE_DESC,
           p.OWNER,
           CASE
               WHEN INSTR (p.owner_descr, '-') = 0
               THEN
                   p.owner || ' - ' || p.owner_descr
               ELSE
                   p.owner_descr
           END,
           NULL,                                 --  PARALLEL_STRUCTURE_DESIG,
           NULL,                                   --  PIER_PROTECTION_RATING,
           NULL,                                          -- POSTED_CLEARANCE,
           NULL,                                                   --  POSTED,
           NULL,                                        -- POSTED_WEIGHT_TONS,
           NULL,                                            -- POSTED_1_TRUCK,
           NULL,                                             -- POSTED_4_AXLE,
           NULL,                                            -- POSTED_SPACING,
           p.PRIORITY,
           p.RAIL_RATING,
           p.REMAINING_SERVICE_LIFE,
           p.SCOUR_RATING,
           p.SCOUR_RATING_DESCR,
           p.SKEW_ANGLE,
           NULL,                                                    -- STATUS,
           NULL,                                              -- STATUS_DESCR,
           NULL,                                    --  STRUCTURAL_EVALUATION,
           NULL,                                           --  STRUCTURE_OPEN,
           NULL,                                     --  STRUCTURE_OPEN_DESCR,
           p.SUBSTRUCTURE_RATING,
           p.SUBSTRUCTURE_RATING_DESCR,
           p.SUPERSTRUCTURE_RATING,
           p.SUPERSTRUCTURE_RATING_DESCR,
           NULL,                                      --  TEMP_STUCTURE_DESIG,
           NULL,                               --  TEMP_STRUCTURE_DESIG_DESCR,
           p.TOWN_NAME1,
           p.TOWN_NAME2,
           p.TRANSITION_RATING,
           p.TRUCK_WEIGHT_POST_LIMIT,
           p.TYPE_OF_SERVICE_ON,
           p.TYPE_OF_SERVICE_ON_DESCR,
           p.TYPE_OF_SERVICE_UNDER,
           p.TYPE_OF_SERVICE_UNDER_DESCR,
           NULL,                                   --   UNDERCLEARANCE_RATING,
           NULL,                              --  UNDERCLEARANCE_RATING_DESCR,
           NULL,                                  --   UW_INSPECTION_REQUIRED,
           NULL,                                     --   VEHICLE_HEIGHT_OVER,
           NULL,                                     --  VEHICLE_HEIGHT_UNDER,
           p.WATERWAY_ADEQUACY_RATING,
           p.WATERWAY_ADEQUACY_RATING_DESCR,
           p.WIDTH,
           p.WIDTH_CURB_TO_CURB,
           p.YEAR_BUILT,
           NULL,                                       --   YEAR_LAST_PAINTED,
           p.YEAR_RECONSTRUCTED,
           NULL                                           --  YEAR_WS_REPLACED
      FROM PONTIS_BRIDGE_HISTORY  p
           JOIN ibridges i ON p.bridge_number = i.bridge_number
     WHERE SNAPSHOT_YEAR < 2016
    ORDER BY bridge_number, snapshot_year;
