CREATE OR REPLACE VIEW WH_ASSETS.V_COMPLETE_NETWORK
BEQUEATH DEFINER
AS 
SELECT 'Element',
           RS.AADT,
           RS.AADT_TYPE,
           RS.AADT_TYPE_DESCR,
           RS.AADT_YEAR,
           RS.ABN,
           RS.ABN_DESCR,
           RS.ACCESS_CONTROL,
           RS.ACCESS_CONTROL_DESCR,
           RS.AGENCY,
           RS.AGENCY_DESCR,
           RS.BASE_AS_BUILT_HMA,        
           RS.BASE_GRAN_THICK,
           RS.BASE_GRAN_TYPE,
           RS.BASE_GRAN_TYPE_DESCR,
           RS.BASE_MISC_THICK,                 
           RS.BASE_MISC_TYPE,                  
           RS.BASE_MISC_TYPE_DESCR,            
           RS.BASE_MOD_TYPE,                   
           RS.BASE_MOD_TYPE_DESCR,             
           RS.BASE_MOD_YR,                     
           RS.BASE_PRI_ID_TYPE,                
           RS.BASE_PRI_ID_TYPE_DESCR,          
           RS.BASE_PRIMARY_ID,                 
           RS.BASE_PRIMARY_WIN,                
           RS.BASE_SEC_ID_TYPE,                
           RS.BASE_SEC_ID_TYPE_DESCR,          
           RS.BASE_SECOND_ID,                  
           RS.BASE_SUB_THICK,  
           RS.BEGIN_ELEMENT_MILEPOINT,
           RS.BEGIN_NODE_DESCRIPTION,
           RS.BEGIN_NODE_ID,
           RS.BEGIN_OFFSET,                           -- BEGIN_SECTION_OFFSET,
           RS.BEGIN_SECTION_MP,
           RS.BRIDGE_POSTING_CSL,
           RS.BRIDGE_RELIABILITY_CSL,
           RS.CAPACITY,
           RS.CENTER_TURN_LANE_COUNT,
           RS.CENTER_TURN_LANE_WIDTH,
           RS.CONDITION_CSL,
           RS.CONGESTION_CSL,
           RS.CONGESTION_RATE_CSL,
           RS.COUNTY_CODE,
           RS.COUNTY_NAME,
           RS.CRASH_HISTORY_CSL,
           RS.CRASH_HISTORY_RATE_CSL,
           RS.CSL_YEAR,
           RS.CUMULATIVE_MILEPOINT_ORDER,
           RS.DIRECTION,
           RS.DIRECTIONAL_SUFFIX,
           RS.ELEMENT_ID,
           RS.ELEMENT_LENGTH,
           RS.ELEMENT_WID,
           RS.END_ELEMENT_MILEPOINT,
           RS.END_NODE_DESCRIPTION,
           RS.END_NODE_ID,
           RS.END_OFFSET,                               -- END_SECTION_OFFSET,
           RS.END_SECTION_MP,
           RS.EXCEPTIONS_DESC_XXX,
           RS.EXISTING,
           RS.FACTORED_AADT,
           RS.FACTORED_AADT_CALC_COMMENT, 
           RS.FACTOR_GROUP,
           RS.FACTOR_YEAR,
           RS.FED_AID,
           RS.FEDERAL_FUNCTIONAL_CLASS,
           RS.FEDERAL_FUNCTIONAL_CLASS_DESCR,
           RS.FEDERAL_URBAN_GROUP,
           RS.FEDERAL_URBAN_GROUP_DESCR,
           RS.FEDERAL_URBAN_RURAL,
           RS.FEDERAL_URBAN_RURAL_DESCR,
           RS.FUTURE_ADT,
           RS.FUTURE_ADT_YEAR,
           RS.GA_TYPE,
           RS.GA_TYPE_DESCR,
           RS.HASS_DESCRIPTION,
           RS.HASS_ID,
           RS.HPMS_SECTION_ID,
           RS.HPMT_COMB_AADT_PCNT,
           RS.HPMT_COMB_DHV_PCNT,
           RS.HPMT_DHV_PCNT,
           RS.HPMT_DIR_DIST,
           RS.HPMT_PASS_AADT_PCNT,
           RS.HPMT_PASS_DHV_PCNT,
           RS.HPMT_SU_AADT_PCNT,
           RS.HPMT_SU_DHV_PCNT,
           RS.HUNDRED_MILLION_VEHICLE_MILES,
           RS.IRI,
           RS.JURISDICTION,
           RS.JURISDICTION_ABBREVIATION,
           RS.JURISDICTION_CODE,
           RS.LANE_COUNT,
           RS.LANE_SURFACE_TYPE,
           RS.LANE_SURFACE_TYPE_DESCR,
           RS.LAST_TREATMENT_PSN,
           RS.LEFT_LANE_CROSSSECTION,
           RS.LEFT_RUT,
           RS.LEFT_SHOULDER_TYPE,
           RS.LEFT_SHOULDER_TYPE_DESCR,
           RS.LEFT_SHOULDER_WIDTH,
           RS.LEFT_SIDEWALK_TYPE,
           RS.LEFT_SIDEWALK_TYPE_DESCR,
           RS.LEFT_SIDEWALK_WIDTH,
           RS.LEFT_TURN_LANE_COUNT,
           RS.LEFT_TURN_LANE_WIDTH,
           RS.MAINT_RESP_WINTER,
           RS.MAINT_RESP_WINTER_DESCR,
           RS.MAINT_RESP_YEARROUND,
           RS.MAINT_RESP_YEAR_DESCR,
           RS.MEAN_SUM_DEFLECTION_CSL,
           RS.MEDIAN_AVERAGE_WIDTH,
           RS.MEDIAN_TYPE,
           RS.MEDIAN_TYPE_DESCR,
           NULL,                                                        -- MEV
           RS.MIN_PAVEMENT_WIDTH_CSL,
           RS.MIN_STRUCT_BRIDGE_COND_CSL,
           RS.MPO,
           RS.NATIONAL_TRUCK_NETWORK,
           RS.NATIONAL_TRUCK_NETWORK_DESCR,
           RS.NHFN_CONNECTOR_ID,
           RS.NHFN_SUBSYSTEM,
           RS.NHFN_SUBSYSTEM_DESCR,
           RS.NHS_STATUS,
           RS.NHS_TYPE,
           RS.NHS_TYPE_DESCR,
           NULL,                                          -- NODE_DESCRIPTION,
           NULL,                                                   -- NODE_ID,
           NULL,                                                -- NO_OF_LEGS,
           RS.LANE_COUNT,
           RS.OFFICIAL_MILES,
           RS.ONE_WAY,
           RS.ONE_WAY_DESCR,
           RS.OWNER,
           RS.OWNER_DESCR,
           RS.PAVEMENT_CONDITION_CSL,
           RS.PAVEMENT_RUTTING_CSL,
           RS.PAVEMENT_WIDTH_CSL,
           RS.PCR,
           RS.PLOW_CREW,
           RS.PMS_FILE_NAME,
           RS.PMS_INVENTORY_YEAR,
           RS.PRIMARY,
           RS.BEGIN_SECTION_MP,                            -- PRIMARY ROUTE MP
           RS.PRIMARY_ROUTE_NUMBER,
           RS.PRIORITY,
           RS.RAMP,
           RS.RAMP_DESCR,
           RS.MAINTENANCE_REGION,
           RS.MAINTENANCE_REGION_DESCR,
           RS.RIDE_QUALITY_CSL,
           RS.RIGHT_LANE_CROSSSECTION,
           RS.RIGHT_RUT,
           RS.RIGHT_SHOULDER_TYPE,
           RS.RIGHT_SHOULDER_TYPE_DESCR,
           RS.RIGHT_SHOULDER_WIDTH,
           RS.RIGHT_SIDEWALK_TYPE,
           RS.RIGHT_SIDEWALK_TYPE_DESCR,
           RS.RIGHT_SIDEWALK_WIDTH,
           RS.RIGHT_TURN_LANE_COUNT,
           RS.RIGHT_TURN_LANE_WIDTH,
           RS.ROADWAY_STRENGTH_CSL,
           RS.ROADWAY_TYPE,
           RS.ROADWAY_TYPE_DESCR,
           RS.ROAD_POSTING_CSL,
           RS.ROUTE_GROUP,
           RS.ROUTE_NAME,
           RS.ROUTE_NUMBER,
           RS.ROUTE_SYSTEM,
           RS.ROUTE_TYPE,
           RS.RUT_CSL,
           RS.SAFETY_CSL,
           RS.SCENIC_BYWAY_DESCRIPTION,
           RS.SCENIC_BYWAY_DESIG_YR,
           RS.SCENIC_BYWAY_NAME,
           RS.SCENIC_BYWAY_TYPE,
           RS.SCENIC_BYWAY_TYPE_DESCR,
           RS.SECTION_ID,
           RS.SECTION_LENGTH,
           RS.SERVICE_CSL,
           RS.SH_SA_IR_DESIGNATION,
           RS.SLD_FILE_DATE,                   
           RS.SLD_FILE_NAME,
           RS.SORTORD,
           RS.SPEED,
           RS.SPEEDSRC,
           RS.SPEEDZN_ID,
           RS.SPUR_NUMBER,
           RS.STATE_AID_NO,
           RS.STATE_DESIGNATION_NUMBER,
           RS.STATE_DESIG_TYPE,
           RS.STATE_DESIG_TYPE_DESCR,
           RS.STATE_HIGHWAY_DESIGNATION_NUMBER,
           RS.STATE_URBAN_RURAL,
           RS.STATE_URBAN_RURAL_DESCR,
           RS.STRATEGIC_HIGHWAY_NETWORK,
           RS.STRATEGIC_HIGHWAY_NETWORK_DESC,
           RS.STREET_NAME,
           RS.STREET_NAME_PREFIX,
           RS.STREET_NAME_SUFFIX,
           RS.STREETNAME,
           RS.STRUCT_BRIDGE_COND_CSL,
           RS.SUMMER_CREW,
           RS.THRU_LANE_COUNT,
           RS.THRU_LANE_WIDTH,
           RS.TOTAL_PAVEMENT_WIDTH,
           NULL,                                             -- TOWNLINE_NODE,
           RS.TOWN_CODE,
           RS.TOWN,
           NULL,                                             -- TRAFFIC_SIGNAL
           RS.TRANSPORTATION_MODE,
           RS.TRUCK_LANE_COUNT,
           RS.TRUCK_LANE_WIDTH,
           RS.TRUCK_PERCENT,
           RS.WCSH_AGREEMENT,
           RS.WCSH_CODE,
           RS.WEIGHTED_IRI_CSL,
           RS.WEIGHTED_PCR_CSL,
           RS.WIDTH,
           RS.WINTER_CREW
      FROM route_sections rs
    UNION
    SELECT DISTINCT
           'Node',
           NULL,                                                      -- AADT,
           NULL,                                               --   AADT_TYPE,
           NULL,                                         --   AADT_TYPE_DESCR,
           NULL,                                                 -- AADT_YEAR,
           NULL,                                                      --  ABN,
           NULL,                                                --  ABN_DESCR,
           NULL,                                           --  ACCESS_CONTROL,
           NULL,                                    --   ACCESS_CONTROL_DESCR,
           NULL,                                                  --   AGENCY,
           NULL,                                           --    AGENCY_DESCR,
           NULL,   -- BASE_AS_BUILT_HMA,        
           NULL,   -- BASE_GRAN_THICK,
           NULL,   -- BASE_GRAN_TYPE,
           NULL,   -- BASE_GRAN_TYPE_DESCR,
           NULL,   -- BASE_MISC_THICK,                 
           NULL,   -- BASE_MISC_TYPE,                  
           NULL,   -- BASE_MISC_TYPE_DESCR,            
           NULL,   -- BASE_MOD_TYPE,                   
           NULL,   -- BASE_MOD_TYPE_DESCR,             
           NULL,   -- BASE_MOD_YR,                     
           NULL,   -- BASE_PRI_ID_TYPE,                
           NULL,   -- BASE_PRI_ID_TYPE_DESCR,          
           NULL,   -- BASE_PRIMARY_ID,                 
           NULL,   -- BASE_PRIMARY_WIN,                
           NULL,   -- BASE_SEC_ID_TYPE,                
           NULL,   -- BASE_SEC_ID_TYPE_DESCR,          
           NULL,   -- BASE_SECOND_ID,                  
           NULL,   -- BASE_SUB_THICK,  
           CASE                         --    ROUTE_SECTIONS.BEGIN_ELEMENT_MP,
               WHEN n.NODE_ID = r.begin_node_id
               THEN
                   r.BEGIN_element_milepoint
               WHEN n.NODE_ID = r.end_node_id
               THEN
                   r.end_element_milepoint
           END,
           NULL,                                    -- BEGIN_NODE_DESCRIPTION,
           NULL,                               --ROUTE_SECTIONS.BEGIN_NODE_ID,
           NULL,                                            --   BEGIN_OFFSET,
           CASE                         --    ROUTE_SECTIONS.BEGIN_SECTION_MP,
               WHEN n.NODE_ID = r.begin_node_id
               THEN
                   r.BEGIN_element_milepoint
               WHEN n.NODE_ID = r.end_node_id
               THEN
                   r.end_element_milepoint
           END,
           NULL,                                     --    BRIDGE_POSTING_CSL,
           NULL,                                 --    BRIDGE_RELIABILITY_CSL,
           NULL,                                               --    CAPACITY,
           NULL,                                    -- CENTER_TURN_LANE_COUNT,
           NULL,                                  --   CENTER_TURN_LANE_WIDTH,
           NULL,                                          --    CONDITION_CSL,
           NULL,                                         --    CONGESTION_CSL,
           NULL,                                    --    CONGESTION_RATE_CSL,
           n.county_code1,                          --   HIGHWAYS.COUNTY_CODE,
           n.county_name1,                            -- HIGHWAYS.COUNTY_NAME,
           NULL,                                      --    CRASH_HISTORY_CSL,
           NULL,                                 --    CRASH_HISTORY_RATE_CSL,
           NULL,                                               --    CSL_YEAR,
           NULL,                             --    CUMULATIVE_MILEPOINT_ORDER,
           NULL,                                                 -- DIRECTION,
           NULL,                                     --    DIRECTIONAL_SUFFIX,
           NULL,                                               --  ELEMENT_ID,
           NULL,                                         --    ELEMENT_LENGTH,
           NULL,                                                --ELEMENT_WID,
           CASE
               WHEN n.NODE_ID = r.begin_node_id      -- END_ELEMENT_MILEPOINT,
               THEN
                   r.BEGIN_element_milepoint
               WHEN n.NODE_ID = r.end_node_id
               THEN
                   r.end_element_milepoint
           END,
           NULL,                                       -- END_NODE_DESCRIPTION
           NULL,                                               -- END_NODE_ID,
           NULL,                                        -- END_SECTION_OFFSET,
           CASE                                          --    END_SECTION_MP,
               WHEN n.NODE_ID = r.begin_node_id
               THEN
                   r.BEGIN_element_milepoint
               WHEN n.NODE_ID = r.end_node_id
               THEN
                   r.end_element_milepoint
           END,
           NULL,   -- EXCEPTIONS_DESC_XXX
           NULL,                                                 --  EXISTING,
           N.FACTORED_AADT,
           NULL,    -- FACTORED_AADT_CALC_COMMENT 
           NULL,                                        --       FACTOR_GROUP,
           NULL,                                         --       FACTOR_YEAR,
           NULL,                                         -- FED_AID,
           N.FEDERAL_FUNCTIONAL_CLASS,
           N.FEDERAL_FUNCTIONAL_CLASS_DESCR,
           N.FEDERAL_URBAN_GROUP,
           N.FEDERAL_URBAN_GROUP_DESCR,
           N.FEDERAL_URBAN_RURAL,
           N.FEDERAL_URBAN_RURAL_DESCR,
           NULL,                                                -- FUTURE_ADT,
           NULL,                                          --  FUTURE_ADT_YEAR,
           NULL,                                                    -- GA_TYPE
           NULL,                                              -- GA_TYPE_DESCR
           n.hass_descr,                                 --  HASS_DESCRIPTION,
           NULL,                                                   -- HASS_ID,
           NULL,                                           -- HPMS_SECTION_ID,
           NULL,                            --  HPMT_COMB_AADT_PCNT,
           NULL,                            --  HPMT_COMB_DHV_PCNT,
           NULL,                            --  HPMT_DHV_PCNT,
           NULL,                            --  HPMT_DIR_DIST,
           NULL,                            --  HPMT_PASS_AADT_PCNT,
           NULL,                            --  HPMT_PASS_DHV_PCNT,
           NULL,                            --  HPMT_SU_AADT_PCNT,
           NULL,                            --  HPMT_SU_DHV_PCNT,
           NULL,                            --  HUNDRED_MILLION_VEHICLE_MILES,
           NULL,                                                      --  IRI,
           N.JURISDICTION,
           NULL,                                  -- JURISDICTION_ABBREVIATION
           NULL,                                          -- JURISDICTION_CODE
           NULL,                                               --  LANE_COUNT,
           NULL,                                         --LANE_SURFACE_TYPE ,
           NULL,                                   --LANE_SURFACE_TYPE_DESCR ,
           NULL,                                    --  LAST_TREATMENT_PSN,
           NULL,                                     -- LEFT_LANE_CROSSSECTION
           NULL,                                                 --  LEFT_RUT,
           NULL,                                       --  LEFT_SHOULDER_TYPE,
           NULL,                                 --  LEFT_SHOULDER_TYPE_DESCR,
           NULL,                                      --  LEFT_SHOULDER_WIDTH,
           NULL,                                       --  left_sidewalk_type,
           NULL,                                 --  left_sidewalk_type_descr,
           NULL,                                       -- left_sidewalk_width,
           NULL,                                       -- LEFT_TURN_LANE_COUNT
           NULL,                                       -- LEFT_TURN_LANE_WIDTH
           NULL,                                        --  MAINT_RESP_WINTER,
           NULL,                                  --  MAINT_RESP_WINTER_DESCR,
           NULL,                                     --  MAINT_RESP_YEARROUND,
           NULL,                                    --  MAINT_RESP_YEAR_DESCR,
           NULL,                                  --  MEAN_SUM_DEFLECTION_CSL,
           NULL,                                     --  MEDIAN_AVERAGE_WIDTH,
           NULL,                                               -- MEDIAN_TYPE,
           NULL,                                         -- MEDIAN_TYPE_DESCR,
           N.MEV,
           NULL,                                   --  MIN_PAVEMENT_WIDTH_CSL,
           NULL,                               --  MIN_STRUCT_BRIDGE_COND_CSL,
           NULL,                                                       -- MPO,
           NULL,                                   --  NATIONAL_TRUCK_NETWORK,
           NULL,                             --  NATIONAL_TRUCK_NETWORK_DESCR,
           NULL,                             --  NHFN_CONNECTOR_ID,
           NULL,                             --  NHFN_SUBSYSTEM,
           NULL,                             --  NHFN_SUBSYSTEM_DESCR,
           N.NHS_STATUS,
           NULL,                                                  --NHS_TYPE ,
           NULL,                                           -- NHS_TYPE_DESCR ,
           N.NODE_DESCRIPTION,
           N.NODE_ID,
           N.NO_OF_LEGS,
           NULL,                                          --  NUMBER_OF_LANES,
           NULL,                                           --  OFFICIAL_MILES,
           NULL,                                                  --  ONE_WAY,
           NULL,                                            --  ONE_WAY_DESCR,
           NULL,                                                    --  OWNER,
           NULL,                                             --   OWNER_DESCR,
           NULL,                                  --   PAVEMENT_CONDITION_CSL,
           NULL,                                    --   PAVEMENT_RUTTING_CSL,
           NULL,                                      --   PAVEMENT_WIDTH_CSL,
           NULL,                                                     --   PCR,
           NULL,                                               --   PLOW_CREW,
           NULL,                                           --   PMS_FILE_NAME,
           NULL,                                      --   PMS_INVENTORY_YEAR,
           NULL,                                                --   .PRIMARY,
           N.PRIMARY_ROUTE_MP,
           N.PRIMARY_ROUTE_NUM,
           N.PRIORITY,
           NULL,                                                    --   RAMP,
           NULL,                                              --   RAMP_DESCR,
           TO_CHAR (n.region1),                                  --    REGION,
           n.region_name1,                                --     REGION_DESCR,
           NULL,                                        --   RIDE_QUALITY_CSL,
           NULL,                                   -- RIGHT_LANE_CROSSSECTION,
           NULL,                                              --    RIGHT_RUT,
           NULL,                                   --     RIGHT_SHOULDER_TYPE,
           NULL,                             --     RIGHT_SHOULDER_TYPE_DESCR,
           NULL,                                  --     RIGHT_SHOULDER_WIDTH,
           NULL,                                    --    RIGHT_SIDEWALK_TYPE,
           NULL,                                 -- RIGHT_SIDEWALK_TYPE_DESCR,
           NULL,                                      -- RIGHT_SIDEWALK_WIDTH,
           NULL,                                     -- RIGHT_TURN_LANE_COUNT,
           NULL,                                     -- RIGHT_TURN_LANE_WIDTH,
           NULL,                                    --   ROADWAY_STRENGTH_CSL,
           NULL,                                          --     ROADWAY_TYPE,
           NULL,                                   --      ROADWAY_TYPE_DESCR,
           NULL,                                     --      ROAD_POSTING_CSL,
           r.route_group,
           R.ROUTE_NAME,
           R.ROUTE_NUMBER,
           r.route_system,                                    -- route_system,
           r.route_type,
           NULL,                                                --    RUT_CSL,
           NULL,                                             --    SAFETY_CSL,
           NULL,                               --    SCENIC_BYWAY_DESCRIPTION,
           NULL,                                  --    SCENIC_BYWAY_DESIG_YR,
           NULL,                                       --   SCENIC_BYWAY_NAME,
           NULL,                                       --   SCENIC_BYWAY_TYPE,
           NULL,                                --    SCENIC_BYWAY_TYPE_DESCR,
           NULL,                                               --  SECTION_ID,
           NULL,                                         --    SECTION_LENGTH,
           NULL,                                            --    SERVICE_CSL,
           NULL,                                      -- SH_SA_IR_DESIGNATION,
           NULL,    -- SLD_FILE_DATE, 
           NULL,    -- SLD_FILE_NAME,
           R.SORTORD,                                               -- SORTORD
           NULL,                                               --       SPEED,
           NULL,                                                   --SPEEDSRC,
           NULL,                                                 --SPEEDZN_ID,
           NULL,                                              --  SPUR_NUMBER,
           NULL,                                               -- STATE_AID_NO
           NULL,                                 --  STATE_DESIGNATION_NUMBER,
           NULL,                                       --    STATE_DESIG_TYPE,
           NULL,                                 --    STATE_DESIG_TYPE_DESCR,
           NULL,                           -- STATE_HIGHWAY_DESIGNATION_NUMBER
           N.STATE_URBAN_RURAL,
           N.STATE_URBAN_RURAL_DESCR,
           NULL,                                -- STRATEGIC_HIGHWAY_NETWORK ,
           NULL,                           -- STRATEGIC_HIGHWAY_NETWORK_DESC ,
           NULL,                                           --     STREET_NAME,
           NULL,                                    --     STREET_NAME_PREFIX,
           NULL,                                    --     STREET_NAME_SUFFIX,
           NULL,                                               --  STREETNAME,
           NULL,                                --     STRUCT_BRIDGE_COND_CSL,
           NULL,                                           --     SUMMER_CREW,
           NULL,                                       --     THRU_LANE_COUNT,
           NULL,                                          --  THRU_LANE_WIDTH,
           NULL,                                --       TOTAL_PAVEMENT_WIDTH,
           N.TOWNLINE_NODE,
           n.town_code1,                                         -- TOWN_CODE,
           n.town_name1,                                             --  TOWN,
           N.TRAFFIC_SIGNAL,
           R.TRANSPORTATION_MODE,
           NULL,                                       --    TRUCK_LANE_COUNT,
           NULL,                                           --TRUCK_LANE_WIDTH,
           NULL,                                        --      TRUCK_PERCENT,
           NULL,                                         --    WCSH_AGREEMENT,
           NULL,                                                 -- WCSH_CODE,
           NULL,                                     --      WEIGHTED_IRI_CSL,
           NULL,                                     --      WEIGHTED_PCR_CSL,
           NULL,                                                --      WIDTH,
           NULL                                           --      WINTER_CREW,
      FROM nodes  N
           JOIN routes r
               ON (   (n.node_id = r.begin_node_id)
                   OR (n.node_id = r.end_node_id));
