CREATE OR REPLACE VIEW WH_ASSETS.V_DTGISP_E911_PRIVATE
BEQUEATH DEFINER
AS 
SELECT RDNAME, TOWN, LCITY, LCOUNTY, RCITY,RCOUNTY, MAP_LABEL, ROUND(FEET / 5280, 3) AS MILES, DATE_MOD
from E911_PRIVATE@GIS;
