CREATE OR REPLACE VIEW WH_ASSETS.V_FFC_CHANGE_YEAROVER
BEQUEATH DEFINER
AS 
(SELECT t.ROUTE_NUMBER, t.COLUMN7 ROUTE_NAME, t.BEGIN_SECTION_MP SECTION_BMP,
            t.END_SECTION_MP SECTION_EMP, t.COLUMN1 FFC, t.COLUMN2 STREETNAME,
            t.COLUMN3 TOWN, t.COLUMN4 AGENCY, t.COLUMN5 MAINT_RESP_YEAR_DESCR,
            t.END_SECTION_MP - t.BEGIN_SECTION_MP MILES, t.COLUMN6 * (t.END_SECTION_MP - t.BEGIN_SECTION_MP) LANE_MILES,
            t.SNAPSHOT_YEAR
       FROM TABLE (
                WH_ASSETS.PKG_DISSOLVE.F_DISSOLVE_ROUTE (
                    'SNAPSHOT_YEAR = F_Get_Snapshot_Year AND ROUTE_TYPE IN (''N'', ''I'') 
                         AND TRANSPORTATION_MODE = ''HIGHWAY''',
                    'FEDERAL_FUNCTIONAL_CLASS_DESCR, STREETNAME, TOWN_NAME, AGENCY, MAINT_RESP_YEAR_DESCR, LANE_COUNT, ROUTE_NAME'))
            t
     UNION
     SELECT p.ROUTE_NUMBER, p.COLUMN7 ROUTE_NAME, p.BEGIN_SECTION_MP SECTION_BMP,
            p.END_SECTION_MP SECTION_EMP, p.COLUMN1 FFC, p.COLUMN2 STREETNAME,
            p.COLUMN3 TOWN, p.COLUMN4 AGENCY, p.COLUMN5 MAINT_RESP_YEAR_DESCR, 
            p.END_SECTION_MP - p.BEGIN_SECTION_MP MILES, p.COLUMN6 * (p.END_SECTION_MP - p.BEGIN_SECTION_MP) LANE_MILES,
            p.SNAPSHOT_YEAR
       FROM TABLE (
                WH_ASSETS.PKG_DISSOLVE.F_DISSOLVE_ROUTE (
                    'SNAPSHOT_YEAR = F_Get_Snapshot_Year - 1 AND ROUTE_TYPE IN (''N'', ''I'') 
                         AND TRANSPORTATION_MODE = ''HIGHWAY'' ',
                    'FEDERAL_FUNCTIONAL_CLASS_DESCR, STREETNAME, TOWN_NAME, AGENCY, MAINT_RESP_YEAR_DESCR, LANE_COUNT, ROUTE_NAME'))
            p)
    ORDER BY ROUTE_NUMBER, SECTION_BMP, FFC;
