CREATE OR REPLACE VIEW WH_ASSETS.V_HSIS_CRASH_HISTORIC
BEQUEATH DEFINER
AS 
WITH
        hsiscrashes
        AS
            (
            SELECT a.MDOTID,
                    a.PRIMARY_ROUTE_NAME,
                    a.PRIMARY_ROUTE_NUMBER,
                    a.PRIMARY_ROUTE_MP,
                    a.AADT,
                    a.ACCIDENT_DATE,
                    a.ACCIDENT_DAY_OF_WEEK,
                    a.ACCIDENT_DAY_OF_WEEK_NUM,
                    a.ACCIDENT_HOUR,
                    a.ACCIDENT_MONTH_NAME,
                    a.ACCIDENT_MONTH_NUM,
                    a.ACCIDENT_TIME,
                    a.BEGIN_ELEMENT_MILEPOINT,
                    a.BEGIN_SECTION_MP,
                    a.BEGIN_SECTION_OFFSET,
                    a.CAPACITY,
                    a.CONTRIB_CIRC_ENV1,
                    a.CONTRIB_CIRC_ENV1_DESCR,
                    a.CONTRIB_CIRC_ENV2,
                    a.CONTRIB_CIRC_ENV2_DESCR,
                    a.CONTRIB_CIRC_ROAD1,
                    a.CONTRIB_CIRC_ROAD1_DESCR,
                    a.CONTRIB_CIRC_ROAD2,
                    a.CONTRIB_CIRC_ROAD2_DESCR,
                    a.COUNTY_CODE,
                    a.COUNTY_NAME,
                    a.DIRECTIONAL_SUFFIX,
                    a.ELEMENT_ID,
                    a.ELEMENT_LENGTH,
                    a.ELEMENT_WID,
                    a.END_ELEMENT_MILEPOINT,
                    a.END_SECTION_MP,
                    a.END_SECTION_OFFSET,
                    a.EXISTING,
                    a.FACTOR_YEAR,
                    a.FACTORED_AADT,
                    a.FEDERAL_FUNCTIONAL_CLASS,
                    a.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                    a.FEDERAL_URBAN_GROUP,
                    a.FEDERAL_URBAN_GROUP_DESCR,
                    a.FUTURE_ADT,
                    a.FUTURE_ADT_YEAR,
                    a.HASS_DESCRIPTION,
                    a.HUNDRED_MILLION_VEHICLE_MILES,
                    a.INJURY_COUNT,
                    a.INJURY_LEVEL,
                    a.INJURY_LEVEL_CODE,
                    a.JURISDICTION,
                    a.LANE_COUNT,
                    a.LATITUDE,
                    a.LONGITUDE,
                    a.LEFT_SHOULDER_TYPE,
                    a.LEFT_SHOULDER_TYPE_DESCR,
                    a.LEFT_SHOULDER_WIDTH,
                    a.LIGHT_CONDITION,
                    a.LIGHT_CONDITION_DESCR,
                    a.LOC_FIRST_HARMFUL_EVENT,
                    a.LOC_FIRST_HARMFUL_EVENT_DESCR,
                    a.LOCATION_TYPE,
                    a.MEDIAN_AVERAGE_WIDTH,
                    a.MEDIAN_TYPE,
                    a.MEDIAN_TYPE_DESCR,
                    a.MEV                                 AS CRASHES_ON_ROUTE_MEV,
                    a.NATIONAL_TRUCK_NETWORK,
                    a.NATIONAL_TRUCK_NETWORK_DESCR,
                    a.NHS_STATUS,
                    a.NO_OF_A_INJ,
                    a.NO_OF_B_INJ,
                    a.NO_OF_C_INJ,
                    a.NO_OF_K_INJ,
                    a.NO_OF_NON_INJ,
                    a.NODE_ID                             AS COR_NODE_ID,
                    a.NUMBER_OF_LANES,
                    a.OFFSET,
                    a.ONE_WAY,
                    a.ONE_WAY_DESCR,
                    a.RAMP,
                    a.RAMP_DESCR,
                    a.REGION_CODE,
                    a.REGION_NAME,
                    a.REPORT_NUMBER,
                    a.REPORTING_AGENCY,
                    a.REPORTING_AGENCY_DESCR,
                    a.RIGHT_SHOULDER_TYPE,
                    a.RIGHT_SHOULDER_TYPE_DESCR,
                    a.RIGHT_SHOULDER_WIDTH,
                    a.ROAD_GRADE,
                    a.ROAD_GRADE_DESCR,
                    a.ROAD_SURF_COND,
                    a.ROAD_SURF_COND_DESCR,
                    a.ROADWAY_TYPE,
                    a.ROUTE_NAME,
                    a.ROUTE_NUMBER,
                    a.ROUTE_SYSTEM,
                    a.SCENIC_BYWAY_DESCRIPTION,
                    a.SCENIC_BYWAY_DESIG_YR,
                    a.SCENIC_BYWAY_NAME,
                    a.SCENIC_BYWAY_TYPE,
                    a.SCENIC_BYWAY_TYPE_DESCR,
                    a.SCHOOL_BUS_RELATED,
                    a.SCHOOL_BUS_RELATED_DESCR,
                    a.SECTION_ID,
                    a.SECTION_LENGTH,
                    a.SPEED,
                    a.SPEED_LIMIT,
                    a.STATE_DESIG_TYPE,
                    a.STATE_DESIG_TYPE_DESCR,
                    a.STATE_URBAN_RURAL,
                    a.STATE_URBAN_RURAL_DESCR,
                    a.STREET_NAME,
                    a.STREET_NAME_PREFIX,
                    a.STREET_NAME_SUFFIX,
                    a.TOTAL_PAVEMENT_WIDTH,
                    a.TOWN_CODE,
                    a.TOWN_NAME,
                    a.TRAFFIC_CONTROL_DEVICE,
                    a.TRAFFIC_CONTROL_DEVICE_DESCR,
                    a.TRF_CNTRL_DEV_OPRATIONL,
                    a.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                    a.TRUCK_PERCENT,
                    a.TYPE_OF_CRASH,
                    a.TYPE_OF_CRASH_DESCR,
                    a.TYPE_OF_LOCATION,
                    a.TYPE_OF_LOCATION_DESCR,
                    a.WEATHER_CONDITION,
                    a.WEATHER_CONDITION_DESCR,
                    a.WIDTH,
                    a.WORKZONE_IN_OR_NEAR,
                    a.WORKZONE_IN_OR_NEAR_DESCR,
                    a.WORKZONE_LOCATION,
                    a.WORKZONE_LOCATION_DESCR,
                    a.WORKZONE_POLICE_PRESENT,
                    a.WORKZONE_POLICE_PRESENT_DESCR,
                    a.WORKZONE_TYPE,
                    a.WORKZONE_TYPE_DESCR,
                    a.WORKZONE_WORKERS_PRESENT,
                    a.WORKZONE_WORKERS_PRESENT_DESCR,
                    nodes.MEV                             AS NODES_MEV,
                    nodes.NODE_ID                         AS NODES_NODE_ID,
                    nodes.NO_OF_LEGS                      AS nodes_no_of_legs,
                    nodes.NODE_DESCRIPTION                AS nodes_node_description,
                    nodes.TOWN_CODE1                      AS nodes_town_code1,
                    nodes.TOWN_CODE2                      AS nodes_town_code2,
                    nodes.TOWN_NAME1                      AS nodes_town_name1,
                    nodes.TOWN_NAME2                      AS nodes_town_name2,
                    nodes.TOWNLINE_NODE                   AS nodes_townline_node,
                    nodes.TRAFFIC_SIGNAL                  AS nodes_traffic_signal,
                    2024                                  AS CRASH_SUBSET,
                    EXTRACT (YEAR FROM accident_date)     AS accident_year
               FROM CRASHES_ON_ROUTE_2024  a
                    LEFT OUTER JOIN NODES_history nodes
                        ON     a.NODE_ID = NODES.NODE_ID
                           AND nodes.snapshot_year = 2024
                           AND nodes.state = 'PAST'
              WHERE     a.ROUTE_NUMBER = a.PRIMARY_ROUTE_NUMBER
                    AND EXTRACT (YEAR FROM accident_date) = 2024
            UNION ALL
            SELECT a.MDOTID,
                    a.PRIMARY_ROUTE_NAME,
                    a.PRIMARY_ROUTE_NUMBER,
                    a.PRIMARY_ROUTE_MP,
                    a.AADT,
                    a.ACCIDENT_DATE,
                    a.ACCIDENT_DAY_OF_WEEK,
                    a.ACCIDENT_DAY_OF_WEEK_NUM,
                    a.ACCIDENT_HOUR,
                    a.ACCIDENT_MONTH_NAME,
                    a.ACCIDENT_MONTH_NUM,
                    a.ACCIDENT_TIME,
                    a.BEGIN_ELEMENT_MILEPOINT,
                    a.BEGIN_SECTION_MP,
                    a.BEGIN_SECTION_OFFSET,
                    a.CAPACITY,
                    a.CONTRIB_CIRC_ENV1,
                    a.CONTRIB_CIRC_ENV1_DESCR,
                    a.CONTRIB_CIRC_ENV2,
                    a.CONTRIB_CIRC_ENV2_DESCR,
                    a.CONTRIB_CIRC_ROAD1,
                    a.CONTRIB_CIRC_ROAD1_DESCR,
                    a.CONTRIB_CIRC_ROAD2,
                    a.CONTRIB_CIRC_ROAD2_DESCR,
                    a.COUNTY_CODE,
                    a.COUNTY_NAME,
                    a.DIRECTIONAL_SUFFIX,
                    a.ELEMENT_ID,
                    a.ELEMENT_LENGTH,
                    a.ELEMENT_WID,
                    a.END_ELEMENT_MILEPOINT,
                    a.END_SECTION_MP,
                    a.END_SECTION_OFFSET,
                    a.EXISTING,
                    a.FACTOR_YEAR,
                    a.FACTORED_AADT,
                    a.FEDERAL_FUNCTIONAL_CLASS,
                    a.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                    a.FEDERAL_URBAN_GROUP,
                    a.FEDERAL_URBAN_GROUP_DESCR,
                    a.FUTURE_ADT,
                    a.FUTURE_ADT_YEAR,
                    a.HASS_DESCRIPTION,
                    a.HUNDRED_MILLION_VEHICLE_MILES,
                    a.INJURY_COUNT,
                    a.INJURY_LEVEL,
                    a.INJURY_LEVEL_CODE,
                    a.JURISDICTION,
                    a.LANE_COUNT,
                    a.LATITUDE,
                    a.LONGITUDE,
                    a.LEFT_SHOULDER_TYPE,
                    a.LEFT_SHOULDER_TYPE_DESCR,
                    a.LEFT_SHOULDER_WIDTH,
                    a.LIGHT_CONDITION,
                    a.LIGHT_CONDITION_DESCR,
                    a.LOC_FIRST_HARMFUL_EVENT,
                    a.LOC_FIRST_HARMFUL_EVENT_DESCR,
                    a.LOCATION_TYPE,
                    a.MEDIAN_AVERAGE_WIDTH,
                    a.MEDIAN_TYPE,
                    a.MEDIAN_TYPE_DESCR,
                    a.MEV                                 AS CRASHES_ON_ROUTE_MEV,
                    a.NATIONAL_TRUCK_NETWORK,
                    a.NATIONAL_TRUCK_NETWORK_DESCR,
                    a.NHS_STATUS,
                    a.NO_OF_A_INJ,
                    a.NO_OF_B_INJ,
                    a.NO_OF_C_INJ,
                    a.NO_OF_K_INJ,
                    a.NO_OF_NON_INJ,
                    a.NODE_ID                             AS COR_NODE_ID,
                    a.NUMBER_OF_LANES,
                    a.OFFSET,
                    a.ONE_WAY,
                    a.ONE_WAY_DESCR,
                    a.RAMP,
                    a.RAMP_DESCR,
                    a.REGION_CODE,
                    a.REGION_NAME,
                    a.REPORT_NUMBER,
                    a.REPORTING_AGENCY,
                    a.REPORTING_AGENCY_DESCR,
                    a.RIGHT_SHOULDER_TYPE,
                    a.RIGHT_SHOULDER_TYPE_DESCR,
                    a.RIGHT_SHOULDER_WIDTH,
                    a.ROAD_GRADE,
                    a.ROAD_GRADE_DESCR,
                    a.ROAD_SURF_COND,
                    a.ROAD_SURF_COND_DESCR,
                    a.ROADWAY_TYPE,
                    a.ROUTE_NAME,
                    a.ROUTE_NUMBER,
                    a.ROUTE_SYSTEM,
                    a.SCENIC_BYWAY_DESCRIPTION,
                    a.SCENIC_BYWAY_DESIG_YR,
                    a.SCENIC_BYWAY_NAME,
                    a.SCENIC_BYWAY_TYPE,
                    a.SCENIC_BYWAY_TYPE_DESCR,
                    a.SCHOOL_BUS_RELATED,
                    a.SCHOOL_BUS_RELATED_DESCR,
                    a.SECTION_ID,
                    a.SECTION_LENGTH,
                    a.SPEED,
                    a.SPEED_LIMIT,
                    a.STATE_DESIG_TYPE,
                    a.STATE_DESIG_TYPE_DESCR,
                    a.STATE_URBAN_RURAL,
                    a.STATE_URBAN_RURAL_DESCR,
                    a.STREET_NAME,
                    a.STREET_NAME_PREFIX,
                    a.STREET_NAME_SUFFIX,
                    a.TOTAL_PAVEMENT_WIDTH,
                    a.TOWN_CODE,
                    a.TOWN_NAME,
                    a.TRAFFIC_CONTROL_DEVICE,
                    a.TRAFFIC_CONTROL_DEVICE_DESCR,
                    a.TRF_CNTRL_DEV_OPRATIONL,
                    a.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                    a.TRUCK_PERCENT,
                    a.TYPE_OF_CRASH,
                    a.TYPE_OF_CRASH_DESCR,
                    a.TYPE_OF_LOCATION,
                    a.TYPE_OF_LOCATION_DESCR,
                    a.WEATHER_CONDITION,
                    a.WEATHER_CONDITION_DESCR,
                    a.WIDTH,
                    a.WORKZONE_IN_OR_NEAR,
                    a.WORKZONE_IN_OR_NEAR_DESCR,
                    a.WORKZONE_LOCATION,
                    a.WORKZONE_LOCATION_DESCR,
                    a.WORKZONE_POLICE_PRESENT,
                    a.WORKZONE_POLICE_PRESENT_DESCR,
                    a.WORKZONE_TYPE,
                    a.WORKZONE_TYPE_DESCR,
                    a.WORKZONE_WORKERS_PRESENT,
                    a.WORKZONE_WORKERS_PRESENT_DESCR,
                    nodes.MEV                             AS NODES_MEV,
                    nodes.NODE_ID                         AS NODES_NODE_ID,
                    nodes.NO_OF_LEGS                      AS nodes_no_of_legs,
                    nodes.NODE_DESCRIPTION                AS nodes_node_description,
                    nodes.TOWN_CODE1                      AS nodes_town_code1,
                    nodes.TOWN_CODE2                      AS nodes_town_code2,
                    nodes.TOWN_NAME1                      AS nodes_town_name1,
                    nodes.TOWN_NAME2                      AS nodes_town_name2,
                    nodes.TOWNLINE_NODE                   AS nodes_townline_node,
                    nodes.TRAFFIC_SIGNAL                  AS nodes_traffic_signal,
                    2023                                  AS CRASH_SUBSET,
                    EXTRACT (YEAR FROM accident_date)     AS accident_year
               FROM CRASHES_ON_ROUTE_2023  a
                    LEFT OUTER JOIN NODES_history nodes
                        ON     a.NODE_ID = NODES.NODE_ID
                           AND nodes.snapshot_year = 2023
                           AND nodes.state = 'PAST'
              WHERE     a.ROUTE_NUMBER = a.PRIMARY_ROUTE_NUMBER
                    AND EXTRACT (YEAR FROM accident_date) = 2023
            UNION ALL
            SELECT a.MDOTID,
                    a.PRIMARY_ROUTE_NAME,
                    a.PRIMARY_ROUTE_NUMBER,
                    a.PRIMARY_ROUTE_MP,
                    a.AADT,
                    a.ACCIDENT_DATE,
                    a.ACCIDENT_DAY_OF_WEEK,
                    a.ACCIDENT_DAY_OF_WEEK_NUM,
                    a.ACCIDENT_HOUR,
                    a.ACCIDENT_MONTH_NAME,
                    a.ACCIDENT_MONTH_NUM,
                    a.ACCIDENT_TIME,
                    a.BEGIN_ELEMENT_MILEPOINT,
                    a.BEGIN_SECTION_MP,
                    a.BEGIN_SECTION_OFFSET,
                    a.CAPACITY,
                    a.CONTRIB_CIRC_ENV1,
                    a.CONTRIB_CIRC_ENV1_DESCR,
                    a.CONTRIB_CIRC_ENV2,
                    a.CONTRIB_CIRC_ENV2_DESCR,
                    a.CONTRIB_CIRC_ROAD1,
                    a.CONTRIB_CIRC_ROAD1_DESCR,
                    a.CONTRIB_CIRC_ROAD2,
                    a.CONTRIB_CIRC_ROAD2_DESCR,
                    a.COUNTY_CODE,
                    a.COUNTY_NAME,
                    a.DIRECTIONAL_SUFFIX,
                    a.ELEMENT_ID,
                    a.ELEMENT_LENGTH,
                    a.ELEMENT_WID,
                    a.END_ELEMENT_MILEPOINT,
                    a.END_SECTION_MP,
                    a.END_SECTION_OFFSET,
                    a.EXISTING,
                    a.FACTOR_YEAR,
                    a.FACTORED_AADT,
                    a.FEDERAL_FUNCTIONAL_CLASS,
                    a.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                    a.FEDERAL_URBAN_GROUP,
                    a.FEDERAL_URBAN_GROUP_DESCR,
                    a.FUTURE_ADT,
                    a.FUTURE_ADT_YEAR,
                    a.HASS_DESCRIPTION,
                    a.HUNDRED_MILLION_VEHICLE_MILES,
                    a.INJURY_COUNT,
                    a.INJURY_LEVEL,
                    a.INJURY_LEVEL_CODE,
                    a.JURISDICTION,
                    a.LANE_COUNT,
                    a.LATITUDE,
                    a.LONGITUDE,
                    a.LEFT_SHOULDER_TYPE,
                    a.LEFT_SHOULDER_TYPE_DESCR,
                    a.LEFT_SHOULDER_WIDTH,
                    a.LIGHT_CONDITION,
                    a.LIGHT_CONDITION_DESCR,
                    a.LOC_FIRST_HARMFUL_EVENT,
                    a.LOC_FIRST_HARMFUL_EVENT_DESCR,
                    a.LOCATION_TYPE,
                    a.MEDIAN_AVERAGE_WIDTH,
                    a.MEDIAN_TYPE,
                    a.MEDIAN_TYPE_DESCR,
                    a.MEV                                 AS CRASHES_ON_ROUTE_MEV,
                    a.NATIONAL_TRUCK_NETWORK,
                    a.NATIONAL_TRUCK_NETWORK_DESCR,
                    a.NHS_STATUS,
                    a.NO_OF_A_INJ,
                    a.NO_OF_B_INJ,
                    a.NO_OF_C_INJ,
                    a.NO_OF_K_INJ,
                    a.NO_OF_NON_INJ,
                    a.NODE_ID                             AS COR_NODE_ID,
                    a.NUMBER_OF_LANES,
                    a.OFFSET,
                    a.ONE_WAY,
                    a.ONE_WAY_DESCR,
                    a.RAMP,
                    a.RAMP_DESCR,
                    a.REGION_CODE,
                    a.REGION_NAME,
                    a.REPORT_NUMBER,
                    a.REPORTING_AGENCY,
                    a.REPORTING_AGENCY_DESCR,
                    a.RIGHT_SHOULDER_TYPE,
                    a.RIGHT_SHOULDER_TYPE_DESCR,
                    a.RIGHT_SHOULDER_WIDTH,
                    a.ROAD_GRADE,
                    a.ROAD_GRADE_DESCR,
                    a.ROAD_SURF_COND,
                    a.ROAD_SURF_COND_DESCR,
                    a.ROADWAY_TYPE,
                    a.ROUTE_NAME,
                    a.ROUTE_NUMBER,
                    a.ROUTE_SYSTEM,
                    a.SCENIC_BYWAY_DESCRIPTION,
                    a.SCENIC_BYWAY_DESIG_YR,
                    a.SCENIC_BYWAY_NAME,
                    a.SCENIC_BYWAY_TYPE,
                    a.SCENIC_BYWAY_TYPE_DESCR,
                    a.SCHOOL_BUS_RELATED,
                    a.SCHOOL_BUS_RELATED_DESCR,
                    a.SECTION_ID,
                    a.SECTION_LENGTH,
                    a.SPEED,
                    a.SPEED_LIMIT,
                    a.STATE_DESIG_TYPE,
                    a.STATE_DESIG_TYPE_DESCR,
                    a.STATE_URBAN_RURAL,
                    a.STATE_URBAN_RURAL_DESCR,
                    a.STREET_NAME,
                    a.STREET_NAME_PREFIX,
                    a.STREET_NAME_SUFFIX,
                    a.TOTAL_PAVEMENT_WIDTH,
                    a.TOWN_CODE,
                    a.TOWN_NAME,
                    a.TRAFFIC_CONTROL_DEVICE,
                    a.TRAFFIC_CONTROL_DEVICE_DESCR,
                    a.TRF_CNTRL_DEV_OPRATIONL,
                    a.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                    a.TRUCK_PERCENT,
                    a.TYPE_OF_CRASH,
                    a.TYPE_OF_CRASH_DESCR,
                    a.TYPE_OF_LOCATION,
                    a.TYPE_OF_LOCATION_DESCR,
                    a.WEATHER_CONDITION,
                    a.WEATHER_CONDITION_DESCR,
                    a.WIDTH,
                    a.WORKZONE_IN_OR_NEAR,
                    a.WORKZONE_IN_OR_NEAR_DESCR,
                    a.WORKZONE_LOCATION,
                    a.WORKZONE_LOCATION_DESCR,
                    a.WORKZONE_POLICE_PRESENT,
                    a.WORKZONE_POLICE_PRESENT_DESCR,
                    a.WORKZONE_TYPE,
                    a.WORKZONE_TYPE_DESCR,
                    a.WORKZONE_WORKERS_PRESENT,
                    a.WORKZONE_WORKERS_PRESENT_DESCR,
                    nodes.MEV                             AS NODES_MEV,
                    nodes.NODE_ID                         AS NODES_NODE_ID,
                    nodes.NO_OF_LEGS                      AS nodes_no_of_legs,
                    nodes.NODE_DESCRIPTION                AS nodes_node_description,
                    nodes.TOWN_CODE1                      AS nodes_town_code1,
                    nodes.TOWN_CODE2                      AS nodes_town_code2,
                    nodes.TOWN_NAME1                      AS nodes_town_name1,
                    nodes.TOWN_NAME2                      AS nodes_town_name2,
                    nodes.TOWNLINE_NODE                   AS nodes_townline_node,
                    nodes.TRAFFIC_SIGNAL                  AS nodes_traffic_signal,
                    2022                                  AS CRASH_SUBSET,
                    EXTRACT (YEAR FROM accident_date)     AS accident_year
               FROM CRASHES_ON_ROUTE_2022  a
                    LEFT OUTER JOIN NODES_history nodes
                        ON     a.NODE_ID = NODES.NODE_ID
                           AND nodes.snapshot_year = 2022
                           AND nodes.state = 'PAST'
              WHERE     a.ROUTE_NUMBER = a.PRIMARY_ROUTE_NUMBER
                    AND EXTRACT (YEAR FROM accident_date) = 2022
            UNION ALL
            SELECT a.MDOTID,
                    a.PRIMARY_ROUTE_NAME,
                    a.PRIMARY_ROUTE_NUMBER,
                    a.PRIMARY_ROUTE_MP,
                    a.AADT,
                    a.ACCIDENT_DATE,
                    a.ACCIDENT_DAY_OF_WEEK,
                    a.ACCIDENT_DAY_OF_WEEK_NUM,
                    a.ACCIDENT_HOUR,
                    a.ACCIDENT_MONTH_NAME,
                    a.ACCIDENT_MONTH_NUM,
                    a.ACCIDENT_TIME,
                    a.BEGIN_ELEMENT_MILEPOINT,
                    a.BEGIN_SECTION_MP,
                    a.BEGIN_SECTION_OFFSET,
                    a.CAPACITY,
                    a.CONTRIB_CIRC_ENV1,
                    a.CONTRIB_CIRC_ENV1_DESCR,
                    a.CONTRIB_CIRC_ENV2,
                    a.CONTRIB_CIRC_ENV2_DESCR,
                    a.CONTRIB_CIRC_ROAD1,
                    a.CONTRIB_CIRC_ROAD1_DESCR,
                    a.CONTRIB_CIRC_ROAD2,
                    a.CONTRIB_CIRC_ROAD2_DESCR,
                    a.COUNTY_CODE,
                    a.COUNTY_NAME,
                    a.DIRECTIONAL_SUFFIX,
                    a.ELEMENT_ID,
                    a.ELEMENT_LENGTH,
                    a.ELEMENT_WID,
                    a.END_ELEMENT_MILEPOINT,
                    a.END_SECTION_MP,
                    a.END_SECTION_OFFSET,
                    a.EXISTING,
                    a.FACTOR_YEAR,
                    a.FACTORED_AADT,
                    a.FEDERAL_FUNCTIONAL_CLASS,
                    a.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                    a.FEDERAL_URBAN_GROUP,
                    a.FEDERAL_URBAN_GROUP_DESCR,
                    a.FUTURE_ADT,
                    a.FUTURE_ADT_YEAR,
                    a.HASS_DESCRIPTION,
                    a.HUNDRED_MILLION_VEHICLE_MILES,
                    a.INJURY_COUNT,
                    a.INJURY_LEVEL,
                    a.INJURY_LEVEL_CODE,
                    a.JURISDICTION,
                    a.LANE_COUNT,
                    a.LATITUDE,
                    a.LONGITUDE,
                    a.LEFT_SHOULDER_TYPE,
                    a.LEFT_SHOULDER_TYPE_DESCR,
                    a.LEFT_SHOULDER_WIDTH,
                    a.LIGHT_CONDITION,
                    a.LIGHT_CONDITION_DESCR,
                    a.LOC_FIRST_HARMFUL_EVENT,
                    a.LOC_FIRST_HARMFUL_EVENT_DESCR,
                    a.LOCATION_TYPE,
                    a.MEDIAN_AVERAGE_WIDTH,
                    a.MEDIAN_TYPE,
                    a.MEDIAN_TYPE_DESCR,
                    a.MEV                                 AS CRASHES_ON_ROUTE_MEV,
                    a.NATIONAL_TRUCK_NETWORK,
                    a.NATIONAL_TRUCK_NETWORK_DESCR,
                    a.NHS_STATUS,
                    a.NO_OF_A_INJ,
                    a.NO_OF_B_INJ,
                    a.NO_OF_C_INJ,
                    a.NO_OF_K_INJ,
                    a.NO_OF_NON_INJ,
                    a.NODE_ID                             AS COR_NODE_ID,
                    a.NUMBER_OF_LANES,
                    a.OFFSET,
                    a.ONE_WAY,
                    a.ONE_WAY_DESCR,
                    a.RAMP,
                    a.RAMP_DESCR,
                    a.REGION_CODE,
                    a.REGION_NAME,
                    a.REPORT_NUMBER,
                    a.REPORTING_AGENCY,
                    a.REPORTING_AGENCY_DESCR,
                    a.RIGHT_SHOULDER_TYPE,
                    a.RIGHT_SHOULDER_TYPE_DESCR,
                    a.RIGHT_SHOULDER_WIDTH,
                    a.ROAD_GRADE,
                    a.ROAD_GRADE_DESCR,
                    a.ROAD_SURF_COND,
                    a.ROAD_SURF_COND_DESCR,
                    a.ROADWAY_TYPE,
                    a.ROUTE_NAME,
                    a.ROUTE_NUMBER,
                    a.ROUTE_SYSTEM,
                    a.SCENIC_BYWAY_DESCRIPTION,
                    a.SCENIC_BYWAY_DESIG_YR,
                    a.SCENIC_BYWAY_NAME,
                    a.SCENIC_BYWAY_TYPE,
                    a.SCENIC_BYWAY_TYPE_DESCR,
                    a.SCHOOL_BUS_RELATED,
                    a.SCHOOL_BUS_RELATED_DESCR,
                    a.SECTION_ID,
                    a.SECTION_LENGTH,
                    a.SPEED,
                    a.SPEED_LIMIT,
                    a.STATE_DESIG_TYPE,
                    a.STATE_DESIG_TYPE_DESCR,
                    a.STATE_URBAN_RURAL,
                    a.STATE_URBAN_RURAL_DESCR,
                    a.STREET_NAME,
                    a.STREET_NAME_PREFIX,
                    a.STREET_NAME_SUFFIX,
                    a.TOTAL_PAVEMENT_WIDTH,
                    a.TOWN_CODE,
                    a.TOWN_NAME,
                    a.TRAFFIC_CONTROL_DEVICE,
                    a.TRAFFIC_CONTROL_DEVICE_DESCR,
                    a.TRF_CNTRL_DEV_OPRATIONL,
                    a.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                    a.TRUCK_PERCENT,
                    a.TYPE_OF_CRASH,
                    a.TYPE_OF_CRASH_DESCR,
                    a.TYPE_OF_LOCATION,
                    a.TYPE_OF_LOCATION_DESCR,
                    a.WEATHER_CONDITION,
                    a.WEATHER_CONDITION_DESCR,
                    a.WIDTH,
                    a.WORKZONE_IN_OR_NEAR,
                    a.WORKZONE_IN_OR_NEAR_DESCR,
                    a.WORKZONE_LOCATION,
                    a.WORKZONE_LOCATION_DESCR,
                    a.WORKZONE_POLICE_PRESENT,
                    a.WORKZONE_POLICE_PRESENT_DESCR,
                    a.WORKZONE_TYPE,
                    a.WORKZONE_TYPE_DESCR,
                    a.WORKZONE_WORKERS_PRESENT,
                    a.WORKZONE_WORKERS_PRESENT_DESCR,
                    nodes.MEV                             AS NODES_MEV,
                    nodes.NODE_ID                         AS NODES_NODE_ID,
                    nodes.NO_OF_LEGS                      AS nodes_no_of_legs,
                    nodes.NODE_DESCRIPTION                AS nodes_node_description,
                    nodes.TOWN_CODE1                      AS nodes_town_code1,
                    nodes.TOWN_CODE2                      AS nodes_town_code2,
                    nodes.TOWN_NAME1                      AS nodes_town_name1,
                    nodes.TOWN_NAME2                      AS nodes_town_name2,
                    nodes.TOWNLINE_NODE                   AS nodes_townline_node,
                    nodes.TRAFFIC_SIGNAL                  AS nodes_traffic_signal,
                    2021                                  AS CRASH_SUBSET,
                    EXTRACT (YEAR FROM accident_date)     AS accident_year
               FROM CRASHES_ON_ROUTE_2021  a
                    LEFT OUTER JOIN NODES_history nodes
                        ON     a.NODE_ID = NODES.NODE_ID
                           AND nodes.snapshot_year = 2021
                           AND nodes.state = 'PAST'
              WHERE     a.ROUTE_NUMBER = a.PRIMARY_ROUTE_NUMBER
                    AND EXTRACT (YEAR FROM accident_date) = 2021
             UNION ALL
             SELECT a.MDOTID,
                    a.PRIMARY_ROUTE_NAME,
                    a.PRIMARY_ROUTE_NUMBER,
                    a.PRIMARY_ROUTE_MP,
                    a.AADT,
                    a.ACCIDENT_DATE,
                    a.ACCIDENT_DAY_OF_WEEK,
                    a.ACCIDENT_DAY_OF_WEEK_NUM,
                    a.ACCIDENT_HOUR,
                    a.ACCIDENT_MONTH_NAME,
                    a.ACCIDENT_MONTH_NUM,
                    a.ACCIDENT_TIME,
                    a.BEGIN_ELEMENT_MILEPOINT,
                    a.BEGIN_SECTION_MP,
                    a.BEGIN_SECTION_OFFSET,
                    a.CAPACITY,
                    a.CONTRIB_CIRC_ENV1,
                    a.CONTRIB_CIRC_ENV1_DESCR,
                    a.CONTRIB_CIRC_ENV2,
                    a.CONTRIB_CIRC_ENV2_DESCR,
                    a.CONTRIB_CIRC_ROAD1,
                    a.CONTRIB_CIRC_ROAD1_DESCR,
                    a.CONTRIB_CIRC_ROAD2,
                    a.CONTRIB_CIRC_ROAD2_DESCR,
                    a.COUNTY_CODE,
                    a.COUNTY_NAME,
                    a.DIRECTIONAL_SUFFIX,
                    a.ELEMENT_ID,
                    a.ELEMENT_LENGTH,
                    a.ELEMENT_WID,
                    a.END_ELEMENT_MILEPOINT,
                    a.END_SECTION_MP,
                    a.END_SECTION_OFFSET,
                    a.EXISTING,
                    a.FACTOR_YEAR,
                    a.FACTORED_AADT,
                    a.FEDERAL_FUNCTIONAL_CLASS,
                    a.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                    a.FEDERAL_URBAN_GROUP,
                    a.FEDERAL_URBAN_GROUP_DESCR,
                    a.FUTURE_ADT,
                    a.FUTURE_ADT_YEAR,
                    a.HASS_DESCRIPTION,
                    a.HUNDRED_MILLION_VEHICLE_MILES,
                    a.INJURY_COUNT,
                    a.INJURY_LEVEL,
                    a.INJURY_LEVEL_CODE,
                    a.JURISDICTION,
                    a.LANE_COUNT,
                    a.LATITUDE,
                    a.LONGITUDE,
                    a.LEFT_SHOULDER_TYPE,
                    a.LEFT_SHOULDER_TYPE_DESCR,
                    a.LEFT_SHOULDER_WIDTH,
                    a.LIGHT_CONDITION,
                    a.LIGHT_CONDITION_DESCR,
                    a.LOC_FIRST_HARMFUL_EVENT,
                    a.LOC_FIRST_HARMFUL_EVENT_DESCR,
                    a.LOCATION_TYPE,
                    a.MEDIAN_AVERAGE_WIDTH,
                    a.MEDIAN_TYPE,
                    a.MEDIAN_TYPE_DESCR,
                    a.MEV                                 AS CRASHES_ON_ROUTE_MEV,
                    a.NATIONAL_TRUCK_NETWORK,
                    a.NATIONAL_TRUCK_NETWORK_DESCR,
                    a.NHS_STATUS,
                    a.NO_OF_A_INJ,
                    a.NO_OF_B_INJ,
                    a.NO_OF_C_INJ,
                    a.NO_OF_K_INJ,
                    a.NO_OF_NON_INJ,
                    a.NODE_ID                             AS COR_NODE_ID,
                    a.NUMBER_OF_LANES,
                    a.OFFSET,
                    a.ONE_WAY,
                    a.ONE_WAY_DESCR,
                    a.RAMP,
                    a.RAMP_DESCR,
                    a.REGION_CODE,
                    a.REGION_NAME,
                    a.REPORT_NUMBER,
                    a.REPORTING_AGENCY,
                    a.REPORTING_AGENCY_DESCR,
                    a.RIGHT_SHOULDER_TYPE,
                    a.RIGHT_SHOULDER_TYPE_DESCR,
                    a.RIGHT_SHOULDER_WIDTH,
                    a.ROAD_GRADE,
                    a.ROAD_GRADE_DESCR,
                    a.ROAD_SURF_COND,
                    a.ROAD_SURF_COND_DESCR,
                    a.ROADWAY_TYPE,
                    a.ROUTE_NAME,
                    a.ROUTE_NUMBER,
                    a.ROUTE_SYSTEM,
                    a.SCENIC_BYWAY_DESCRIPTION,
                    a.SCENIC_BYWAY_DESIG_YR,
                    a.SCENIC_BYWAY_NAME,
                    a.SCENIC_BYWAY_TYPE,
                    a.SCENIC_BYWAY_TYPE_DESCR,
                    a.SCHOOL_BUS_RELATED,
                    a.SCHOOL_BUS_RELATED_DESCR,
                    a.SECTION_ID,
                    a.SECTION_LENGTH,
                    a.SPEED,
                    a.SPEED_LIMIT,
                    a.STATE_DESIG_TYPE,
                    a.STATE_DESIG_TYPE_DESCR,
                    a.STATE_URBAN_RURAL,
                    a.STATE_URBAN_RURAL_DESCR,
                    a.STREET_NAME,
                    a.STREET_NAME_PREFIX,
                    a.STREET_NAME_SUFFIX,
                    a.TOTAL_PAVEMENT_WIDTH,
                    a.TOWN_CODE,
                    a.TOWN_NAME,
                    a.TRAFFIC_CONTROL_DEVICE,
                    a.TRAFFIC_CONTROL_DEVICE_DESCR,
                    a.TRF_CNTRL_DEV_OPRATIONL,
                    a.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                    a.TRUCK_PERCENT,
                    a.TYPE_OF_CRASH,
                    a.TYPE_OF_CRASH_DESCR,
                    a.TYPE_OF_LOCATION,
                    a.TYPE_OF_LOCATION_DESCR,
                    a.WEATHER_CONDITION,
                    a.WEATHER_CONDITION_DESCR,
                    a.WIDTH,
                    a.WORKZONE_IN_OR_NEAR,
                    a.WORKZONE_IN_OR_NEAR_DESCR,
                    a.WORKZONE_LOCATION,
                    a.WORKZONE_LOCATION_DESCR,
                    a.WORKZONE_POLICE_PRESENT,
                    a.WORKZONE_POLICE_PRESENT_DESCR,
                    a.WORKZONE_TYPE,
                    a.WORKZONE_TYPE_DESCR,
                    a.WORKZONE_WORKERS_PRESENT,
                    a.WORKZONE_WORKERS_PRESENT_DESCR,
                    nodes.MEV                             AS NODES_MEV,
                    nodes.NODE_ID                         AS NODES_NODE_ID,
                    nodes.NO_OF_LEGS                      AS nodes_no_of_legs,
                    nodes.NODE_DESCRIPTION                AS nodes_node_description,
                    nodes.TOWN_CODE1                      AS nodes_town_code1,
                    nodes.TOWN_CODE2                      AS nodes_town_code2,
                    nodes.TOWN_NAME1                      AS nodes_town_name1,
                    nodes.TOWN_NAME2                      AS nodes_town_name2,
                    nodes.TOWNLINE_NODE                   AS nodes_townline_node,
                    nodes.TRAFFIC_SIGNAL                  AS nodes_traffic_signal,
                    2020                                  AS CRASH_SUBSET,
                    EXTRACT (YEAR FROM accident_date)     AS accident_year
               FROM CRASHES_ON_ROUTE_2020  a
                    LEFT OUTER JOIN NODES_history nodes
                        ON     a.NODE_ID = NODES.NODE_ID
                           AND nodes.snapshot_year = 2020
                           AND nodes.state = 'PAST'
              WHERE     a.ROUTE_NUMBER = a.PRIMARY_ROUTE_NUMBER
                    AND EXTRACT (YEAR FROM accident_date) = 2020
             UNION ALL
             SELECT a.MDOTID,
                    a.PRIMARY_ROUTE_NAME,
                    a.PRIMARY_ROUTE_NUMBER,
                    a.PRIMARY_ROUTE_MP,
                    a.AADT,
                    a.ACCIDENT_DATE,
                    a.ACCIDENT_DAY_OF_WEEK,
                    a.ACCIDENT_DAY_OF_WEEK_NUM,
                    a.ACCIDENT_HOUR,
                    a.ACCIDENT_MONTH_NAME,
                    a.ACCIDENT_MONTH_NUM,
                    a.ACCIDENT_TIME,
                    a.BEGIN_ELEMENT_MILEPOINT,
                    a.BEGIN_SECTION_MP,
                    a.BEGIN_SECTION_OFFSET,
                    a.CAPACITY,
                    a.CONTRIB_CIRC_ENV1,
                    a.CONTRIB_CIRC_ENV1_DESCR,
                    a.CONTRIB_CIRC_ENV2,
                    a.CONTRIB_CIRC_ENV2_DESCR,
                    a.CONTRIB_CIRC_ROAD1,
                    a.CONTRIB_CIRC_ROAD1_DESCR,
                    a.CONTRIB_CIRC_ROAD2,
                    a.CONTRIB_CIRC_ROAD2_DESCR,
                    a.COUNTY_CODE,
                    a.COUNTY_NAME,
                    a.DIRECTIONAL_SUFFIX,
                    a.ELEMENT_ID,
                    a.ELEMENT_LENGTH,
                    a.ELEMENT_WID,
                    a.END_ELEMENT_MILEPOINT,
                    a.END_SECTION_MP,
                    a.END_SECTION_OFFSET,
                    a.EXISTING,
                    a.FACTOR_YEAR,
                    a.FACTORED_AADT,
                    a.FEDERAL_FUNCTIONAL_CLASS,
                    a.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                    a.FEDERAL_URBAN_GROUP,
                    a.FEDERAL_URBAN_GROUP_DESCR,
                    a.FUTURE_ADT,
                    a.FUTURE_ADT_YEAR,
                    a.HASS_DESCRIPTION,
                    a.HUNDRED_MILLION_VEHICLE_MILES,
                    a.INJURY_COUNT,
                    a.INJURY_LEVEL,
                    a.INJURY_LEVEL_CODE,
                    a.JURISDICTION,
                    a.LANE_COUNT,
                    a.LATITUDE,
                    a.LONGITUDE,
                    a.LEFT_SHOULDER_TYPE,
                    a.LEFT_SHOULDER_TYPE_DESCR,
                    a.LEFT_SHOULDER_WIDTH,
                    a.LIGHT_CONDITION,
                    a.LIGHT_CONDITION_DESCR,
                    a.LOC_FIRST_HARMFUL_EVENT,
                    a.LOC_FIRST_HARMFUL_EVENT_DESCR,
                    a.LOCATION_TYPE,
                    a.MEDIAN_AVERAGE_WIDTH,
                    a.MEDIAN_TYPE,
                    a.MEDIAN_TYPE_DESCR,
                    a.MEV                                 AS CRASHES_ON_ROUTE_MEV,
                    a.NATIONAL_TRUCK_NETWORK,
                    a.NATIONAL_TRUCK_NETWORK_DESCR,
                    a.NHS_STATUS,
                    a.NO_OF_A_INJ,
                    a.NO_OF_B_INJ,
                    a.NO_OF_C_INJ,
                    a.NO_OF_K_INJ,
                    a.NO_OF_NON_INJ,
                    a.NODE_ID                             AS COR_NODE_ID,
                    a.NUMBER_OF_LANES,
                    a.OFFSET,
                    a.ONE_WAY,
                    a.ONE_WAY_DESCR,
                    a.RAMP,
                    a.RAMP_DESCR,
                    a.REGION_CODE,
                    a.REGION_NAME,
                    a.REPORT_NUMBER,
                    a.REPORTING_AGENCY,
                    a.REPORTING_AGENCY_DESCR,
                    a.RIGHT_SHOULDER_TYPE,
                    a.RIGHT_SHOULDER_TYPE_DESCR,
                    a.RIGHT_SHOULDER_WIDTH,
                    a.ROAD_GRADE,
                    a.ROAD_GRADE_DESCR,
                    a.ROAD_SURF_COND,
                    a.ROAD_SURF_COND_DESCR,
                    a.ROADWAY_TYPE,
                    a.ROUTE_NAME,
                    a.ROUTE_NUMBER,
                    a.ROUTE_SYSTEM,
                    a.SCENIC_BYWAY_DESCRIPTION,
                    a.SCENIC_BYWAY_DESIG_YR,
                    a.SCENIC_BYWAY_NAME,
                    a.SCENIC_BYWAY_TYPE,
                    a.SCENIC_BYWAY_TYPE_DESCR,
                    a.SCHOOL_BUS_RELATED,
                    a.SCHOOL_BUS_RELATED_DESCR,
                    a.SECTION_ID,
                    a.SECTION_LENGTH,
                    a.SPEED,
                    a.SPEED_LIMIT,
                    a.STATE_DESIG_TYPE,
                    a.STATE_DESIG_TYPE_DESCR,
                    a.STATE_URBAN_RURAL,
                    a.STATE_URBAN_RURAL_DESCR,
                    a.STREET_NAME,
                    a.STREET_NAME_PREFIX,
                    a.STREET_NAME_SUFFIX,
                    a.TOTAL_PAVEMENT_WIDTH,
                    a.TOWN_CODE,
                    a.TOWN_NAME,
                    a.TRAFFIC_CONTROL_DEVICE,
                    a.TRAFFIC_CONTROL_DEVICE_DESCR,
                    a.TRF_CNTRL_DEV_OPRATIONL,
                    a.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                    a.TRUCK_PERCENT,
                    a.TYPE_OF_CRASH,
                    a.TYPE_OF_CRASH_DESCR,
                    a.TYPE_OF_LOCATION,
                    a.TYPE_OF_LOCATION_DESCR,
                    a.WEATHER_CONDITION,
                    a.WEATHER_CONDITION_DESCR,
                    a.WIDTH,
                    a.WORKZONE_IN_OR_NEAR,
                    a.WORKZONE_IN_OR_NEAR_DESCR,
                    a.WORKZONE_LOCATION,
                    a.WORKZONE_LOCATION_DESCR,
                    a.WORKZONE_POLICE_PRESENT,
                    a.WORKZONE_POLICE_PRESENT_DESCR,
                    a.WORKZONE_TYPE,
                    a.WORKZONE_TYPE_DESCR,
                    a.WORKZONE_WORKERS_PRESENT,
                    a.WORKZONE_WORKERS_PRESENT_DESCR,
                    nodes.MEV                             AS NODES_MEV,
                    nodes.NODE_ID                         AS NODES_NODE_ID,
                    nodes.NO_OF_LEGS                      AS nodes_no_of_legs,
                    nodes.NODE_DESCRIPTION                AS nodes_node_description,
                    nodes.TOWN_CODE1                      AS nodes_town_code1,
                    nodes.TOWN_CODE2                      AS nodes_town_code2,
                    nodes.TOWN_NAME1                      AS nodes_town_name1,
                    nodes.TOWN_NAME2                      AS nodes_town_name2,
                    nodes.TOWNLINE_NODE                   AS nodes_townline_node,
                    nodes.TRAFFIC_SIGNAL                  AS nodes_traffic_signal,
                    2019                                  AS CRASH_SUBSET,
                    EXTRACT (YEAR FROM accident_date)     AS accident_year
               FROM CRASHES_ON_ROUTE_2019  a
                    LEFT OUTER JOIN NODES_history nodes
                        ON     a.NODE_ID = NODES.NODE_ID
                           AND nodes.snapshot_year = 2019
                           AND nodes.state = 'PAST'
              WHERE     a.ROUTE_NUMBER = a.PRIMARY_ROUTE_NUMBER
                    AND EXTRACT (YEAR FROM accident_date) = 2019
             UNION ALL
             SELECT a.MDOTID,
                    a.PRIMARY_ROUTE_NAME,
                    a.PRIMARY_ROUTE_NUMBER,
                    a.PRIMARY_ROUTE_MP,
                    a.AADT,
                    a.ACCIDENT_DATE,
                    a.ACCIDENT_DAY_OF_WEEK,
                    a.ACCIDENT_DAY_OF_WEEK_NUM,
                    a.ACCIDENT_HOUR,
                    a.ACCIDENT_MONTH_NAME,
                    a.ACCIDENT_MONTH_NUM,
                    a.ACCIDENT_TIME,
                    a.BEGIN_ELEMENT_MILEPOINT,
                    a.BEGIN_SECTION_MP,
                    a.BEGIN_SECTION_OFFSET,
                    a.CAPACITY,
                    a.CONTRIB_CIRC_ENV1,
                    a.CONTRIB_CIRC_ENV1_DESCR,
                    a.CONTRIB_CIRC_ENV2,
                    a.CONTRIB_CIRC_ENV2_DESCR,
                    a.CONTRIB_CIRC_ROAD1,
                    a.CONTRIB_CIRC_ROAD1_DESCR,
                    a.CONTRIB_CIRC_ROAD2,
                    a.CONTRIB_CIRC_ROAD2_DESCR,
                    a.COUNTY_CODE,
                    a.COUNTY_NAME,
                    a.DIRECTIONAL_SUFFIX,
                    a.ELEMENT_ID,
                    a.ELEMENT_LENGTH,
                    a.ELEMENT_WID,
                    a.END_ELEMENT_MILEPOINT,
                    a.END_SECTION_MP,
                    a.END_SECTION_OFFSET,
                    a.EXISTING,
                    a.FACTOR_YEAR,
                    a.FACTORED_AADT,
                    a.FEDERAL_FUNCTIONAL_CLASS,
                    a.FEDERAL_FUNCTIONAL_CLASS_DESCR,
                    a.FEDERAL_URBAN_GROUP,
                    a.FEDERAL_URBAN_GROUP_DESCR,
                    a.FUTURE_ADT,
                    a.FUTURE_ADT_YEAR,
                    a.HASS_DESCRIPTION,
                    a.HUNDRED_MILLION_VEHICLE_MILES,
                    a.INJURY_COUNT,
                    a.INJURY_LEVEL,
                    a.INJURY_LEVEL_CODE,
                    a.JURISDICTION,
                    a.LANE_COUNT,
                    a.LATITUDE,
                    a.LONGITUDE,
                    a.LEFT_SHOULDER_TYPE,
                    a.LEFT_SHOULDER_TYPE_DESCR,
                    a.LEFT_SHOULDER_WIDTH,
                    a.LIGHT_CONDITION,
                    a.LIGHT_CONDITION_DESCR,
                    a.LOC_FIRST_HARMFUL_EVENT,
                    a.LOC_FIRST_HARMFUL_EVENT_DESCR,
                    a.LOCATION_TYPE,
                    a.MEDIAN_AVERAGE_WIDTH,
                    a.MEDIAN_TYPE,
                    a.MEDIAN_TYPE_DESCR,
                    a.MEV                                 AS CRASHES_ON_ROUTE_MEV,
                    a.NATIONAL_TRUCK_NETWORK,
                    a.NATIONAL_TRUCK_NETWORK_DESCR,
                    a.NHS_STATUS,
                    a.NO_OF_A_INJ,
                    a.NO_OF_B_INJ,
                    a.NO_OF_C_INJ,
                    a.NO_OF_K_INJ,
                    a.NO_OF_NON_INJ,
                    a.NODE_ID                             AS COR_NODE_ID,
                    a.NUMBER_OF_LANES,
                    a.OFFSET,
                    a.ONE_WAY,
                    a.ONE_WAY_DESCR,
                    a.RAMP,
                    a.RAMP_DESCR,
                    a.REGION_CODE,
                    a.REGION_NAME,
                    a.REPORT_NUMBER,
                    a.REPORTING_AGENCY,
                    a.REPORTING_AGENCY_DESCR,
                    a.RIGHT_SHOULDER_TYPE,
                    a.RIGHT_SHOULDER_TYPE_DESCR,
                    a.RIGHT_SHOULDER_WIDTH,
                    a.ROAD_GRADE,
                    a.ROAD_GRADE_DESCR,
                    a.ROAD_SURF_COND,
                    a.ROAD_SURF_COND_DESCR,
                    a.ROADWAY_TYPE,
                    a.ROUTE_NAME,
                    a.ROUTE_NUMBER,
                    a.ROUTE_SYSTEM,
                    a.SCENIC_BYWAY_DESCRIPTION,
                    a.SCENIC_BYWAY_DESIG_YR,
                    a.SCENIC_BYWAY_NAME,
                    a.SCENIC_BYWAY_TYPE,
                    a.SCENIC_BYWAY_TYPE_DESCR,
                    a.SCHOOL_BUS_RELATED,
                    a.SCHOOL_BUS_RELATED_DESCR,
                    a.SECTION_ID,
                    a.SECTION_LENGTH,
                    a.SPEED,
                    a.SPEED_LIMIT,
                    a.STATE_DESIG_TYPE,
                    a.STATE_DESIG_TYPE_DESCR,
                    a.STATE_URBAN_RURAL,
                    a.STATE_URBAN_RURAL_DESCR,
                    a.STREET_NAME,
                    a.STREET_NAME_PREFIX,
                    a.STREET_NAME_SUFFIX,
                    a.TOTAL_PAVEMENT_WIDTH,
                    a.TOWN_CODE,
                    a.TOWN_NAME,
                    a.TRAFFIC_CONTROL_DEVICE,
                    a.TRAFFIC_CONTROL_DEVICE_DESCR,
                    a.TRF_CNTRL_DEV_OPRATIONL,
                    a.TRF_CNTRL_DEV_OPRATIONL_DESCR,
                    a.TRUCK_PERCENT,
                    a.TYPE_OF_CRASH,
                    a.TYPE_OF_CRASH_DESCR,
                    a.TYPE_OF_LOCATION,
                    a.TYPE_OF_LOCATION_DESCR,
                    a.WEATHER_CONDITION,
                    a.WEATHER_CONDITION_DESCR,
                    a.WIDTH,
                    a.WORKZONE_IN_OR_NEAR,
                    a.WORKZONE_IN_OR_NEAR_DESCR,
                    a.WORKZONE_LOCATION,
                    a.WORKZONE_LOCATION_DESCR,
                    a.WORKZONE_POLICE_PRESENT,
                    a.WORKZONE_POLICE_PRESENT_DESCR,
                    a.WORKZONE_TYPE,
                    a.WORKZONE_TYPE_DESCR,
                    a.WORKZONE_WORKERS_PRESENT,
                    a.WORKZONE_WORKERS_PRESENT_DESCR,
                    nodes.MEV                             AS NODES_MEV,
                    nodes.NODE_ID                         AS NODES_NODE_ID,
                    nodes.NO_OF_LEGS                      AS nodes_no_of_legs,
                    nodes.NODE_DESCRIPTION                AS nodes_node_description,
                    nodes.TOWN_CODE1                      AS nodes_town_code1,
                    nodes.TOWN_CODE2                      AS nodes_town_code2,
                    nodes.TOWN_NAME1                      AS nodes_town_name1,
                    nodes.TOWN_NAME2                      AS nodes_town_name2,
                    nodes.TOWNLINE_NODE                   AS nodes_townline_node,
                    nodes.TRAFFIC_SIGNAL                  AS nodes_traffic_signal,
                    2018                                  AS CRASH_SUBSET,
                    EXTRACT (YEAR FROM accident_date)     AS accident_year
               FROM CRASHES_ON_ROUTE_2018  a
                    LEFT OUTER JOIN NODES_history nodes
                        ON     a.NODE_ID = NODES.NODE_ID
                           AND nodes.snapshot_year = 2018
                           AND nodes.state = 'PAST'
              WHERE     a.ROUTE_NUMBER = a.PRIMARY_ROUTE_NUMBER
                    AND EXTRACT (YEAR FROM accident_date) IN
                            (2016, 2017, 2018))
    SELECT "UNIQUEID",
           "MDOTID",
           gis_crash_id,
           "PRIMARY_ROUTE_NAME",
           "PRIMARY_ROUTE_NUMBER",
           "PRIMARY_ROUTE_MP",
           "AADT",
           "ACCIDENT_DATE",
           "ACCIDENT_DAY_OF_WEEK",
           "ACCIDENT_DAY_OF_WEEK_NUM",
           "ACCIDENT_HOUR",
           "ACCIDENT_MONTH_NAME",
           "ACCIDENT_MONTH_NUM",
           "ACCIDENT_TIME",
           "BEGIN_ELEMENT_MILEPOINT",
           "BEGIN_SECTION_MP",
           "BEGIN_SECTION_OFFSET",
           "CAPACITY",
           "CONTRIB_CIRC_ENV1",
           "CONTRIB_CIRC_ENV1_DESCR",
           "CONTRIB_CIRC_ENV2",
           "CONTRIB_CIRC_ENV2_DESCR",
           "CONTRIB_CIRC_ROAD1",
           "CONTRIB_CIRC_ROAD1_DESCR",
           "CONTRIB_CIRC_ROAD2",
           "CONTRIB_CIRC_ROAD2_DESCR",
           "COUNTY_CODE",
           "COUNTY_NAME",
           "DIRECTIONAL_SUFFIX",
           "ELEMENT_ID",
           "ELEMENT_LENGTH",
           "ELEMENT_WID",
           "END_ELEMENT_MILEPOINT",
           "END_SECTION_MP",
           "END_SECTION_OFFSET",
           "EXISTING",
           "FACTOR_YEAR",
           "FACTORED_AADT",
           "FEDERAL_FUNCTIONAL_CLASS",
           "FEDERAL_FUNCTIONAL_CLASS_DESCR",
           "FEDERAL_URBAN_GROUP",
           "FEDERAL_URBAN_GROUP_DESCR",
           "FUTURE_ADT",
           "FUTURE_ADT_YEAR",
           "HASS_DESCRIPTION",
           "HUNDRED_MILLION_VEHICLE_MILES",
           "INJURY_COUNT",
           "INJURY_LEVEL",
           "INJURY_LEVEL_CODE",
           "JURISDICTION",
           "LANE_COUNT",
           "LATITUDE",
           "LONGITUDE",
           "LEFT_SHOULDER_TYPE",
           "LEFT_SHOULDER_TYPE_DESCR",
           "LEFT_SHOULDER_WIDTH",
           "LIGHT_CONDITION",
           "LIGHT_CONDITION_DESCR",
           "LOC_FIRST_HARMFUL_EVENT",
           "LOC_FIRST_HARMFUL_EVENT_DESCR",
           "LOCATION_TYPE",
           "MEDIAN_AVERAGE_WIDTH",
           "MEDIAN_TYPE",
           "MEDIAN_TYPE_DESCR",
           "CRASHES_ON_ROUTE_MEV",
           "NATIONAL_TRUCK_NETWORK",
           "NATIONAL_TRUCK_NETWORK_DESCR",
           "NHS_STATUS",
           "NO_OF_A_INJ",
           "NO_OF_B_INJ",
           "NO_OF_C_INJ",
           "NO_OF_K_INJ",
           "NO_OF_NON_INJ",
           "COR_NODE_ID",
           "NUMBER_OF_LANES",
           "OFFSET",
           "ONE_WAY",
           "ONE_WAY_DESCR",
           "RAMP",
           "RAMP_DESCR",
           "REGION_CODE",
           "REGION_NAME",
           "REPORT_NUMBER",
           "REPORTING_AGENCY",
           "REPORTING_AGENCY_DESCR",
           "RIGHT_SHOULDER_TYPE",
           "RIGHT_SHOULDER_TYPE_DESCR",
           "RIGHT_SHOULDER_WIDTH",
           "ROAD_GRADE",
           "ROAD_GRADE_DESCR",
           "ROAD_SURF_COND",
           "ROAD_SURF_COND_DESCR",
           "ROADWAY_TYPE",
           "ROUTE_NAME",
           "ROUTE_NUMBER",
           "ROUTE_SYSTEM",
           "SCENIC_BYWAY_DESCRIPTION",
           "SCENIC_BYWAY_DESIG_YR",
           "SCENIC_BYWAY_NAME",
           "SCENIC_BYWAY_TYPE",
           "SCENIC_BYWAY_TYPE_DESCR",
           "SCHOOL_BUS_RELATED",
           "SCHOOL_BUS_RELATED_DESCR",
           "SECTION_ID",
           "SECTION_LENGTH",
           "SPEED",
           "SPEED_LIMIT",
           "STATE_DESIG_TYPE",
           "STATE_DESIG_TYPE_DESCR",
           "STATE_URBAN_RURAL",
           "STATE_URBAN_RURAL_DESCR",
           "STREET_NAME",
           "STREET_NAME_PREFIX",
           "STREET_NAME_SUFFIX",
           "TOTAL_PAVEMENT_WIDTH",
           "TOWN_CODE",
           "TOWN_NAME",
           "TRAFFIC_CONTROL_DEVICE",
           "TRAFFIC_CONTROL_DEVICE_DESCR",
           "TRF_CNTRL_DEV_OPRATIONL",
           "TRF_CNTRL_DEV_OPRATIONL_DESCR",
           "TRUCK_PERCENT",
           "TYPE_OF_CRASH",
           "TYPE_OF_CRASH_DESCR",
           "TYPE_OF_LOCATION",
           "TYPE_OF_LOCATION_DESCR",
           "WEATHER_CONDITION",
           "WEATHER_CONDITION_DESCR",
           "WIDTH",
           "WORKZONE_IN_OR_NEAR",
           "WORKZONE_IN_OR_NEAR_DESCR",
           "WORKZONE_LOCATION",
           "WORKZONE_LOCATION_DESCR",
           "WORKZONE_POLICE_PRESENT",
           "WORKZONE_POLICE_PRESENT_DESCR",
           "WORKZONE_TYPE",
           "WORKZONE_TYPE_DESCR",
           "WORKZONE_WORKERS_PRESENT",
           "WORKZONE_WORKERS_PRESENT_DESCR",
           "NODES_MEV",
           "NO_OF_LEGS",
           "NODE_DESCRIPTION",
           "TOWN_CODE1",
           "TOWN_CODE2",
           "TOWN_NAME1",
           "TOWN_NAME2",
           "TOWNLINE_NODE",
           "TRAFFIC_SIGNAL",
           "ACCIDENT_YEAR",
           "CRASH_SUBSET"
      FROM (SELECT CAST (
                       ROW_NUMBER ()
                           OVER (
                               ORDER BY CRASH_SUBSET, ACCIDENT_YEAR, MDOTID)
                           AS NUMBER (9))    AS uniqueid,
                   MDOTID,
                   CASE
                       WHEN (UPPER (MDOTID) LIKE '%C')
                       THEN
                              SUBSTR (MDOTID, 1, 5)
                           || LPAD (SUBSTR (MDOTID, 6), 6, '0')
                       ELSE
                              SUBSTR (MDOTID, 1, 5)
                           || LPAD (SUBSTR (MDOTID, 6), 5, '0')
                   END                       AS GIS_crash_id,
                   PRIMARY_ROUTE_NAME,
                   PRIMARY_ROUTE_NUMBER,
                   PRIMARY_ROUTE_MP,
                   AADT,
                   ACCIDENT_DATE,
                   ACCIDENT_DAY_OF_WEEK,
                   ACCIDENT_DAY_OF_WEEK_NUM,
                   ACCIDENT_HOUR,
                   ACCIDENT_MONTH_NAME,
                   ACCIDENT_MONTH_NUM,
                   ACCIDENT_TIME,
                   BEGIN_ELEMENT_MILEPOINT,
                   BEGIN_SECTION_MP,
                   BEGIN_SECTION_OFFSET,
                   CAPACITY,
                   CONTRIB_CIRC_ENV1,
                   CONTRIB_CIRC_ENV1_DESCR,
                   CONTRIB_CIRC_ENV2,
                   CONTRIB_CIRC_ENV2_DESCR,
                   CONTRIB_CIRC_ROAD1,
                   CONTRIB_CIRC_ROAD1_DESCR,
                   CONTRIB_CIRC_ROAD2,
                   CONTRIB_CIRC_ROAD2_DESCR,
                   COUNTY_CODE,
                   COUNTY_NAME,
                   DIRECTIONAL_SUFFIX,
                   ELEMENT_ID,
                   ELEMENT_LENGTH,
                   ELEMENT_WID,
                   END_ELEMENT_MILEPOINT,
                   END_SECTION_MP,
                   END_SECTION_OFFSET,
                   EXISTING,
                   FACTOR_YEAR,
                   FACTORED_AADT,
                   FEDERAL_FUNCTIONAL_CLASS,
                   FEDERAL_FUNCTIONAL_CLASS_DESCR,
                   FEDERAL_URBAN_GROUP,
                   FEDERAL_URBAN_GROUP_DESCR,
                   FUTURE_ADT,
                   FUTURE_ADT_YEAR,
                   HASS_DESCRIPTION,
                   HUNDRED_MILLION_VEHICLE_MILES,
                   INJURY_COUNT,
                   INJURY_LEVEL,
                   INJURY_LEVEL_CODE,
                   JURISDICTION,
                   LANE_COUNT,
                   LATITUDE,
                   LONGITUDE,
                   LEFT_SHOULDER_TYPE,
                   LEFT_SHOULDER_TYPE_DESCR,
                   LEFT_SHOULDER_WIDTH,
                   LIGHT_CONDITION,
                   LIGHT_CONDITION_DESCR,
                   LOC_FIRST_HARMFUL_EVENT,
                   LOC_FIRST_HARMFUL_EVENT_DESCR,
                   LOCATION_TYPE,
                   MEDIAN_AVERAGE_WIDTH,
                   MEDIAN_TYPE,
                   MEDIAN_TYPE_DESCR,
                   CRASHES_ON_ROUTE_MEV,
                   NATIONAL_TRUCK_NETWORK,
                   NATIONAL_TRUCK_NETWORK_DESCR,
                   NHS_STATUS,
                   NO_OF_A_INJ,
                   NO_OF_B_INJ,
                   NO_OF_C_INJ,
                   NO_OF_K_INJ,
                   NO_OF_NON_INJ,
                   COR_NODE_ID,
                   NUMBER_OF_LANES,
                   OFFSET,
                   ONE_WAY,
                   ONE_WAY_DESCR,
                   RAMP,
                   RAMP_DESCR,
                   REGION_CODE,
                   REGION_NAME,
                   REPORT_NUMBER,
                   REPORTING_AGENCY,
                   REPORTING_AGENCY_DESCR,
                   RIGHT_SHOULDER_TYPE,
                   RIGHT_SHOULDER_TYPE_DESCR,
                   RIGHT_SHOULDER_WIDTH,
                   ROAD_GRADE,
                   ROAD_GRADE_DESCR,
                   ROAD_SURF_COND,
                   ROAD_SURF_COND_DESCR,
                   ROADWAY_TYPE,
                   ROUTE_NAME,
                   ROUTE_NUMBER,
                   ROUTE_SYSTEM,
                   SCENIC_BYWAY_DESCRIPTION,
                   SCENIC_BYWAY_DESIG_YR,
                   SCENIC_BYWAY_NAME,
                   SCENIC_BYWAY_TYPE,
                   SCENIC_BYWAY_TYPE_DESCR,
                   SCHOOL_BUS_RELATED,
                   SCHOOL_BUS_RELATED_DESCR,
                   SECTION_ID,
                   SECTION_LENGTH,
                   SPEED,
                   SPEED_LIMIT,
                   STATE_DESIG_TYPE,
                   STATE_DESIG_TYPE_DESCR,
                   STATE_URBAN_RURAL,
                   STATE_URBAN_RURAL_DESCR,
                   STREET_NAME,
                   STREET_NAME_PREFIX,
                   STREET_NAME_SUFFIX,
                   TOTAL_PAVEMENT_WIDTH,
                   TOWN_CODE,
                   TOWN_NAME,
                   TRAFFIC_CONTROL_DEVICE,
                   TRAFFIC_CONTROL_DEVICE_DESCR,
                   TRF_CNTRL_DEV_OPRATIONL,
                   TRF_CNTRL_DEV_OPRATIONL_DESCR,
                   TRUCK_PERCENT,
                   TYPE_OF_CRASH,
                   TYPE_OF_CRASH_DESCR,
                   TYPE_OF_LOCATION,
                   TYPE_OF_LOCATION_DESCR,
                   WEATHER_CONDITION,
                   WEATHER_CONDITION_DESCR,
                   WIDTH,
                   WORKZONE_IN_OR_NEAR,
                   WORKZONE_IN_OR_NEAR_DESCR,
                   WORKZONE_LOCATION,
                   WORKZONE_LOCATION_DESCR,
                   WORKZONE_POLICE_PRESENT,
                   WORKZONE_POLICE_PRESENT_DESCR,
                   WORKZONE_TYPE,
                   WORKZONE_TYPE_DESCR,
                   WORKZONE_WORKERS_PRESENT,
                   WORKZONE_WORKERS_PRESENT_DESCR,
                   nodes_MEV                 NODES_MEV,
                   nodes_NO_OF_LEGS          AS no_of_legs,
                   nodes_NODE_DESCRIPTION    AS node_description,
                   nodes_TOWN_CODE1          AS town_code1,
                   nodes_TOWN_CODE2          AS town_code2,
                   nodes_TOWN_NAME1          AS town_name1,
                   nodes_TOWN_NAME2          AS town_name2,
                   nodes_TOWNLINE_NODE       AS townline_node,
                   nodes_TRAFFIC_SIGNAL      AS traffic_signal,
                   accident_year,
                   crash_subset
              FROM hsiscrashes) --where CRASH_SUBSET=2018 and accident_year = 2017
;
