CREATE OR REPLACE VIEW WH_ASSETS.V_MIRE_SEGMENT_NON_LOCAL_PAVED
BEQUEATH DEFINER
AS 
SELECT DISTINCT SECTION_ID, ROUTE_NUMBER, ROUTE_NAME, STREETNAME, FED_AID,
                      NHS_TYPE_DESCR, FEDERAL_URBAN_RURAL_DESCR, LANE_SURFACE_TYPE_DESCR,
                      BEGIN_SECTION_MP, END_SECTION_MP, SECTION_LENGTH, DIRECTIONAL_SUFFIX,
                      FEDERAL_FUNCTIONAL_CLASS_DESCR, MEDIAN_TYPE_DESCR,
                      ACCESS_CONTROL_DESCR, ONE_WAY_DESCR, THRU_LANE_COUNT,
                      FACTORED_AADT AADT, FACTOR_YEAR AADT_YEAR, AGENCY_DESCR
        FROM COMPLETE_TRANSPORTATION_NETWORK
       WHERE     SNAPSHOT_YEAR IN (2021)
             AND ROW_TYPE = 'Element'
             AND PRIMARY = 'Y'
             AND ROUTE_TYPE = 'N'
    ORDER BY ROUTE_NUMBER, BEGIN_SECTION_MP;
