CREATE OR REPLACE VIEW WH_ASSETS.V_MIRE_INTERCHANGE_RAMP
BEQUEATH DEFINER
AS 
SELECT MIN(' '), CN.ELEMENT_ID,  RAMP, ROUTE_NUMBER, BEGIN_ELEMENT_MILEPOINT,
            END_ELEMENT_MILEPOINT, ELEMENT_LENGTH, BEGIN_NODE_ID, 
            CONCAT(ND1.FEDERAL_FUNCTIONAL_CLASS_DESCR, ' ' || ND1.NHS_STATUS), 
            END_NODE_ID, CONCAT(ND2.FEDERAL_FUNCTIONAL_CLASS_DESCR, ' ' || ND2.NHS_STATUS), 
            MIN(' '), CN.FACTORED_AADT,
            FACTOR_YEAR, CN.FEDERAL_FUNCTIONAL_CLASS_DESCR,
            AGENCY_DESCR   
        FROM COMPLETE_TRANSPORTATION_NETWORK CN
        LEFT OUTER JOIN NODES ND1 ON ND1.NODE_ID = CN.BEGIN_NODE_ID
        LEFT OUTER JOIN NODES ND2 ON ND2.NODE_ID = CN.END_NODE_ID
       WHERE SNAPSHOT_YEAR IN (2021) AND ROW_TYPE = 'Element' AND RAMP = '1' AND PRIMARY = 'Y'
    GROUP BY  CN.ELEMENT_ID,  RAMP, ROUTE_NUMBER, BEGIN_ELEMENT_MILEPOINT,
            END_ELEMENT_MILEPOINT, ELEMENT_LENGTH,  BEGIN_NODE_ID, 
            ND1.FEDERAL_FUNCTIONAL_CLASS_DESCR, ND1.NHS_STATUS, END_NODE_ID, 
            ND2.FEDERAL_FUNCTIONAL_CLASS_DESCR, ND2.NHS_STATUS, CN.FACTORED_AADT,
            FACTOR_YEAR, CN.FEDERAL_FUNCTIONAL_CLASS_DESCR,
            AGENCY_DESCR 
    ORDER BY ROUTE_NUMBER, BEGIN_ELEMENT_MILEPOINT;
