CREATE OR REPLACE VIEW WH_ASSETS.V_MIRE_SEGMENT_LOCAL_PAVED
BEQUEATH DEFINER
AS 
SELECT SECTION_ID, ROUTE_NUMBER, FEDERAL_FUNCTIONAL_CLASS_DESCR,
                      LANE_SURFACE_TYPE_DESCR, AGENCY_DESCR, THRU_LANE_COUNT,
                      FACTORED_AADT AADT, FACTOR_YEAR AADT_YEAR, BEGIN_SECTION_MP,
                      END_SECTION_MP, FEDERAL_URBAN_RURAL_DESCR, SECTION_LENGTH
        FROM COMPLETE_TRANSPORTATION_NETWORK
       WHERE     SNAPSHOT_YEAR IN (2021)
             AND ROW_TYPE = 'Element'
             AND PRIMARY = 'Y'
             AND ROUTE_TYPE = 'I'
             AND LANE_SURFACE_TYPE_DESCR IN ('Flexible', 'High rigid', 'Port cement comp')
    ORDER BY ROUTE_NUMBER, BEGIN_SECTION_MP;
