CREATE OR REPLACE VIEW WH_ASSETS.V_PUBLIC_PRIVATE_T0WNS
BEQUEATH DEFINER
AS 
SELECT DISTINCT town
      FROM V_DTGISP_E911_PRIVATE
    UNION
    SELECT DISTINCT town_name
      FROM MV_DISSOLVED_PUBLIC_ROADS;
