CREATE OR REPLACE VIEW WH_ASSETS.V_QC_ELEMENTS_AADT_FACTORGROUP_NULL
BEQUEATH DEFINER
AS 
SELECT "NE_ID_OF","TOWNNAME","THRUTYPERD","THRUTYPERD_DESC","PRIORITY","FEDFUNCCLS" FROM V_QC_ELEMENTS_AADT_FACTORGROUP_NULL@METRANS;
