CREATE OR REPLACE VIEW WH_ASSETS.V_QC_CRASH_ENDATED_PRIMARY_NODES
BEQUEATH DEFINER
AS 
SELECT "PRIMARYNODE", "ASSOCIATEDNODE", "NODEDESCRIPTION", "NODE", "NODE_DESC",
           "TRAFFIC_SIGNAL", "NODE_START_YEAR", "NODE_END_YEAR", "LAST_REFRESH"
      FROM ASSOCIATEDNODES@CRASH
           FULL OUTER JOIN MV_NODES@CRASH ON MV_NODES.NODE = ASSOCIATEDNODES.PRIMARYNODE
     WHERE PRIMARYNODE IS NOT NULL AND MV_NODES.NODE_END_YEAR IS NOT NULL;
