CREATE OR REPLACE VIEW WH_ASSETS.V_QC_CRASH_FAILED_LOCATION_ASSIGNMENT
BEQUEATH DEFINER
AS 
SELECT "CRASHREPORTID", "REPORTINGAGENCY", "REPORTNUMBER", "CRASHDATE", "CRASHTIME",
           "REPORTDATE", "SCENEARRIVALDATE", "SCENEARRIVALTIME", "CITYORTOWN",
           "STREETORHIGHWAY", "POSTEDSPEEDLIMIT", "OFFROADORIFW",
           "NEARESTINTERSECTINGSTREET", "DIRECTIONFROMNEARESTINTERSECT",
           "DISTFROMNEARESTINTERSECTVALUE", "DISTFROMNEARESTINTERSECTUNIT", "LATITUDE",
           "LONGITUDE", "REPORTINGOFFICERNAME", "REPORTINGOFFICERBADGENUMBER",
           "ROADSURFACECONDITION", "ROADGRADE", "LIGHTCONDITION", "WEATHERCONDITION",
           "TYPEOFCRASH", "TRAFFICCONTROLDEVICE", "TRAFFICCONTROLDEVOPERATIONAL",
           "SCHOOLBUSRELATEDCRASH", "WORKZONEINORNEAR", "WORKZONELOCATION", "WORKZONETYPE",
           "WORKZONEWORKERSPRESENT", "WORKZONEPOLICEPRESENT", "CONTRIBCIRCUMSTANCESENVIRON1",
           "CONTRIBCIRCUMSTANCESENVIRON2", "CONTRIBUTINGCIRCUMSTANCESROAD1",
           "CONTRIBUTINGCIRCUMSTANCESROAD2",  "LASTDATETIMEMODIFIED",
           "DATETIMEREPORTCREATED",  "APPROVEDBY", "APPROVEDDATE",
           "TYPEOFLOCATION", "CRASHSYSTEMANDVERSION", "ELEMENTID", "NODE1", "NODE2",
           "MEASUREMENTNODE", "OFFSET", "ISTOTALDAMAGEOVERTHRESHOLD",
           "LOCATIONOFFIRSTHARMFULEVENT", "AUTONARRATIVECREATIONDATATIME", "MDOTID",
           "MDOTELEMENTID", "MDOTNODE1", "MDOTNODE2", "MDOTOFFSET", "MDOTREVIEWDATE",
           "MDOTREVIEWCOMMENT", "MDOTLASTMODIFIED", "MDOTREVIEWERID", "MDOTREVIEWED",
           "CASEXPORTDATE", "STATEUPLOADSTATUS", "GCRUPLOADSTATUS", "XSDFILENAME",
           "XSLFILENAME", "CRASHREPORTCREATOR", "CASEMANAGEMENTSTATE", "PASSEDAUDIT",
           "REVIEWERCOMMENTPENDING",  "MDOTNONHIGHWAY",
           "MDOTELEMENTID_CURRENT", "MDOTNODE1_CURRENT", "MDOTNODE2_CURRENT",
           "MDOTOFFSET_CURRENT"
      FROM CRASHREPORT@CRASH
     WHERE MDOTELEMENTID_CURRENT = -1 AND MDOTNONHIGHWAY = 0;
