CREATE OR REPLACE VIEW WH_ASSETS.V_QC_CRASH_WITH_ENDDATED_NODES_ELEMENTS
BEQUEATH DEFINER
AS 
SELECT MDOTID
      FROM CRASHREPORT@CRASH
     WHERE     MDOTELEMENTID_CURRENT IN (SELECT NEH_NE_ID_OLD FROM MV_ELEMENTS_CLOSED@CRASH)
           AND MDOTNONHIGHWAY = 0
    UNION
    SELECT MDOTID
      FROM CRASHREPORT@CRASH
     WHERE    MDOTNODE1_CURRENT IN (SELECT NODE
                                      FROM MV_NODES@CRASH
                                     WHERE NODE_END_YEAR IS NOT NULL)
           OR MDOTNODE2_CURRENT IN (SELECT NODE
                                      FROM MV_NODES@CRASH
                                     WHERE NODE_END_YEAR IS NOT NULL)
    ORDER BY MDOTID;
