CREATE OR REPLACE VIEW WH_ASSETS.V_QC_BRIDGE_IBRIDGE_METRANS_COMPARE
BEQUEATH DEFINER
AS 
SELECT "BRDGNO","GPS_EASTING","GPS_NORTHING","OFF_SYSTEM","LINK_ID","OFFSET","SOURCE","BRDG_STATUS_CODE","BRDG_STATUS_DESC","ASSET_TYPE" FROM V_QC_BRIDGE_IBRIDGE_METRANS_COMPARE@METRANS

--GRANT SELECT ON V_QC_BRIDGE_IBRIDGE_METRANS_COMPARE to DASH_USER
;
