CREATE OR REPLACE VIEW WH_ASSETS.V_QC_BRIDGE_STATUS_IBRIDGE_METRANS
BEQUEATH DEFINER
AS 
SELECT "BRDGNO","BRIDGE_NAME","STRUCTURE_OPEN","STRUCTURE_OPEN_DESCR","BRDG_STATUS_CODE","BRDG_STATUS_DESC" FROM V_QC_BRIDGE_STATUS_IBRIDGE_METRANS@METRANS;
