CREATE OR REPLACE VIEW WH_ASSETS.V_TIDE_URIP_ADMIN
BEQUEATH DEFINER
AS 
SELECT "TIDEYEAR","EXTRACT_DATE","RESERVE_AMOUNT","BUDGET_AMOUNT","EXTRACT_AMOUNT","BUDGET_PERCENT","MODIFIED_BY","MODIFIED_DATE","ACTUAL_PERCENT","CERTIFICATION_STATUS" FROM URIP_ADMIN@TIDE

--GRANT SELECT ON V_TIDE_URIP_ADMIN TO DASH_USER
;
