CREATE OR REPLACE VIEW WH_ASSETS.V_TIDE_URIP_MILES
BEQUEATH DEFINER
AS 
SELECT "GROUP_NAME","SUM_CENTER","SUM_THRU2","SUM_THRU3","SUM_LEFTTURN","SUM_RIGHTTURN","SUM_CENTERTURN","SUM_TRUCKCLIMBING","GROUP_NUMBER","COUNTY","TIDEYEAR","PAYEE_CODE","PAYEE_TYPE","PAYEE_NAME" FROM URIP_MILES@TIDE

--GRANT SELECT ON V_TIDE_URIP_MILES to DASH_USER
;
