CREATE OR REPLACE VIEW WH_ASSETS.V_TIDE_URIP_DOLLARS
BEQUEATH DEFINER
AS 
SELECT "COUNTY","GROUP_NUMBER","GROUP_NAME","CENTER","THRU2","THRU3","LEFTTURN","RIGHTTURN","CENTERTURN","TRUCKCLIMBING","TIDEYEAR","PAYEE_CODE","PAYEE_TYPE","PAYEE_NAME","EXTRACT_DOLLARS" FROM URIP_DOLLARS@TIDE

--GRANT SELECT ON V_TIDE_URIP_DOLLARS to DASH_USER
;
