CREATE OR REPLACE PROCEDURE load_sections_staging
IS
    /**********************************************************************
    This procedure loads the sections_staging table from the gis system.
    Source View:  V_WH_BASE_SECTIONS_NO_XSP

    12-14-18 SH  Initial Version
    01-09-19 SH  HUNDRED_MILLION_VEHICLE_MILES, FUTURE_ADT, FUTURE_ADT_YEAR, TRUCK_PERCENT computed on GIS system
                 instead of in the warehouse
    01-14-19 SH  Remove cross sectional attributes right_lane_crosssection, right_shoulder_type, right_shoulder_type_descr, right_shoulder_width ,
                 left_lane_crosssection, left_shoulder_type, left_shoulder_type_descr, left_shoulder_width as they will be positioned correctly on the route
    01-16-19 SH  Remove route information
    02-11-19 SH  Clean up and modify new_sections_staging to sections_staging table , rename procedure to load_sections_staging
    02-21-19 SH  Add additional columns requested by Ed Beckwidth HPMS_SECTION_ID, NHS_TYPE , NHS_TYPE_DESCR , STRATEGIC_HIGHWAY_NETWORK ,
                 STRATEGIC_HIGHWAY_NETWORK_DESC , LANE_SURFACE_TYPE , LANE_SURFACE_TYPE_DESCR
    03-04-19 SH  Convert access_control to number
    04-05-19 SH  Add columns STATE_AID_NO, STATE_HIGHWAY_DESIGNATION_NUMBER
    06-15-21 SH  Add columns FED_AID, LAST_TREATMENT_PSN
    02-27-24 DG  Add columns BASE_AS_BUILT_HMA, BASE_GRAN_THICK, BASE_GRAN_TYPE, BASE_GRAN_TYPE_DESCR, BASE_MISC_THICK, BASE_MISC_TYPE, BASE_MISC_TYPE_DESCR, 
                             BASE_MOD_TYPE, BASE_MOD_TYPE_DESCR, BASE_MOD_YR, BASE_PRI_ID_TYPE, BASE_PRI_ID_TYPE_DESCR, BASE_PRIMARY_ID, BASE_PRIMARY_WIN,                
                             BASE_SEC_ID_TYPE, BASE_SEC_ID_TYPE_DESCR, BASE_SECOND_ID, BASE_SUB_THICK, 
                             EXCEPTIONS_DESC_XXX, FACTORED_AADT_CALC_COMMENT, 
                             HPMT_COMB_AADT_PCNT, HPMT_COMB_DHV_PCNT, HPMT_DHV_PCNT, HPMT_DIR_DIST, HPMT_PASS_AADT_PCNTc, HPMT_PASS_DHV_PCNT, HPMT_SU_AADT_PCNT, HPMT_SU_DHV_PCNT
                             NHFN_CONNECTOR_ID, NHFN_SUBSYSTEM, NHFN_SUBSYSTEM_DESCR, SLD_FILE_DATE, SLD_FILE_NAME 
    **********************************************************************/

    commit_count   NUMBER := 0;
    cntr           NUMBER := 0;

    g_start_time   DATE := SYSDATE;
    g_owner        VARCHAR2 (20) := 'WH_ASSETS';
    g_jobname      VARCHAR2 (30) := 'LOAD_SECTIONS_STAGING';
    g_object       VARCHAR2 (20) := 'SECTIONS_STAGING';
    g_sqlmsg       VARCHAR2 (500) := NULL;


    ele_wid        NUMBER;
    section_len    NUMBER;

    CURSOR sec IS
        SELECT aadt,
               aadt_type,
               aadt_type_descr,
               aadt_year,
               abn,
               abn_descr,
               access_control,
               access_control_descr,
               agency,
               agency_descr,
               base_as_built_hma,        
               base_gran_thick,
               base_gran_type,
               base_gran_type_descr,
               base_misc_thick,                 
               base_misc_type,                  
               base_misc_type_descr,            
               base_mod_type,                   
               base_mod_type_descr,             
               base_mod_yr,                     
               base_pri_id_type,                
               base_pri_id_type_descr,          
               base_primary_id,                 
               base_primary_win,                
               base_sec_id_type,                
               base_sec_id_type_descr,          
               base_second_id,                  
               base_sub_thick,  
               begin_offset,
               bridge_posting_csl,
               bridge_reliability_csl,
               capacity,
               center_turn_lane_count,
               center_turn_lane_width,
               condition_csl,
               congestion_csl,
               congestion_rate_csl,
               crash_history_csl,
               crash_history_rate_csl,
               csl_year,
               element_id,
               end_offset,
               exceptions_desc_xxx,
               factored_aadt,
               factored_aadt_calc_comment, 
               factor_year,
               fed_aid,
               federal_functional_class,
               federal_functional_class_descr,
               federal_urban_group,
               federal_urban_group_descr,
               federal_urban_rural,
               federal_urban_rural_descr,
               future_adt,
               future_adt_year,
               hass_description,
               hass_id,
               hpms_section_id,
               hpmt_comb_aadt_pcnt,
               hpmt_comb_dhv_pcnt,
               hpmt_dhv_pcnt,
               hpmt_dir_dist,
               hpmt_pass_aadt_pcnt,
               hpmt_pass_dhv_pcnt,
               hpmt_su_aadt_pcnt,
               hpmt_su_dhv_pcnt,
               hundred_million_vehicle_miles,
               iri,
               jurisdiction,
               jurisdiction_abbreviation,
               jurisdiction_code,
               lane_count,
               lane_surface_type,
               lane_surface_type_descr,
               last_treatment_psn,
               left_rut,
               left_turn_lane_count,
               left_turn_lane_width,
               maint_resp_winter,
               maint_resp_winter_descr,
               maint_resp_yearround,
               maint_resp_year_descr,
               mean_sum_deflection_csl,
               median_average_width,
               median_type,
               median_type_descr,
               min_pavement_width_csl,
               min_struct_bridge_cond_csl,
               mpo,
               national_truck_network,
               national_truck_network_descr,
               nhfn_connector_id,
               nhfn_subsystem,
               nhfn_subsystem_descr,
               nhs_status,
               nhs_type,
               nhs_type_descr,
               owner,
               owner_descr,
               pavement_condition_csl,
               pavement_rutting_csl,
               pavement_width_csl,
               pcr,
               plow_crew,
               pms_file_name,
               pms_inventory_year,
               priority,
               ride_quality_csl,
               right_rut,
               right_turn_lane_count,
               right_turn_lane_width,
               roadway_strength_csl,
               roadway_type,
               roadway_type_descr,
               road_posting_csl,
               rut_csl,
               safety_csl,
               scenic_byway_description,
               scenic_byway_desig_yr,
               scenic_byway_name,
               scenic_byway_type,
               scenic_byway_type_descr,
               service_csl,
               sh_sa_ir_designation,
               sld_file_date,                   
               sld_file_name, 
               speed,
               speedsrc,
               speedzn_id,
               spur_number,
               state_aid_no,
               state_designation_number,
               state_desig_type,
               state_desig_type_descr,
               state_hwy_designation_number,
               state_urban_rural,
               state_urban_rural_descr,
               strategic_highway_network,
               strategic_highway_network_desc,
               street_name,
               street_name_prefix,
               street_name_suffix,
               struct_bridge_cond_csl,
               summer_crew,
               thru_lane_count,
               thru_lane_width,
               total_pavement_width,
               truck_lane_count,
               truck_lane_width,
               truck_percent,
               wcsh_code,
               wcsh_agreement,
               weighted_iri_csl,
               weighted_pcr_csl,
               width,
               winter_crew
          FROM V_WH_BASE_SECTIONS_NO_XSP@gis;


    FUNCTION Get_element_wid (el_id IN NUMBER)
        RETURN NUMBER
    IS
        ele_wid   NUMBER;                               -- Get the element_wid
        err       VARCHAR2 (100);
    BEGIN
        SELECT element_wid
          INTO ele_wid
          FROM element_history h
         WHERE h.element_id = el_id AND h.state = 'CURRENT';

        RETURN ele_wid;
    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            RETURN NULL;
        WHEN OTHERS
        THEN
            err :=
                   'Error num :'
                || TO_CHAR (SQLCODE)
                || ' '
                || SUBSTR (SQLERRM, 1, 70);

            INSERT INTO data_exceptions (TABLE_NAME,
                                         ERROR_CONDITION,
                                         TEST_PROCEDURE,
                                         TEST_DATE,
                                         ASSESSMENT,
                                         COLUMN_NAME1,
                                         COLUMN_VALUE1,
                                         COLUMN_NAME2,
                                         COLUMN_VALUE2)
                 VALUES ('sections_staging',
                         err,
                         $$PLSQL_UNIT,
                         g_start_time,
                         'EXCEPTION',
                         'FUNCTION',
                         'Get_element_wid',
                         'ELEMENT_NUMBER',
                         el_id);

            RETURN NULL;
    END;
BEGIN
    EXECUTE IMMEDIATE 'truncate table sections_staging';

    EXECUTE IMMEDIATE 'truncate table sections_staging_error_log';


    FOR s IN sec
    LOOP
        ele_wid := Get_element_wid (s.element_id);
        section_len := s.end_offset - s.begin_offset;


        INSERT INTO sections_staging (aadt,
                                      aadt_type,
                                      aadt_type_descr,
                                      aadt_year,
                                      abn,
                                      abn_descr,
                                      access_control,
                                      access_control_descr,
                                      agency,
                                      agency_descr,
                                      base_as_built_hma,        
                                      base_gran_thick,
                                      base_gran_type,
                                      base_gran_type_descr,
                                      base_misc_thick,                 
                                      base_misc_type,                  
                                      base_misc_type_descr,            
                                      base_mod_type,                   
                                      base_mod_type_descr,             
                                      base_mod_yr,                     
                                      base_pri_id_type,                
                                      base_pri_id_type_descr,          
                                      base_primary_id,                 
                                      base_primary_win,                
                                      base_sec_id_type,                
                                      base_sec_id_type_descr,          
                                      base_second_id,                  
                                      base_sub_thick,  
                                      begin_offset,
                                      bridge_posting_csl,
                                      bridge_reliability_csl,
                                      capacity,
                                      center_turn_lane_count,
                                      center_turn_lane_width,
                                      condition_csl,
                                      congestion_csl,
                                      congestion_rate_csl,
                                      crash_history_csl,
                                      crash_history_rate_csl,
                                      csl_year,
                                      element_id,
                                      element_wid,
                                      end_offset,
                                      exceptions_desc_xxx,
                                      factored_aadt,
                                      factored_aadt_calc_comment, 
                                      factor_year,
                                      fed_aid,
                                      federal_functional_class,
                                      federal_functional_class_descr,
                                      federal_urban_group,
                                      federal_urban_group_descr,
                                      federal_urban_rural,
                                      federal_urban_rural_descr,
                                      future_adt,
                                      future_adt_year,
                                      hass_description,
                                      hass_id,
                                      hpms_section_id,
                                      hpmt_comb_aadt_pcnt,
                                      hpmt_comb_dhv_pcnt,
                                      hpmt_dhv_pcnt,
                                      hpmt_dir_dist,
                                      hpmt_pass_aadt_pcnt,
                                      hpmt_pass_dhv_pcnt,
                                      hpmt_su_aadt_pcnt,
                                      hpmt_su_dhv_pcnt,
                                      hundred_million_vehicle_miles,
                                      iri,
                                      jurisdiction,
                                      jurisdiction_abbreviation,
                                      jurisdiction_code,
                                      lane_count,
                                      lane_surface_type,
                                      lane_surface_type_descr,
                                      last_treatment_psn,
                                      left_rut,
                                      left_turn_lane_count,
                                      left_turn_lane_width,
                                      maint_resp_winter,
                                      maint_resp_winter_descr,
                                      maint_resp_yearround,
                                      maint_resp_year_descr,
                                      mean_sum_deflection_csl,
                                      median_average_width,
                                      median_type,
                                      median_type_descr,
                                      min_pavement_width_csl,
                                      min_struct_bridge_cond_csl,
                                      mpo,
                                      national_truck_network,
                                      national_truck_network_descr,
                                      nhfn_connector_id,
                                      nhfn_subsystem,
                                      nhfn_subsystem_descr,
                                      nhs_status,
                                      nhs_type,
                                      nhs_type_descr,
                                      owner,
                                      owner_descr,
                                      pavement_condition_csl,
                                      pavement_rutting_csl,
                                      pavement_width_csl,
                                      pcr,
                                      plow_crew,
                                      pms_file_name,
                                      pms_inventory_year,
                                      priority,
                                      ride_quality_csl,
                                      right_rut,
                                      right_turn_lane_count,
                                      right_turn_lane_width,
                                      roadway_strength_csl,
                                      roadway_type,
                                      roadway_type_descr,
                                      road_posting_csl,
                                      rut_csl,
                                      safety_csl,
                                      scenic_byway_description,
                                      scenic_byway_desig_yr,
                                      scenic_byway_name,
                                      scenic_byway_type,
                                      scenic_byway_type_descr,
                                      section_length,
                                      service_csl,
                                      sh_sa_ir_designation,
                                      sld_file_date,                   
                                      sld_file_name, 
                                      speed,
                                      speedsrc,
                                      speedzn_id,
                                      spur_number,
                                      state_aid_no,
                                      state_designation_number,
                                      state_desig_type,
                                      state_desig_type_descr,
                                      state_highway_designation_number,
                                      state_urban_rural,
                                      state_urban_rural_descr,
                                      strategic_highway_network,
                                      strategic_highway_network_desc,
                                      street_name,
                                      street_name_prefix,
                                      street_name_suffix,
                                      struct_bridge_cond_csl,
                                      summer_crew,
                                      thru_lane_count,
                                      thru_lane_width,
                                      total_pavement_width,
                                      truck_lane_count,
                                      truck_lane_width,
                                      truck_percent,
                                      wcsh_code,
                                      wcsh_agreement,
                                      weighted_iri_csl,
                                      weighted_pcr_csl,
                                      width,
                                      winter_crew)
             VALUES (s.aadt,
                     s.aadt_type,
                     s.aadt_type_descr,
                     s.aadt_year,
                     s.abn,
                     s.abn_descr,
                     convert_to_number (s.access_control),
                     s.access_control_descr,
                     s.agency,
                     s.agency_descr,
                     s.base_as_built_hma,        
                     s.base_gran_thick,
                     s.base_gran_type,
                     s.base_gran_type_descr,
                     s.base_misc_thick,                 
                     s.base_misc_type,                  
                     s.base_misc_type_descr,            
                     s.base_mod_type,                   
                     s.base_mod_type_descr,             
                     s.base_mod_yr,                     
                     s.base_pri_id_type,                
                     s.base_pri_id_type_descr,          
                     s.base_primary_id,                 
                     s.base_primary_win,                
                     s.base_sec_id_type,                
                     s.base_sec_id_type_descr,          
                     s.base_second_id,                  
                     s.base_sub_thick,  
                     s.begin_offset,
                     s.bridge_posting_csl,
                     s.bridge_reliability_csl,
                     s.capacity,
                     s.center_turn_lane_count,
                     s.center_turn_lane_width,
                     s.condition_csl,
                     s.congestion_csl,
                     s.congestion_rate_csl,
                     s.crash_history_csl,
                     s.crash_history_rate_csl,
                     s.csl_year,
                     s.element_id,
                     ele_wid,
                     s.end_offset,
                     s.exceptions_desc_xxx,
                     s.factored_aadt,
                     s.factored_aadt_calc_comment, 
                     s.factor_year,
                     s.fed_aid,
                     s.federal_functional_class,
                     s.federal_functional_class_descr,
                     s.federal_urban_group,
                     s.federal_urban_group_descr,
                     s.federal_urban_rural,
                     s.federal_urban_rural_descr,
                     s.future_adt,
                     s.future_adt_year,
                     s.hass_description,
                     s.hass_id,
                     s.hpms_section_id,
                     s.hpmt_comb_aadt_pcnt,
                     s.hpmt_comb_dhv_pcnt,
                     s.hpmt_dhv_pcnt,
                     s.hpmt_dir_dist,
                     s.hpmt_pass_aadt_pcnt,
                     s.hpmt_pass_dhv_pcnt,
                     s.hpmt_su_aadt_pcnt,
                     s.hpmt_su_dhv_pcnt,
                     s.hundred_million_vehicle_miles,
                     s.iri,
                     s.jurisdiction,
                     s.jurisdiction_abbreviation,
                     s.jurisdiction_code,
                     s.lane_count,
                     s.lane_surface_type,
                     s.lane_surface_type_descr,
                     s.last_treatment_psn,
                     s.left_rut,
                     s.left_turn_lane_count,
                     s.left_turn_lane_width,
                     s.maint_resp_winter,
                     s.maint_resp_winter_descr,
                     s.maint_resp_yearround,
                     s.maint_resp_year_descr,
                     s.mean_sum_deflection_csl,
                     s.median_average_width,
                     s.median_type,
                     s.median_type_descr,
                     s.min_pavement_width_csl,
                     s.min_struct_bridge_cond_csl,
                     s.mpo,
                     s.national_truck_network,
                     s.national_truck_network_descr,
                     s.nhfn_connector_id,
                     s.nhfn_subsystem,
                     s.nhfn_subsystem_descr,
                     s.nhs_status,
                     s.nhs_type,
                     s.nhs_type_descr,
                     s.owner,
                     s.owner_descr,
                     s.pavement_condition_csl,
                     s.pavement_rutting_csl,
                     s.pavement_width_csl,
                     s.pcr,
                     s.plow_crew,
                     s.pms_file_name,
                     s.pms_inventory_year,
                     s.priority,
                     s.ride_quality_csl,
                     s.right_rut,
                     s.right_turn_lane_count,
                     s.right_turn_lane_width,
                     s.roadway_strength_csl,
                     s.roadway_type,
                     s.roadway_type_descr,
                     s.road_posting_csl,
                     s.rut_csl,
                     s.safety_csl,
                     s.scenic_byway_description,
                     s.scenic_byway_desig_yr,
                     s.scenic_byway_name,
                     s.scenic_byway_type,
                     s.scenic_byway_type_descr,
                     section_len,
                     s.service_csl,
                     s.sh_sa_ir_designation,
                     s.sld_file_date,                   
                     s.sld_file_name, 
                     s.speed,
                     s.speedsrc,
                     s.speedzn_id,
                     s.spur_number,
                     s.state_aid_no,
                     s.state_designation_number,
                     s.state_desig_type,
                     s.state_desig_type_descr,
                     s.state_hwy_designation_number,
                     s.state_urban_rural,
                     s.state_urban_rural_descr,
                     s.strategic_highway_network,
                     s.strategic_highway_network_desc,
                     s.street_name,
                     s.street_name_prefix,
                     s.street_name_suffix,
                     s.struct_bridge_cond_csl,
                     s.summer_crew,
                     s.thru_lane_count,
                     s.thru_lane_width,
                     s.total_pavement_width,
                     s.truck_lane_count,
                     s.truck_lane_width,
                     s.truck_percent,
                     s.wcsh_code,
                     s.wcsh_agreement,
                     s.weighted_iri_csl,
                     s.weighted_pcr_csl,
                     s.width,
                     s.winter_crew)
                LOG ERRORS INTO sections_staging_error_log
                        ('Insert Sections Staging ' || SYSDATE)
                        REJECT LIMIT 100;

        commit_count := commit_count + 1;

        IF commit_count > 10000
        THEN
            COMMIT;
            commit_count := 0;
        END IF;
    END LOOP;

    COMMIT;



    SELECT COUNT (*) INTO cntr FROM sections_staging;

    WH_COMMON.PKG_COMMON_UTILITIES.UPDATE_WHSE_LOG (
        OWNER         => G_OWNER,
        OBJECT_NAME   => g_object,
        object_cnt    => cntr,
        proc          => $$PLSQL_UNIT,
        start_time    => g_start_time);
EXCEPTION
    WHEN OTHERS
    THEN
        G_SQLMSG := $$PLSQL_UNIT || ': ' || SUBSTR (SQLERRM, 1, 400);
        WH_COMMON.PKG_COMMON_UTILITIES.UPDATE_WHSE_LOG (
            OWNER         => G_OWNER,
            OBJECT_NAME   => g_object,
            MSG           => G_SQLMSG,
            STATUS        => 'Failed');

        WH_COMMON.PKG_COMMON_UTILITIES.EXIT_AND_REPORT (
            g_jobname,
            'FAILURE',
            $$PLSQL_UNIT || ' ' || SUBSTR (SQLERRM, 1, 400));
        RAISE_APPLICATION_ERROR (-20010, G_SQLMSG);
END;
/
