CREATE MATERIALIZED VIEW MV_BNS_PED_BIKE
NOCACHE
NOLOGGING
NOCOMPRESS
NOPARALLEL
NO INMEMORY
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT /*+ NOPARALLEL */ ACCIDENTS.MDOTID,
         COUNT (PERSON_TYPE)
             AS PED_BIKE_NUM,
         PERSON_TYPE
             AS PED_BIKE_TYPE,
         MIN (INJURY_DEGREE)
             AS MAXINJURY_DEGREECD,
         MIN (
             CRASH_LOOKUPI (
                 'INJURY_DEGREE',
                 (SELECT MIN (INJURY_DEGREE)
                    FROM ACCIDENT_PEOPLE
                   WHERE     ACCIDENTS.MDOTID = ACCIDENT_PEOPLE.MDOTID
                         AND ACCIDENT_PEOPLE.PERSON_TYPE IN (3, 7)
                         AND ACCIDENT_PEOPLE.INJURY_DEGREE IS NOT NULL)))
             AS MAXINJURY_DEGREEDESC,
           SUM (DECODE (INJURY_DEGREE, 2, 1, 0))
         + SUM (DECODE (INJURY_DEGREE, 3, 1, 0))
             AS NUM_PED_BIKE_INJURIES,
         SUM (DECODE (INJURY_DEGREE, 1, 1, 0))
             AS PED_BIKE_K,
         SUM (DECODE (INJURY_DEGREE, 2, 1, 0))
             AS PED_BIKE_A,
         SUM (DECODE (INJURY_DEGREE, 3, 1, 0))
             AS PED_BIKE_B,
         SUM (DECODE (INJURY_DEGREE, 4, 1, 0))
             AS PED_BIKE_C,
         SUM (DECODE (INJURY_DEGREE, 5, 1, 0))
             AS PED_BIKE_PD,
         LISTAGG (INJURY_DEGREE, ', ') WITHIN GROUP (ORDER BY INJURY_DEGREE)
             AS PED_BIKE_INJURY_DEGREECD,
         LISTAGG (CRASH_LOOKUP ('INJURY_DEGREE', INJURY_DEGREE), ', ')
             WITHIN GROUP (ORDER BY INJURY_DEGREE)
             AS PED_BIKE_INJURY_DEGREEDESC
    FROM ACCIDENTS
         INNER JOIN ACCIDENT_PEOPLE
             ON ACCIDENTS.MDOTID = ACCIDENT_PEOPLE.MDOTID
   WHERE     PERSON_TYPE IN (3, 7)
         AND TO_NUMBER (TO_CHAR (ACCIDENT_DATE, 'yyyy')) > 2011
         AND INJURY_DEGREE IS NOT NULL
GROUP BY ACCIDENTS.MDOTID,
         PERSON_TYPE,
         TO_NUMBER (TO_CHAR (ACCIDENT_DATE, 'yyyy'));
