CREATE MATERIALIZED VIEW MV_CRASH_PEOPLE_UNITS
NOCACHE
NOLOGGING
NOCOMPRESS
NOPARALLEL
NO INMEMORY
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT /*+ NOPARALLEL */ B.MDOTID, B.UNIT_KEY, AP.PERSON_KEY
  FROM ACCIDENT_PEOPLE  AP
       RIGHT OUTER JOIN
       (SELECT A.MDOTID AS MDOTID, UNIT_KEY
          FROM ACCIDENTS A JOIN ACCIDENT_UNITS U ON A.MDOTID = U.MDOTID) B
           ON B.MDOTID = AP.MDOTID AND b.unit_key = ap.unit_key;
