CREATE MATERIALIZED VIEW MV_CRASH_LOOKUPS
NOCACHE
NOLOGGING
NOCOMPRESS
NOPARALLEL
NO INMEMORY
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT table_name, id, description FROM mv_crash_lookups@crash;
