CREATE MATERIALIZED VIEW MV_CRASH_INJURYCOUNT
NOCACHE
NOLOGGING
NOCOMPRESS
NOPARALLEL
NO INMEMORY
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT crashreportid, injurydegree, COUNT (*) injcount
    FROM persons@CRASH
GROUP BY crashreportid, injurydegree;
